### ISSUE TITLE
Allow using different OpenAI/Azure keys for embeddings vs LLM endpoints

### ISSUE THREAD

**Issue by cpacker** [cpacker/MemGPT#1002]
See https://github.com/cpacker/MemGPT/discussions/999#discussioncomment-8461322

**Comment by thefux** [comment]
I could takle this issue but not sure where to start, either by extending the 'memgpt configure' menu to setup embeddings endpoint manually or .. ? 

https://github.com/cpacker/MemGPT/discussions/999#discussioncomment-8584069
