### ISSUE TITLE
SGLang Integration

### ISSUE THREAD

**Issue by merrymercy** [cpacker/MemGPT#1007]
For local models, SGLang should be able to greatly improve the latency/throughput of MemGPU by using its [fast JSON decoding](https://lmsys.org/blog/2024-02-05-compressed-fsm/) and [automatic KV cache reuse](https://lmsys.org/blog/2024-01-17-sglang/) feature.

This issue tracks the integration of SGLang for local models

**Comment by jackdiy** [comment]
This is awesome. I've been waiting for this.
