### ISSUE TITLE
Server:  Running now - next bug

### ISSUE THREAD

**Issue by philiprhoades** [cpacker/MemGPT#1010]
People,

I have created a new VM and installed via:

pip install pymemgpt

Describe the bug
See the output below.

How did you install memgpt?
pip install pymemgpt

Describe your setup:
What's your OS
Fedora Linux 38

How are you running memgpt?
kitty Terminal

MemGPT Config

[defaults]
preset = memgpt_chat
persona = phi_rho
human = phr

[model]
model = ehartford/dolphin-2.5-mixtral-8x7b
model_endpoint = https://api.memgpt.ai/
model_endpoint_type = vllm
model_wrapper = chatml
context_window = 32768

[embedding]
embedding_endpoint_type = hugging-face
embedding_endpoint = https://embeddings.memgpt.ai/
embedding_model = BAAI/bge-large-en-v1.5
embedding_dim = 1024
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /root/.memgpt/chroma

[recall_storage]
type = sqlite
path = /root/.memgpt

[metadata_storage]
type = sqlite
path = /root/.memgpt

[version]
memgpt_version = 0.3.2

[client]
anon_clientid = 000000000000000000006a2f1aa6ab4d

and then restored my DBs etc.

So now the server runs OK but trying to browse to "localhost:8283" I get:

```
{"detail":"Not Found"}
```
and on the server:
```
INFO:     Started server process [271]
INFO:     Waiting for application startup.
Writing out openapi.json file
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8283 (Press CTRL+C to quit)
INFO:     127.0.0.1:45912 - "GET / HTTP/1.1" 404 Not Found
```

**Comment by sarahwooders** [comment]
@philiprhoades I don't think this is an error necessarily - that `GET` endpoint just doesn't exist. You'll need to write your own  requests to the REST endpoint to get it working.

**Comment by sarahwooders** [comment]
Ok I will close this issue for now, but please make an issue if you have any other problems!
