### ISSUE TITLE
Increasing the size and functionality of the "person" text file.

### ISSUE THREAD

**Issue by philiprhoades** [cpacker/MemGPT#1022]
At the moment these files are limited to 2,000 characters but I am finding that it is better for me to load more info from files than it is for chatting - this is also critical when having to start with a clean slate and reproduce the memories.  At the moment the skeleton person looks like this:
```
This is what I know so far about the user, I should expand this as I learn more about them.
First name: Chad
Last name: 
Gender: Male
Age: 
Nationality: 
Occupation: 
Interests: 
```
I think we need arbitrary fields that can be added by the user like:
```
Views political:
Views social:
Relatives:
Friends:
Health:
Diary entries:
Emails:
Books:
Journal articles:
```
etc . . and the size of the file should be increased - perhaps to no functional limit eventually.

Also, it would be very nice if some of those fields, instead of just having text info, had full-path directory names where individual text files could be loaded from.

Of course a large initial load like this would take a while - but that is still better than retyping hundreds / thousands of the same entry dialogues every time you want to test out something slighty different in the setup but with the same initial data . .

I presume this idea creates technical problems for coding but is it potentially a viable development?

So far I have loaded stuff into archival memory via the documented method, but the chatbot doesn't seem to be aware of the stuff loaded like that - even when I ask leading questions about key words in the loaded file.

Thanks for all the work so far people!

**Comment by sarahwooders** [comment]
@philiprhoades thanks for this suggestion! One thing you could try is to create a new type of memory class in `memory.py` (extending `CoreMemory`), which puts data in explicit fields.  We actually have this in our roadmap (under "Better Memory Systems") https://docs.google.com/document/d/1NOJr5n8hfG1IZO_6c2HGfix1EVYq5rh8oNm7AWCrQPo/edit#heading=h.gubanhndhrt3 so would love to get external contributions! 

You can also edit the size of the core memory in `constants.py` with the fields `CORE_MEMORY_PERSONA_CHAR_LIMIT` and `CORE_MEMORY_HUMAN_CHAR_LIMIT`.

**Comment by philiprhoades** [comment]
@sarahwooders ,

> You can also edit the size of the core memory in constants.py with the fields CORE_MEMORY_PERSONA_CHAR_LIMIT and CORE_MEMORY_HUMAN_CHAR_LIMIT.

Yes, I already doubled the 2000 which worked happily - I was going to keep doubling to see how far I could go but I will def have a look at your link to see if I can do what I want more elegantly.

Thanks!

**Comment by philiprhoades** [comment]
@sarahwooders ,

After doing a backup and clean restart, I doubled CORE_MEMORY_*_CHAR_LIMITs to 8000  and my wc for:

.memgpt/humans/phr.txt

is now:

40  714  4350 

The increase in size resulted from adding information about siblings - however, the interaction after the resetup with the usual defaults was:

```
__ Analyzing user's persona and past conversations for better assistance.
__ Figuring out how best I can support you. Please stand by!

> Enter your message: What do you know about my siblings?

__ Searching archival memory for information on user's siblings.

____ [function] searching memory with archival_memory_search
        query: Siblings of Philip Rhoades, page: 0

__ Realizing that essential information about user's siblings is not in archival memory, I will ask for user input.

__ I don't have information on your siblings in the archives. Could you please tell me about them?
```
I think that the chatbot has been aware of new information added in previous tests - why doesn't he know about my siblings for this exercise?

Thanks people!
