### ISSUE TITLE
Developing using the MemGPT Python client: TypeError: agent_config must be of type dict

### ISSUE THREAD

**Issue by quantumalchemy** [cpacker/MemGPT#1040]
**Describe the bug**
Traceback (most recent call last):
  File "/root/.memgpt/test.py", line 46, in <module>
    agent_state = client.create_agent(agent_config=agent_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/memgpt/client/client.py", line 112, in create_agent
    raise TypeError(f"agent_config must be of type dict")
TypeError: agent_config must be of type dict

**Please describe your setup**
- [ ] How did you install memgpt?
pip install pymemgpt -U 
- [ ] Describe your setup
Linux
  -  
Using the sample : https://memgpt.readme.io/docs/python_client

dolphin-2.1-mistral-7b.Q6_K.gguf - quickstart free endpoint

CODE: 
from memgpt.config import AgentConfig
from memgpt import MemGPT
from memgpt import constants
from memgpt.cli.cli import QuickstartChoice

client = MemGPT(
	# When auto_save is 'True' then the agent(s) will be saved after every
	# user message.  This may have performance implications, so you
	# can otherwise choose when to save explicitly using client.save().
	auto_save=True,

	# Quickstart will automatically configure MemGPT (without having to run `memgpt configure`
	# If you choose 'openai' then you must set the api key (env or in config)
	quickstart=QuickstartChoice.memgpt_hosted,

	# Allows you to override default config generated by quickstart or `memgpt configure`
	config={}
)

# Create an AgentConfig with default persona and human txt
# In this case, assume we wrote a custom persona file "my_persona.txt", located at ~/.memgpt/personas/my_persona.txt
# Same for a custom user file "my_user.txt", located at ~/.memgpt/humans/my_user.txt
agent_config = AgentConfig(
	name="jacktheripper",
	preset = "memgpt_docs",
	persona = "dr_hyde",
	human = "phd_ace",
	model = "ehartford/dolphin-2.5-mixtral-8x7b",
	model_endpoint = "https://api.memgpt.ai",
	model_endpoint_type = "vllm",
	model_wrapper = "chatml",
	context_window = 16384,
	embedding_endpoint_type = "hugging-face",
	embedding_endpoint = "https://embeddings.memgpt.ai",
)

# Create the agent according to AgentConfig we set up. If an agent with
# the same name already exists it will simply return, unless you set
# throw_if_exists to 'True'
agent_state = client.create_agent(agent_config=agent_config)  ## ERROR 

# Create a helper that sends a message and prints the assistant response only
def send_message(message: str):
	"""
	sends a message and prints the assistant output only.
	:param message: the message to send
	"""
	response = client.user_message(agent_id=agent_state.id, message=message)
	for r in response:
	# Can also handle other types "function_call", "function_return", "function_message"
		if "assistant_message" in r:
			print("ASSISTANT:", r["assistant_message"])
		if "internal_monologue" in r:
			print("THOUGHTS:", r["internal_monologue"])

# Send a message and see the response
send_message("Please introduce yourself and tell me about your abilities!")

---
please advise - Thanks!

**Comment by sarahwooders** [comment]
Sorry we recently change the function for agent creation for the client https://github.com/cpacker/MemGPT/blob/main/memgpt/client/client.py#L217

You can see the updated example here https://github.com/cpacker/MemGPT/blob/main/examples/memgpt_client.py

We're actively working on the client (adding more functions, connecting it to the REST server) so sorry things will occasionally break!

**Comment by quantumalchemy** [comment]
thanks - so we need to run the server not import memgpt 
so maybe best to just use the api?  for integration going forward?

**Comment by sarahwooders** [comment]
You can run the client both with the server (docs: https://memgpt.readme.io/reference/api) or without it if you're just trying to run MemGPT locally. I'll close this issue for now but let us know if you run into other issues!
