### ISSUE TITLE
Feature Request: sending message to agent without user role

### ISSUE THREAD

**Issue by CUexter** [cpacker/MemGPT#1062]
**Is your feature request related to a problem? Please describe.**
I am now creating a custom function that calls a image generator. The image generation takes some time, and I don't want it to be blocking the conversation. I want to be able to notify the agent programmatically. 

**Describe the solution you'd like**
Able to change the role when running step function in agents

**Describe alternatives you've considered**
Not yet. Is there?

**Comment by sarahwooders** [comment]
Thanks for the suggesting! We added this to the roadmap #1044
