### ISSUE TITLE
🎉 MemGPT SF Meetup (March 12th)

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#1066]
We will be having a meetup at the [Anyscale Offices](https://www.google.com/maps/place/Anyscale/@37.7856552,-122.4010292,17z/data=!3m2!4b1!5s0x8085807daa4ddceb:0x57b442e3abb8851!4m6!3m5!1s0x808581374bdc8d51:0xac7cfbb4a6978010!8m2!3d37.7856552!4d-122.3984543!16s%2Fg%2F11s5gwp7s4?entry=ttu) on **March 12th**! 

We'd love to meet contributors, users, and also just people curious about MemGPT 😀 

If you'd like to attend, please register here: https://lu.ma/berkeleyllm

**Comment by philiprhoades** [comment]
Any chance of this being streamed for us foreigners?

**Comment by cpacker** [comment]
@philiprhoades not sure yet but we'll keep the request in mind and drop a link if we do end up streaming!

**Comment by cpacker** [comment]
@philiprhoades @haikyuu we did a webinar on Friday with the LlamaIndex team that's up on YouTube: https://www.youtube.com/watch?v=DwwBNjI1xBQ

It covers many of the same (MemGPT) topics that we went into during the meetup!

**Comment by cpacker** [comment]
Thank you everyone who came to the first Berkeley LLM meetup! We'll be hosting another one April 23rd, this time at the Databricks offices, we'd love to see you all there: https://lu.ma/berkeleyllm
