### ISSUE TITLE
Local instance fails to communicate with OpenAI

### ISSUE THREAD

**Issue by leonardsellem** [cpacker/MemGPT#107]
Hi,
I set up MemGPT locally, following religiously your instructions.
I got the few setup prompts (use the last config ? Which model ? Which persona ? Which user ?  Archive preloading ?) But then, I get a  tedious output that you can read in the attached file.
Basically, the meaningful parts seem to be :
```
│ │                waiter = <Future finished exception=SSLCertVerificationError(1, '[SSL:        │ │
│ │                         CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get  │ │
│ │                         local issuer certificate (_ssl.c:1002)')>                            │ │
```
and
```
APIConnectionError: Error communicating with OpenAI
```

I can't figure out what went wrong.
[error memgpt.txt](https://github.com/cpacker/MemGPT/files/13115190/error.memgpt.txt)

**Comment by angar4ik** [comment]
it is not related with memgpt

something interrupting with your ssl connection

are you on the laptop belonging to your company? do you have any sort of fancy firewall/antivirus?

**Comment by cpacker** [comment]
Thank you for the answer @angar4ik! I'm going to close this as it doesn't seem related to MemGPT specifically, but feel free to continue debugging discussion in the comments (or reopen the issue if you find that there's a problem on MemGPT's side).
