### ISSUE TITLE
quickstart OpenAI fails

### ISSUE THREAD

**Issue by distributev** [cpacker/MemGPT#1077]
I checked to have the correct OpenAI API key in ~/.memgpt/credentials

![image](https://github.com/cpacker/MemGPT/assets/19224635/88823344-2e9a-455a-bc84-86c5e89f2e02)

**Comment by sarahwooders** [comment]
I believe this is a connection error to OpenAI -- please check your internet connection if you have this issue. I'll close this for now but please re-open if you're able to connect to OpenAI but not connect from MemGPT.

**Comment by distributev** [comment]
![image](https://github.com/cpacker/MemGPT/assets/19224635/33e72cec-241b-4965-a07d-42d5c1ff3ba3)
