### ISSUE TITLE
SPR versus MemGPT 

### ISSUE THREAD

**Issue by stevenbaert** [cpacker/MemGPT#109]
Please share your view on SPR vs MemGPT

ref---
https://youtu.be/piRMk2KIx2o?si=aiPIRu7jlUABmudJ

Quote "don't use MemGPT, SPR is much easier and better" 

Also
https://medium.com/@daniellefranca96/spr-sparse-priming-representations-a0e9db13cca9
endref---

Only checked superficially but your take/insights are highly appreciated!

**Comment by angar4ik** [comment]
what is the issue you are reporting?

**Comment by stevenbaert** [comment]
No issue, just would appreciate your input. If that's not possible, feel free to close or remove this item.

**Comment by angar4ik** [comment]
Brother, that's not a forum

**Comment by cpacker** [comment]
There is already discussion about this on the discord, you can search there
