### ISSUE TITLE
bug: Permission denied.

### ISSUE THREAD

**Issue by palandovalex** [cpacker/MemGPT#1111]
**Describe the bug**
I use a proxy server that forwards my requests to openai, because when I try to log in directly, cloudflare appears.

I am able to use memGPT because it has the ability to override endpoint. However, when testing the library, the endpoint override is ignored. Because of this, it is not possible to test the library correctly. The following answers are returned to me:

```html
<title>Attention Required! | Cloudflare</title>
  <h2 class="cf-subheadline"><span data-translate="unable_to_access">You are unable to access</span> api.openai.com</h2>
    <div class="cf-columns two">
        <div class="cf-column">
           <h2 data-translate="blocked_why_headline">Why have I been blocked?</h2>
           <p data-translate="blocked_why_detail">This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.</p>
           </div>
           <div class="cf-column">
             <h2 data-translate="blocked_resolve_headline">What can I do to resolve this?</h2>
             <p data-translate="blocked_resolve_detail">You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray ID found at the bottom of this page.</p>
           </div>
         </div>
```

**Please describe your setup**
- [x] How did you install memgpt?
 `git clone`
- [x] Describe your setup
  - Linux
  i am running tests
**Screenshots**

**Additional context**

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

```ini
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = gpt-4
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 8192

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /home/lexsilentium/.memgpt/chroma

[recall_storage]
type = sqlite
path = /home/lexsilentium/.memgpt

[metadata_storage]
type = sqlite
path = /home/lexsilentium/.memgpt

[version]
memgpt_version = 0.3.5

[client]
anon_clientid = 000000000000000000004dd78c959640
```

**Comment by palandovalex** [comment]
What the!!!!

I previously configured memgpt by memgpt configure
An i set another endpoint! But here i see some realy strange!

**Comment by palandovalex** [comment]
I also noticed in the config that the embedding endpoint remains standard, despite the fact that I changed the gpt provider endpoint to a custom proxy.

**Comment by sarahwooders** [comment]
Are you running the MemGPT test suites with `pytest tests/...`? I think some of the tests will override the config to get a certain configuration during testing. We need to set it up so that you can override the config location temporarily during testing, but haven't gotten to that yet.

**Comment by sarahwooders** [comment]
As of now, I dont think there is any way to override the OpenAI endpoint in the tests unless you modify the code in the tests to use the proxy endpoint instead of setting the OpenAI default endpoint.
