### ISSUE TITLE
Error: externally-managed-environment

### ISSUE THREAD

**Issue by libersoft-org** [cpacker/MemGPT#112]
I just git cloned the project and followed instructions in README (in Debian 12):

-----------------
root@web-test:/data/MemGPT# pip install -r requirements.txt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
-----------------

Would be great if you can fix the README installation instructions.

Thank you.

**Comment by sarahwooders** [comment]
Could you run `pip install pymemgpt`? The docs haven't been updated yet but we just pushed a package.

**Comment by libersoft-org** [comment]
> Could you run `pip install pymemgpt`? The docs haven't been updated yet but we just pushed a package.

The same result:

root@web-test:/data/MemGPT# pip install pymemgpt
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

**Comment by sarahwooders** [comment]
Could you try following either of the recommended options of creating a virtual env, or using pipx?

**Comment by libersoft-org** [comment]
root@web-test:/data/MemGPT# pipx install pymemgpt
  installed package pymemgpt 0.1.2, installed using Python 3.11.2
  These apps are now globally available
    - memgpt
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is updated. Run `pipx ensurepath` to
    automatically add it, or manually modify your PATH in your shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨
root@web-test:/data/MemGPT# memgpt
-bash: memgpt: command not found
root@web-test:/data/MemGPT# pipx ensurepath
Success! Added /root/.local/bin to the PATH environment variable.

Consider adding shell completions for pipx. Run 'pipx completions' for instructions.

You will need to open a new terminal or re-login for the PATH changes to take effect.

Otherwise pipx is ready to go! ✨ 🌟 ✨
root@web-test:/data/MemGPT# memgpt
-bash: memgpt: command not found
root@web-test:/data/MemGPT# pymemgpt
-bash: pymemgpt: command not found

**Comment by cpacker** [comment]
Hi @libersoft-org , please try the new recommended install `pip install pymemgpt`. If that doesn't work feel free to re-open the issue.

**Comment by libersoft-org** [comment]
> Hi @libersoft-org , please try the new recommended install `pip install pymemgpt`. If that doesn't work feel free to re-open the issue.

It works now, but not with "pip", but with "pipx". Would be great if you mention this in README and add there what dependencies should people install. Thanks a lot for your help.

**Comment by lydacious** [comment]
@libersoft-org hello, I'm having the same issue. what did you do to fix?

**Comment by libersoft-org** [comment]
> @libersoft-org hello, I'm having the same issue. what did you do to fix?

used "pipx" instead of "pip"
