### ISSUE TITLE
Local LLM not setting backend correctly and expects openai key?

### ISSUE THREAD

**Issue by IreGaddr** [cpacker/MemGPT#114]
As you can see I'm setting the backend to webui, but it's still trying to query an openAPI key?
![Screenshot 2023-10-24 215021](https://github.com/cpacker/MemGPT/assets/130914610/10faf980-a4b4-4781-9958-a7a9d3203850)
![Screenshot 2023-10-24 215144](https://github.com/cpacker/MemGPT/assets/130914610/f9e9e056-3d1a-4f67-a7f3-3caf669974bf)
![Screenshot 2023-10-24 215203](https://github.com/cpacker/MemGPT/assets/130914610/78f026bf-9076-4a22-ba85-0d629810d7d4)

**Comment by cpacker** [comment]
Do `set BACKEND_TYPE=webui` (no spaces)

https://stackoverflow.com/questions/55500857/how-can-i-set-the-environment-variables-in-windows
