### ISSUE TITLE
REST API Agent creation fails (POST api/agents)

### ISSUE THREAD

**Issue by gberrido** [cpacker/MemGPT#1166]
**Describe the bug**
Agent create fails on POSTAPI endpoint /api/agents
**Please describe your setup**
- How did you install memgpt? git clone
- Describe your setup
MacOs silicon / Docker Desktop

I run python examples/memgpt_client.py
Admin authentication -> OK
User/token creation -> OK
Agent creation -> NOT OK

**Screenshots**
docker run -p 8083:8083 -e OPENAI_API_KEY memgpt-server
Generated admin server password for this session: Y1m_5Z40kHdE-2gvQjGOaw
User ID: 00000000-0000-0000-0000-0242ac110002
INFO:     Started server process [1]
INFO:     Waiting for application startup.
Writing out openapi_memgpt.json file
Writing out openapi_assistants.json file
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8083 (Press CTRL+C to quit)
INFO:     192.168.65.1:56616 - "POST /admin/users HTTP/1.1" 200 OK
INFO:     192.168.65.1:56617 - "POST /api/agents HTTP/1.1" 403 Forbidden
**Additional context**
Exact same issue when trying to create an agent using the curl command. curl GET/POST users works
curl GET api/agents works but curl POST api/agents fails on authentication (403 forbidden)
**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.
[defaults]
preset = memgpt_chat
persona = seren
human = basic

[model]
model = gpt-4
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 8192

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-ada-002
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /Users/nabu/.memgpt/chroma

[recall_storage]
type = sqlite
path = /Users/nabu/.memgpt

[metadata_storage]
type = sqlite
path = /Users/nabu/.memgpt

[version]
memgpt_version = 0.3.6

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000
---

**Comment by sarahwooders** [comment]
Did you attach the user bearer token to the request? The `POST /admin/users` route should return JSON that has an `api_key` field for the `user_id`, which you need to use as the bearer token.

**Comment by sarahwooders** [comment]
Since this isn't very well documented, just wanted to clarify that there are two levels of authentication: 
* Admin auth: permission for `/admin` routes, where the token comes from `memgpt server` or can be set with `export MEMGPT_SERVER_PASS=test_server_token`
* User auth: permissions for `/api` routes where the token is created via the admin routes (e.g. creating a user, creating a new key)

**Comment by gberrido** [comment]
>>there are two levels of authentication. Yes the auth for both works fine. GET /api/agents to list agents works with the created user key, but authentication fails with the same key when trying to create an agent POST /api/agents
I just tried again now with the latest nightly build: 
SERVER SIDE: 
memgpt server
Generated admin server password for this session: jb8ZEfjovl2k6b0HAl33FQ
User ID: 00000000-0000-0000-0000-000000000000
DEBUG False
Running: uvicorn <fastapi.applications.FastAPI object at 0x13d043450>:app --host localhost --port 8283
INFO:     Started server process [88952]
INFO:     Waiting for application startup.
Writing out openapi_memgpt.json file
Writing out openapi_assistants.json file
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8283 (Press CTRL+C to quit)
INFO:     ::1:56175 - "GET / HTTP/1.1" 404 Not Found
INFO:     ::1:56175 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     ::1:56289 - "POST /admin/users HTTP/1.1" 200 OK
INFO:     ::1:56290 - "POST /api/agents HTTP/1.1" 403 Forbidden

CLIENT SIDE:
python examples/memgpt_client.py
{'user_id': 'dc16df4e-49bd-4ec7-a8d8-e50305d182ba', 'api_key': 'sk-d8ad5e88cfa1782b89adcede4179ac14b5eb36dce39b2b18'}
Created user: ('user_id', UUID('dc16df4e-49bd-4ec7-a8d8-e50305d182ba')) with token: ('api_key', 'sk-d8ad5e88cfa1782b89adcede4179ac14b5eb36dce39b2b18')
Traceback (most recent call last):
  File "/Users/nabu/Projects/MemGPT/MemGPT/examples/memgpt_client.py", line 53, in <module>
    main()
  File "/Users/nabu/Projects/MemGPT/MemGPT/examples/memgpt_client.py", line 27, in main
    agent_info = client.create_agent(
                 ^^^^^^^^^^^^^^^^^^^^
  File "/Users/nabu/Projects/MemGPT/MemGPT/memgpt/client/client.py", line 250, in create_agent
    raise ValueError(f"Failed to create agent: {response.text}")
ValueError: Failed to create agent: {"detail":"Authentication error: Token ('api_key', 'sk-d8ad5e88cfa1782b89adcede4179ac14b5eb36dce39b2b18') does not exist"}

**Comment by gberrido** [comment]
This is tested with the client in memgpt/examples/memgpt_client.py
Manual curl commands give the exact same result.

**Comment by sarahwooders** [comment]
There were a few bugs in the example since I forgot to update them after changing the client return type to pydantic objects - does the updated example in #1174 work for you? It's possible you've found a separate issue.

**Comment by gberrido** [comment]
That works! awsome. Thanks for the great work.
