### ISSUE TITLE
Azure embedding not possible

### ISSUE THREAD

**Issue by LukeTS117** [cpacker/MemGPT#118]
When using Azure OpenAI it still tries to embbed using the regular OpenAI API. I might be blind, but I can't find a way to configure memgpt to use an Azure embedding model. 

![Capture](https://github.com/cpacker/MemGPT/assets/32310130/69609be3-dce4-420d-ac8d-3a73531d9610)

**Comment by shagu2021** [comment]
facing the same issue

**Comment by mlops-v2-gs** [comment]
same here. would be get this sorted as well.

**Comment by cpacker** [comment]
This is a bug on our end, will be patched shortly! Thank you for opening an issue

**Comment by cpacker** [comment]
Actually @vivi any idea why this might be happening?

I thought it was because we were missing the Azure support on the call to `acreate_embedding_with_backoff`, but I went to go patch it and realized it was already there: https://github.com/cpacker/MemGPT/blob/main/memgpt/openai_tools.py#L128-L131

Is there anywhere else we're calling embeddings directly that would bypass this?

**Comment by vivi** [comment]
Looking into this (currently getting our hands on an Azure account we can debug on).

**Comment by chandeldivyam** [comment]
A few months back while implementing a RAG, had once a similar issue, I had to deploy a separate model with a different deployment for embedding. Here, I think we are using the same azure model for both chat completion and embedding and hence the error:
```
@aretry_with_exponential_backoff
async def acreate_embedding_with_backoff(**kwargs):
    """Wrapper around Embedding.acreate w/ backoff"""
    azure_openai_deployment = os.getenv("AZURE_OPENAI_DEPLOYMENT")
    if azure_openai_deployment is not None:
        kwargs["deployment_id"] = azure_openai_deployment
    return await openai.Embedding.acreate(**kwargs)
```

`azure_openai_deployment = os.getenv("AZURE_OPENAI_DEPLOYMENT")`

We could add a different env variable for `AZURE_EMBEDDING_OPENAI_DEPLOYMENT` and use that for our usecase. I thnk that could resolve the problem @LukeTS117

**Comment by LukeTS117** [comment]
> We could add a different env variable for `AZURE_EMBEDDING_OPENAI_DEPLOYMENT` and use that for our usecase. I thnk that could resolve the problem @LukeTS117

Yeah that should fix it

**Comment by vivi** [comment]
Will push a fix for this tomorrow!
