### ISSUE TITLE
Make sure that the vLLM server is running and reachable at https://api.memgpt.ai/v1/completions.

### ISSUE THREAD

**Issue by philiprhoades** [cpacker/MemGPT#1185]
Describe the bug:
Problems with bot processing / retrieving info from the human text file.

Recreating VMs from scratch and / or:
Recreating humans and agents with:
SQL dump of DBs.
Clean of DBs.

Please describe your setup:
What is the output of memgpt version? (eg "0.2.4")
0.3.2 , 0.3.3 , 0.3.4, 0.3.7 for different VMs.

How did you install memgpt?

pip install pymemgpt
or:
pip install pymemgpt==0.3.2 etc

Describe your setup:
What's your OS:
Fedora Linux v38 (for Python3.11)

How are you running memgpt?
tmux Terminal

Recently whether I use the unchanged CORE_MEMORY_PERSONA_CHAR_LIMIT and CORE_MEMORY_HUMAN_CHAR_LIMIT of 2000 or my attempts at 8000, using all the defaults I still get the above error - so I am guessing the problem is not really that the vLLM server is unreachable . . 

Anyway, just to test that hypothesis, I thought I should set up a minimal, local vLLM that will work with defaults but which I can then test with increased CORE_MEMORY_PERSONA_CHAR_LIMIT and CORE_MEMORY_HUMAN_CHAR_LIMIT . . is this possible?

Thanks.

**Comment by quantumalchemy** [comment]
yeah the api.memgpt.ai endpoint has been on error (times-out) since yesterday - 
I think they have been working on a new llm - so that maybe.. wait and see hope its back soon

**Comment by philiprhoades** [comment]
> wait and see hope its back soon

Oh right - just checked and it is still an issue - will try again later . .

Thanks!

**Comment by philiprhoades** [comment]
Server seems to be running again.
