### ISSUE TITLE
APIConnectionError: Error communicating with OpenAl

### ISSUE THREAD

**Issue by dengweixing1996** [cpacker/MemGPT#119]
I have tried many methods, but they all failed. I have set up a proxy in Anaconda and tried many nodes at the same time. I also configured APIKEY in the project, but I can't connect to OPENAI. I can ping OPENAI's official website. But I can’t connect to the project.

**Comment by cpacker** [comment]
Deleting issue, please make a new one with sensitive information redacted (or join the discord so that we can help you debug there via DMs)
