### ISSUE TITLE
ChatUI - offer a docker-compose.yml to easily deploy chatui using docker

### ISSUE THREAD

**Issue by distributev** [cpacker/MemGPT#1192]
Now when deploying chatui on a VPS server it is required to expose to internet port 4200 (or other port when chatui will be configured to run).

When running inside docker no port will be expose through internet because ChatUI will run behind a web proxy (eg. nginx)

**Comment by sarahwooders** [comment]
We are moving towards defaulting to the new dev portal, which is available via docker compose.
