### ISSUE TITLE
[function] searching memory with conversation_search FAILED

### ISSUE THREAD

**Issue by tucaodashen** [cpacker/MemGPT#1199]
i just create a chatbot whit defult api.
then i chat with her for a while.
then i asked if you could list all the conversation we had haven.
then it began to use the [function] searching memory with conversation_search and constantly fail.
I don't konw what's going on and how to slove it.
![bug](https://github.com/cpacker/MemGPT/assets/121039198/a26d0b41-22cd-4fbf-b0fc-7bc67ec621dc)

**Comment by quantumalchemy** [comment]
similar (problem with archive / search functions)  Error calling function core_memory_append: Edit failed: Exceeds 2000 character limit (requested 3120). Consider summarizing existing core memories in 'persona' and/or moving lower priority content to archival memory to free up space in core memory, then trying again.  --> then loops again
Also --> No function named step1_archivall_search_matching_query   ->  ** so archival search not working.. but memory shows the data for the answer is there  (using  free memgpt endpoint)

**Comment by sarahwooders** [comment]
I believe this is a model issue - closing for now but please feel free to re-open.
