### ISSUE TITLE
its running in lm studio  , but its not workings 

### ISSUE THREAD

**Issue by offbeatsgames** [cpacker/MemGPT#1231]
![Screenshot 2024-04-08 041701](https://github.com/cpacker/MemGPT/assets/132132055/47363c50-c2d8-4537-a701-0ef3348c751b)
ists a error i cant able to fic 

here LM studio side :
![Screenshot 2024-04-08 041823](https://github.com/cpacker/MemGPT/assets/132132055/3c34bd89-488e-49f8-8007-16817846676d)

please  help to find fix of it

**Comment by adarsh-trenser** [comment]
Me too facing this issue. But memgpt working fine with OpenAI API
