### ISSUE TITLE
Compose server cleanup

### ISSUE THREAD

**Issue by norton120** [cpacker/MemGPT#1233]
I spun up the server today and ran into a handful of problems with CORS swagger issues (there are conflicts between the 8083 and 8283 mappings), and a handful of additional mods to make it locally editable/ hot reloads etc. I squared away my local a bit, but if I wanted to clean up a bit - say add a reverse proxy and clean up the compose, add a health check etc - would that be a PR y'all are interested in?

**Comment by sarahwooders** [comment]
@norton120 yes that would be fantastic, thank you!
