### ISSUE TITLE
Issue using MemGPT with AutoGen

### ISSUE THREAD

**Issue by hframa** [cpacker/MemGPT#124]
When I try to run the sample code demonstrating how to use MemGPT with AutoGen, I get a runtime error: 
"RuntimeError: asyncio.run() cannot be called from a running event loop".

I cannot seem to figure out what I am doing wrong.

Sample code: https://github.com/cpacker/MemGPT/discussions/65

![Screenshot from 2023-10-26 07-33-41](https://github.com/cpacker/MemGPT/assets/33560589/98c8c97c-f23c-43e9-835c-7e3f415b0da5)
![Screenshot from 2023-10-26 07-32-58](https://github.com/cpacker/MemGPT/assets/33560589/c2ea287d-2d41-4ba8-9a07-c5cff3d931bd)

Sorry if I am not smart.

**Comment by vivi** [comment]
See the new example introduced by #123, we did some refactoring that should have solved this.

**Comment by cpacker** [comment]
@hframa which jupyter notebook are you referring to? We didn't publish any notebooks, just an example code snippet which is now also checked into the git repo [here](https://github.com/cpacker/MemGPT/tree/main/memgpt/autogen/examples).

Or do you mean the example linked above works when you just run the python file, but fails when you try to take the code out into a Jupyter notebook? If that's the case, can you share the contents of the notebook eg via a google colab link so we can try to debug it?

**Comment by cpacker** [comment]
> Thank you, and sorry.
> 
> I think I messed up something on my part, which I cant seem to figure out.
> 
> Following is the link to the Jupyter Notebook: https://colab.research.google.com/drive/1boC1Ghsla8AISAy8nbgSWNZzX6xPLmgK?usp=sharing

can you open view access on the notebook?
