### ISSUE TITLE
AttributeError on Retrieving Messages: 'str' Object Has No Attribute 'tzinfo' After Multiple Fetches

### ISSUE THREAD

**Issue by glindberg2000** [cpacker/MemGPT#1264]
**Summary:**
Fetching the latest messages from the REST API for an agent with more than three messages generates an internal server error. The error occurs due to a type mismatch in handling datetime objects, where the server expects a datetime object but receives a string instead. This error is thrown in the to_json method when attempting to check if the created_at attribute is timezone-aware.

**Config:**
installed: pip install pymemgpt
setup: linux, Mac (same error on both)
config: standard openAI config

**Screenshots**
<img width="635" alt="bug2" src="https://github.com/cpacker/MemGPT/assets/148168828/43f35521-88d4-4a3e-9375-ee135e721adb">
<img width="516" alt="bug3" src="https://github.com/cpacker/MemGPT/assets/148168828/9e4e90a9-4f94-4b50-ad9a-5c25daed3386">

**Steps to Reproduce:**
Create a New Agent: Use the provided cURL command in the documentation to create a new agent.
Send Messages: Send at least three messages to the new agent using the cURL command provided in the documentation.
Retrieve Messages: Use the cURL command to fetch messages for the agent.
Repeat Message Retrieval: Attempt to fetch messages again. The retrieval command will generate the error shown above.
Behavior Observed: The error consistently occurs when retrieving messages after the third message has been sent to the agent. This behavior is consistent across different client implementations, including Python REST clients.
Restarting memgpt will sometimes clear the error one time, but subsequent fetches result in same error

**Proposed Fix:**
I was able to resolve the issue by modifying _data_types.py_: the function to_json within the Message class should be modified to ensure created_at is always a timezone-aware datetime object before serialization. Here is the revised function snippet that resolves the issue:
```

import copy
from datetime import datetime, timezone

def to_json(self):
    temp_message = copy.deepcopy(self)
    if isinstance(temp_message.created_at, str):
        try:
            temp_message.created_at = datetime.strptime(temp_message.created_at, '%Y-%m-%d %H:%M:%S%z')
        except ValueError:
            temp_message.created_at = datetime.now(timezone.utc)
    if temp_message.created_at.tzinfo is None or temp_message.created_at.tzinfo.utcoffset(temp_message.created_at) is None:
        temp_message.created_at = temp_message.created_at.replace(tzinfo=timezone.utc)
    json_message = vars(temp_message)
    if json_message["tool_calls"] is not None:
        json_message["tool_calls"] = [tc.to_dict() for tc in json_message["tool_calls"]]
    json_message["created_at"] = temp_message.created_at.isoformat()
    return json_message



```

**Comment by ZhouYimao** [comment]
Nice!
