### ISSUE TITLE
about paper_experiments

### ISSUE THREAD

**Issue by hshc123** [cpacker/MemGPT#1277]
Hello, I was wondering if the "paper_experiments" directory of the project code is missing the "MemGPT for Conversational Agents" experiment?

**Comment by sarahwooders** [comment]
Yes we have this code in a different repo but it still needs to be cleaned up and merged -- if you reach out to our berkeley emails we can share the code with you!

**Comment by hshc123** [comment]
> Yes we have this code in a different repo but it still needs to be cleaned up and merged -- if you reach out to our berkeley emails we can share the code with you!

I've previously reached out to you via your Berkeley email addresses inquiring about the "MemGPT for Conversational Agents" experiment code, but I haven't received a response yet. I'm highly interested in this particular aspect of your project and would greatly appreciate it if you could share the code with me. My email address is [hshc123@qq.com](mailto:hshc123@qq.com). I look forward to hearing from you soon.
