### ISSUE TITLE
connect error

### ISSUE THREAD

**Issue by dengweixing1996** [cpacker/MemGPT#128]
I have tried many methods, but they all failed. I have set up a proxy in Anaconda and tried many nodes at the same time. I also configured KEY in the project, but I can't connect to apikeyserver. I can ping this official website. But I can’t connect to the project.

**Comment by cpacker** [comment]
What are you trying to do here? What is the IP - is it routing to an official OpenAI API server (that supports function calling)?

If this is an OpenAI API server, then you need to set `OPENAI_API_BASE` to the exact address of the API. For example, the default for `OPENAI_API_BASE` is `https://api.openai.com/v1/chat/completions`, not `https://api.openai.com`. You can check taht this server IP you're pointing at is OK by sending a curl request, just replace `https://api.openai.com/v1/chat/completions` with the IP you're trying to test:

```sh
curl https://api.openai.com/v1/chat/completions \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $OPENAI_API_KEY" \
-d '{
  "model": "gpt-4",
  "messages": [
    {
      "role": "user",
      "content": "What is the weather like in Boston?"
    }
  ],
  "functions": [
    {
      "name": "get_current_weather",
      "description": "Get the current weather in a given location",
      "parameters": {
        "type": "object",
        "properties": {
          "location": {
            "type": "string",
            "description": "The city and state, e.g. San Francisco, CA"
          },
          "unit": {
            "type": "string",
            "enum": ["celsius", "fahrenheit"]
          }
        },
        "required": ["location"]
      }
    }
  ],
  "function_call": "auto"
}'

```

Is it pointing to an Azure server? Then you have to follow more examples here: https://github.com/cpacker/MemGPT#running-memgpt-locally

Is it pointing to a locally hosted LM server? Then you have to follow these instructions here: https://github.com/cpacker/MemGPT/tree/main/memgpt/local_llm

Can you try some extremely basic code to see if your IP is working?

**Comment by cpacker** [comment]
Closing because seems to be an error with the IP (should be fixed by instructions above), feel free to re-open if nothing linked above works.
