### ISSUE TITLE
Config's URI is overridden

### ISSUE THREAD

**Issue by theocnrds** [cpacker/MemGPT#1319]
**Describe the bug**
When configuring MemGPT with a connection uri to our PostgreSQL database via `memgpt configure` the connection uri is overridden either by set env variables (`pg_uri` which leads to problems when specifying options in the uri because it's using `pg8000`) or by the default values. The passed connection string is not used at all.
Since `settings.pg_uri`in this [line of code](https://github.com/cpacker/MemGPT/blob/main/memgpt/metadata.py#L329) always returns a string `config.metadata_storage_uri` will never be used. The way it was implemented in 0.3.11 was working.

**Please describe your setup**
- [x] How did you install memgpt?
  - `pip install pymemgpt`
- [x] Describe your setup
  - MacOS
  - Running in Terminal within Conda env.

**MemGPT Config**
[model]
model = gpt-4-1106-preview
model_endpoint = https://api.openai.com/v1
model_endpoint_type = openai
context_window = 128000

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://api.openai.com/v1
embedding_model = text-embedding-ada-002
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = postgres
path = /Users/tc_frogs42/.memgpt/chroma
uri = postgresql://<USER>:<PASSWORD>@<HOST>:5432/postgres?options=-csearch_path=memgpt

[recall_storage]
type = postgres
path = /Users/tc_frogs42/.memgpt
uri = postgresql://<USER>:<PASSWORD>@<HOST>:5432/postgres?options=-csearch_path=memgpt

[metadata_storage]
type = postgres
path = /Users/tc_frogs42/.memgpt
uri = postgresql://<USER>:<PASSWORD>@<HOST>:5432/postgres?options=-csearch_path=memgpt

[version]
memgpt_version = 0.3.13

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

**Comment by sarahwooders** [comment]
Thanks for reporting this! We should only override the config if the URI is provided via the environment variables -- I added a fix in #1327
