### ISSUE TITLE
UPDATE pip install  only:  latest: v03.13 : Not Found configs/memgpt_hosted.json / AssertionError: Must provide llm_config field when creating an Agent from a Preset - 

### ISSUE THREAD

**Issue by quantumalchemy** [cpacker/MemGPT#1320]
**Describe the bug**
AssertionError: Must provide llm_config field when creating an Agent from a Preset
looking for -->
Config file not found at /usr/local/lib/python3.11/site-packages/memgpt/cli/../../configs/memgpt_hosted.json

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt`
- [ ] Describe your setup
  - Linux
  - How are you running `memgpt`? Terminal 

**MemGPT Config**
error occurs befor write of config

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**
memgpt free endpoint  
memgpt run

**Comment by quantumalchemy** [comment]
also tested memgpt quickstart --backend memgpt
SCRIPT /usr/local/lib/python3.11/site-packages/memgpt/cli
FILE PATH /usr/local/lib/python3.11/site-packages/memgpt/cli/../../configs/memgpt_hosted.json
Config file not found at /usr/local/lib/python3.11/site-packages/memgpt/cli/../../configs/memgpt_

**Comment by sarahwooders** [comment]
When do you get this error? When you run `memgpt run`? 

Can you post whats in your `~/.memgpt/config` file?

**Comment by hgrigolli** [comment]
I've got the same error. I was inspecting the memgpt/cli/cli.py and it looks for the config file that is not found. 

https://raw.githubusercontent.com/cpacker/MemGPT/main/memgpt/configs/memgpt_hosted.json

**Comment by quantumalchemy** [comment]
yes: memgpt run
only when 'pip install' (03.13) is used 
-> error occurs before the config is written ..
