### ISSUE TITLE
Possibility to influence when to use external context

### ISSUE THREAD

**Issue by PizBernina** [cpacker/MemGPT#135]
"MemGPT knows when to push critical information to a vector database" 

Is it somehow already possible to influence when external context is being used?
Can I set some threshold and only if it is reached it uses the external context?

I believe I could currently "only" influence it with a preprompt, right? So, I would need to add it in the main context.

**Comment by cpacker** [comment]
You can influence MemGPT via the `persona` as well as during active conversation.

You can tell MemGPT in the `persona` (or `human` / user file) how to use its memory, eg:

```text
Your task is to help the user write a novel. To accomplish this task, you should use your limited core memory to store important high-level details about the novel, and use your archival memory to store other information about the plot or characters that is too long to fit into core memory.
```

Or in conversation:

```text
MemGPT: ...
User: Can you insert this into archival memory for me? ____
```
