### ISSUE TITLE
Would this be a simplified version of Langchain?

### ISSUE THREAD

**Issue by AnitaSherry** [cpacker/MemGPT#1375]

**Comment by MrFCow** [comment]
Even both solution seems to use the similar gears (a.k.a. the LLM and prompting on LLM, LLM tool/function usage) , I would consider they have different purpose/philosophy.  

MemGPT here is to foucs on the out of context memory handling in a way that how a OS work (multi-layers of memory and some being faster like cache and some being slower like disk) [their published research paper explained that]

While langchain's focus is more diverse, trying to work on more problems and having differenrt paper implemented in their ecosystem.

**Comment by AnitaSherry** [comment]
Understood. Thanks
