### ISSUE TITLE
ModuleNotFoundError: No module named 'pgvector'

### ISSUE THREAD

**Issue by aBaldoqui** [cpacker/MemGPT#1378]
**Describe the bug**
After instaling Devel version, and runing, results in ```ModuleNotFoundError: No module named 'pgvector'```

**Please describe your setup**
- [ ] How did you install memgpt?
```
git clone https://github.com/cpacker/MemGPT.git
pip install -e .
```
- [ ] Describe your setup
  - using venv in OS: Manjaro Linux x86_64
  - How are you running `memgpt`?
```
memgpt quickstart
memgpt run
```

**Comment by aBaldoqui** [comment]
Im sorry, was just a dependency error, pip install pgvector and pip install pg8000 solved this.

**Comment by sarahwooders** [comment]
If you want to run with postgres, you should run `pip install -e '.[postgres]'`.
