### ISSUE TITLE
Memory unit tests for evaluating local LLMs

### ISSUE THREAD

**Issue by cpacker** [cpacker/MemGPT#139]
Given how popular local llms + memgpt seems to be (at least in general interest) it might be worth setting up some "memory unit test" scripts so that we can quickly eval different models

---

### Bare minimum tests

1. /exit and /load works fine
2. memory edit works fine (my name is X not Y)
3. memory search works fine ("can you search the conversation for Z?")

**Comment by plaunezkiy** [comment]
Conceptually, are there any metrics or any research into evaluating LLM's output? It would be fun to explore, because it's a non-deterministic task
