### ISSUE TITLE
Load CSV files

### ISSUE THREAD

**Issue by kredens** [cpacker/MemGPT#14]
It will be helpful to load CSV files.

**Comment by cpacker** [comment]
Just to get an better idea of your workflow, can you tell us a little more about the size / format of your data?

E.g., how many CSV files? How many lines in the CSV file?

This will help us add the feature.

**Comment by cpacker** [comment]
@kredens feature added!

see https://github.com/cpacker/MemGPT/pull/45#issuecomment-1771830752 for an example

**Comment by kredens** [comment]
For now, I'm playing around with some data just to see what's possible. I have ~600k trademark registrations and I'm analyzing how your solution handles this. What I'm looking for is a solution where a user can ask the database if the desired brand is already registered in their field.
