### ISSUE TITLE
Have issue on running "memgpt quickstart" or "MemGPT run"

### ISSUE THREAD

**Issue by feilliu** [cpacker/MemGPT#1404]
**Describe the bug**

$ memgpt quickstart
Config file not found at /home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.10/site-packages/memgpt/cli/../../configs/memgpt_hosted.json

$MemGPT run

![01_54_37](https://github.com/cpacker/MemGPT/assets/166539225/97ede4c8-204f-4fa4-8507-ef5d0e5c82f4)

**Please describe your setup**
- [ ] How did you install memgpt?
  - `pip install pymemgpt`? `pip install pymemgpt-nightly`? `git clone`?

pip install pymemgpt

- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?  MacOS
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal). Powershell

**Screenshots**

**Additional context**

**MemGPT Config**
Please attach your `~/.memgpt/config` file or copy past it below.

Can't find this one when I pip install pymemgpt and memgpt quickstart.  After run memgpt configure, it then can find this file, but still experience the issue above.

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by datashaman** [comment]
https://github.com/cpacker/MemGPT/issues/1341#issuecomment-2132694838

**Comment by sarahwooders** [comment]
A hack around this problem is to do `memgpt quickstart --latest` instead -- but will fix this bug soon sorry!
