### ISSUE TITLE
Remove unnecessary `async` code 

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#141]
MemGPT runs from a `async def main(...)` function called in `main.py`, however none of the code needs to be async. There are many parts of the code which are written in async as a result, which would all be removed.

**Comment by cpacker** [comment]
`async` all the things 😈

**Comment by vivi** [comment]
in `async` we trust 😩

**Comment by cpacker** [comment]
```python
import asyncio

async def hello_world():
    return "Hello, World!"

async def main():
    message = await hello_world()
    print(message)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
```

**Comment by QZGao** [comment]
While `async` seems unnecessary from the command line, the Discord bot would appreciate `async` and `await` right?

**Comment by sarahwooders** [comment]
I believe the discord bot runs on different code @cpacker -- but to minimize code changes, we can maybe just start removing async functions for configuration and persistent state management, but keeping the main loop async?

**Comment by cpacker** [comment]
Closed since this was addressed by #156 but now there's a bug introduced by the sync PR #162

**Comment by vivi** [comment]
reopening to remove async once and for all because managing both is too bug-prone:
- [ ] Modify all code in this repo to use Agent instead of AsyncAgent
- [ ] Remove AsyncAgent and all the async supporting code
- [ ] Open up issue/discussion with guide on how to convert Agent to be async if you want to use memgpt in a discord bot (unofficial support)

**Comment by Simsalaba** [comment]
I'm glad to hear you are considering removing async. I was trying to fix the issue I get when trying to run memgpt with autogen (TypeError: cannot unpack non-iterable coroutine object). It was difficult to understand what needs to be async and what needs not.

**Comment by sarahwooders** [comment]
Done with #400
