### ISSUE TITLE
Support using a vector database for archival storage 

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#142]
Archival and recall memory should be able to be backed up into a database, rather than in a local FAISS index. 

MemGPT can support the following options for storing data: 
* Local FAISS index 
* Local vector DB 
* Remote vector DB

**Comment by lightningorb** [comment]
https://github.com/pgvector/pgvector-python/blob/master/examples/openai_embeddings.py

**Comment by sarahwooders** [comment]
It looks like Llama Index has a nice example with [Postgres](https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/postgres.html), so we can add a `PostgresArchivalMemory(ArchivalMemory)` that uses this once #154 is merged.
