### ISSUE TITLE
sqlalchemy error after upgrade to 0.3.18 from 0.3.17

### ISSUE THREAD

**Issue by MisileLab** [cpacker/MemGPT#1485]
**Describe the bug**
Error when use `memgpt server`

**Please describe your setup**
- [x] How did you install memgpt?
  - `pdm add pymemgpt` (same as `pip install pymemgpt`)
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)? Linux(nixos)
  - How are you running `memgpt`? bash(pdm run memgpt)

**Additional context**
[log](https://bpa.st/CV6A)

**MemGPT Config**
https://bpa.st/UXYQ

**Comment by sarahwooders** [comment]
If you don't mind losing data, you can do `rm ~/.memgpt/sqlite.db` to reset your database. Otherwise we can post a migration script sometime this weekend. Sorry for the breaking changes!

**Comment by MisileLab** [comment]
> If you don't mind losing data, you can do `rm ~/.memgpt/sqlite.db` to reset your database. Otherwise we can post a migration script sometime this weekend. Sorry for the breaking changes!

Ok, thank you!
I'll wait for migration script.

**Comment by sarahwooders** [comment]
I added a script in this PR: https://github.com/cpacker/MemGPT/pull/1489

Note that if you added custom tools, you will need to re-add them since this resets the tool database.

**Comment by MisileLab** [comment]
I'll close this issue, use migration script if error
