### ISSUE TITLE
Rate Limit issue with gpt3.5-turbo

### ISSUE THREAD

**Issue by NitinNi3** [cpacker/MemGPT#151]
logs:

acreate (backoff): caught error: You exceeded your current quota, please check your plan and billing details.

Here are some screenshots for Usage and api key :

![Screenshot (50)](https://github.com/cpacker/MemGPT/assets/110168215/603e8440-2fe0-413c-a46d-4fd71b47d4ef)

![Screenshot (51)](https://github.com/cpacker/MemGPT/assets/110168215/0b25c96b-84a5-403f-8a2c-541014ea4990)

do i need to create the paid account to use the gpt3.5-turbo model which is used by free from "chat.openai.com"?

**Comment by cpacker** [comment]
Yeah I'm pretty sure you need to click the "set up a paid account", then everything should start working. Unfortunately ChatGPT is separate from GPT API (paying for ChatGPT does not give you GPT API access).
