### ISSUE TITLE
How to calculate the evaluation matrics, CSIM?

### ISSUE THREAD

**Issue by HelloWorld4747** [cpacker/MemGPT#152]
Hello,
Just wondering how you calculate the CSIM-relative evaluation metrics for measuring the engagement of the conversation opener task since I failed to find out where it comes from. Or is this indicator also proposed by you? But, if this is the case, I also failed to find out the calculation process for this indicator.

Btw, this idea is pretty impressive. Really appreciate your hard work in sharing such a promising idea! Looking forward to your response soon! 

Cheers!

**Comment by vivi** [comment]
Consolidating this into #103 

But to calculate CSIM we compute it on the openai embedding of the two strings:
```python
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import openai
import numpy as np

def compute_cosine_similarity_tfidf(str1, str2):
    vectorizer = TfidfVectorizer()
    tfidf_matrix = vectorizer.fit_transform([str1, str2])
    return cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])[0][0]

def compute_cosine_similarity_openai(str1, str2):
    response1 = openai.Embedding.create(input=str1, model="text-embedding-ada-002")
    response2 = openai.Embedding.create(input=str2, model="text-embedding-ada-002")
    embedding1 = np.array(response1['data'][0]['embedding'])
    embedding2 = np.array(response2['data'][0]['embedding'])
    return cosine_similarity(embedding1.reshape(1, -1), embedding2.reshape(1, -1))[0][0]
```

**Comment by hy522** [comment]
Hi, could you provide an example of how to reproduce the evaluation results for DEEP MEMORY RETRIEVAL TASK and CONVERSATION OPENER TASK?(similar to paper_experiments/doc_qa_task). It's a little bit unclear what's used in the dataset to generate response/opener and what's the letta  agent setting etc.
