### ISSUE TITLE
Rate limit reached for gpt-4 in organization org-XXXX on tokens per min. Limit: 10000 / min. Please try again in 6ms. Visit https://platform.openai.com/account/rate-limits 

### ISSUE THREAD

**Issue by jgreenrise** [cpacker/MemGPT#155]
How to fix issues like above?

Steps to reproduce
1. Upload a book <pdf-book> to memgpt.
2. Ask a question "Prepare flash card from page 161 to page 172 and list all the flash cards from Document: <pdf-book>"

```
 % memgpt
? Which model would you like to use? gpt-4
? Which persona would you like MemGPT to use? memgpt_doc
     My name is MemGPT. I am an AI assistant designed to help human users with document analysis. I can
     use this space in my core memory to keep track of my current tasks and goals.  The answer to the
     human's question will usually be located somewhere in your archival memory, so keep paging through
     results until you find enough information to construct an answer. Do not respond to the human until
     you have arrived at an answer.
('memgpt_doc', None)
? Which user would you like to use? basic
     First name: Chad
? Would you like to preload anything into MemGPT's archival memory? Yes
? What would you like to load? A folder or file
? Please enter the folder or file (tab for autocomplete): IXXXXXXXX.EBooksWorld.ir.pdf
? Would you like to compute embeddings over these files to enable embeddings search? Yes
Computing embeddings over 1 files. This will cost ~$0.41. Continue? [y/n] y
Processing file chunks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1302/1302 [01:26<00:00, 15.08it/s]
Saving embeddings to /......./embeddings.json
Saving archival storage with preloaded files to /...../archival_index_from_files_2023-10-27_02_37_57_PM_PDT-0700/all_docs.jsonl
Saving faiss index /...../archival_index_from_files_2023-10-27_02_37_57_PM_PDT-0700/all_docs.index

⚙️ Saved config file to /...../.memgpt/configs/2023-10-27_02_39_32_PM_PDT-0700.json.
Running... [exit by typing '/exit', list available commands with '/help']
Initializing InMemoryStateManager with agent object
InMemoryStateManager.all_messages.len = 4
InMemoryStateManager.messages.len = 4
💭 Bootup sequence complete. Persona activated. Testing messaging functionality.
Hit enter to begin (will request first MemGPT message)
```

**Comment by tractorjuice** [comment]
Have you enabled DEBUG in the memgpt/utils.py file?

This may provide some clues. I have seen it get stuck in a loop and chew through API calls.

**Comment by cpacker** [comment]
@jgreenrise from what you've posted, I think the issue doesn't have to do with the book upload. The book upload will (if you're using OpenAI) use the embeddings API, which is why it's so cheap, and that has a split rate limit from gpt-4.

gpt-4 for most accounts has a rate-limit of 10k, which I'm seeing in your title. So the rate limit is probably occurring because GPT-4 is trying to answer your question by looking through the book uploads, and is going faster than 10k tokens per minute.

However, I think what's more likely (if you're seeing this error often) is that you may have someone else in your org also using GPT-4 at the same time. Since in our experience, MemGPT does not run fast enough to trigger the 10k token/min rate limit by itself very often, however if you have 2+ people using the same account/org with a shared 10k token/min limit, you'll easily hit the limit if both people are doing anything intensive.

Please let me know if you're still having issues with this and feel free to reopen if you feel like I didn't answer your question.

**Comment by ZeChArtiahSaher** [comment]
It's incredibly easy to reach the limit. The tool perhaps should provide some idea of the size of input or estimates if gpt 3.5 turbo 16k support is not really there. Also sometimes I dont what it does or Im used to summarizing git repos with gpt 3.5 turbo 16k but it's insanely easy to overrun the limit. This is definetely a design issue

**Comment by tractorjuice** [comment]
Check the agent.py. These lines, 

time.sleep(62)
await asyncio.sleep(62) 

should be 

time.sleep(delay)
await asyncio.sleep(delay) 

To actually backoff the calls to the api and use the 'delay' calculated.

**Comment by ZeChArtiahSaher** [comment]
I wouldn't consider that a solution because it's reactive and not preemptive. What's I'm saying is that if it's easy to run into limit with a utility that attemps to deal with large datasets by design. Then it probably should give some introspection or more fine grained control before the requests go flying and the bill goes up.

**Comment by cpacker** [comment]
> I wouldn't consider that a solution because it's reactive and not preemptive. What I'm saying is that if it's easy to run into limit with a utility that attemps to deal with large datasets by design. Then it probably should give some introspection or more fine grained control of the dataset or something before the requests go flying and the bill goes up. Plus delays are messed up too I agree, Current backoff logic doesn't seem to apply to rpm measurement

The way the code works is we don't preemptively start cutting/summarizing, instead we wait until the backend server sends a token limit error (failed request doesn't cost money on OpenAI AFAIK), and the MemGPT loop will start a summarization + data movement process when it sees this message propagated up the stack.

This is different than TPM / rate limit errors. For example if there's a token limit alert, that doesn't get retried, it immediately goes up the stack to the MemGPT token limit alert handler, but if there's a rate limit alert, that gets retried.

**Comment by cpacker** [comment]
> Yeah considering the target size of datasets are larger than typical context size it's kinda weird to not include gpt-3.5-turbo-16k. I tried to run this on repo files. Getting:
> 
> /usr/local/lib/python3.11/site-packages/memgpt/agent.py:842: RuntimeWarning: coroutine 'async_get_embedding_with_backoff' was never awaited return messages, None, True # force a heartbeat to allow agent to handle error RuntimeWarning: Enable tracemalloc to get the object allocation tracebac

You can run `gpt-3.5-turbo-16k` with `--model gpt-3.5-turbo-16k` afaik

**Comment by HelloWorld4747** [comment]
> Check the agent.py. These lines,
> 
> time.sleep(62) await asyncio.sleep(62)
> 
> should be
> 
> time.sleep(delay) await asyncio.sleep(delay)
> 
> To actually backoff the calls to the api and use the 'delay' calculated.

hello, I am experiencing the same issue.

My goal is to try to load the example .txt file to the archival memory, and ask memgpt some questions relative to those .txt files stored in the archival memory. 

Command how I ran: 
python3 main.py --archival_storage_files_compute_embeddings="memgpt/personas/examples/preload_archival/*.txt" --persona=memgpt_doc --human=basic

I am currently using a free version api key. And there aren't any usage history shown in my "Usage Page". Also, I had already stored all the .txt file into "preload_archival" folder. So, for my case, I prefer to try the time.sleep() method to extend the time-waiting as long as hitting the upper bound of the request limit per min. 

So, may I please ask you if where to add the time.sleep() function?

Appreciate all of your response!!
