### ISSUE TITLE
calling the/app/agents/id/messages interface never returns a result, suspected to be stuck in a dead loop

### ISSUE THREAD

**Issue by a67793581** [cpacker/MemGPT#1555]
**Describe the bug**
When using the OpenAI GPT-4o model with MemGPT, calling the/app/agents/id/messages interface never returns a result, suspected to be stuck in a dead loop.

**Please describe your setup**
- [ x ] How did you install memgpt?
  - git clone
- [ x ] Describe your setup
  -  OS MacOS
  - Terminal

**Screenshots**

**Additional context**

OpenAI API ：{"error":{"message":"Authentication Error, ExceededTokenBudget: Current spend for token: 21.393555839999998; Max Budget for Token: 20.0","type":"auth_error","param":"None","code":401}}

/api/agents/4519a4c1-43a7-489f-9a8a-f00babbd5164/messages
Authorization: Bearer 123456
Content-Type: application/json

{
  "message": "xxx",
  "role": "user",
  "stream": false,
  "timestamp": "2024-07-17T14:42:14+08:00"
}

**MemGPT Config**

[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = gpt-4o
model_endpoint = https://ai-gateway-test.bondee-inc.com/v1
model_endpoint_type = openai
model_wrapper = null
context_window = 8192

[embedding]
embedding_endpoint_type = openai
embedding_endpoint = https://ai-gateway-test.bondee-inc.com/v1
embedding_model = text-embedding-ada-002
embedding_dim = 1536
embedding_chunk_size = 300

[archival_storage]
type = postgres
path = /root/.memgpt/chroma
uri = postgresql+pg8000://memgpt:memgpt@localhost:5432/memgpt

[recall_storage]
type = postgres
path = /root/.memgpt
uri = postgresql+pg8000://memgpt:memgpt@localhost:5432/memgpt

[metadata_storage]
type = postgres
path = /root/.memgpt
uri = postgresql+pg8000://memgpt:memgpt@localhost:5432/memgpt

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`)
- [ ] The local LLM backend you are using (web UI? LM Studio?)
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

**Comment by sarahwooders** [comment]
#1562 might work - there are issues with smaller models not calling tools properly, which MemGPT needs to function properly

**Comment by a67793581** [comment]
> #1562 might work - there are issues with smaller models not calling tools properly, which MemGPT needs to function properly
If you look closely at this error, it refers to insufficient fees. What I mean by this is that the current error handling logic doesn't return error results in non-streaming mode, but instead falls into an endless loop

**Comment by a67793581** [comment]
> #1562 might work - there are issues with smaller models not calling tools properly, which MemGPT needs to function

If you look closely at this error, it refers to insufficient fees. What I mean by this is that the current error handling logic doesn't return error results in non-streaming mode, but instead falls into an endless loop
