### ISSUE TITLE
How to add a function(tool) to Memgpt?

### ISSUE THREAD

**Issue by samarthshrivas** [cpacker/MemGPT#1556]
How to add a function(tool) to Memgpt?

I am running Memgpt from source code.
i have tried to do as the docs said but i cant get it to work. 

i have tried these docs pages :
https://memgpt.readme.io/docs/functions
https://memgpt.readme.io/docs/adding-custom-tools-to-memgpt

Is there any step by step guide or some resource on how to add tools?

**Comment by sarahwooders** [comment]
Can you post the specific error / issue you're having, and step by step description of what you did?
