### ISSUE TITLE
memgpt server restapi call create agent failed due to postgresql error "sorry, too many clients already"

### ISSUE THREAD

**Issue by chatmydear2024** [cpacker/MemGPT#1578]
**Describe the bug**
when i make api call to memgpt server for creating agent ( after already creating many agents), restapi returned internal server error.
sample api call:
curl --request POST \
     --url http://memgpt.localhost/api/agents \
     --header 'accept: application/json' \
     --header 'content-type: application/json'

**Please describe your setup**
- [ ] How did you install memgpt?
  sudo compose up -d
- [ ] Describe your setup
  debian on a VM

**Screenshots**
![image](https://github.com/user-attachments/assets/43d67e3c-53b5-4e67-b696-a1a52165d3e7)

**Additional context**
rebooting the VM made the error go away but I expect the error to come back once accumulates enough db connections.
Appreciate any help!

**MemGPT Config**
i used config in server_config.yaml
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = memgpt-openai
model_endpoint = https://inference.memgpt.ai
model_endpoint_type = openai
model_wrapper = null
context_window = 8192

[embedding]
embedding_endpoint_type = hugging-face
embedding_endpoint = https://embeddings.memgpt.ai
embedding_model = BAAI/bge-large-en-v1.5
embedding_dim = 1024
embedding_chunk_size = 300

[archival_storage]
type = postgres
path = /root/.memgpt/chroma
uri = postgresql+pg8000://memgpt:memgpt@pgvector_db:5432/memgpt

[recall_storage]
type = postgres
path = /root/.memgpt
uri = postgresql+pg8000://memgpt:memgpt@pgvector_db:5432/memgpt

[metadata_storage]
type = postgres
path = /root/.memgpt
uri = postgresql+pg8000://memgpt:memgpt@pgvector_db:5432/memgpt

[client]
anon_clientid = 00000000-0000-0000-0000-000000000000

**Comment by sarahwooders** [comment]
This issue will hopeful by fixes with #1533 which involves refactoring the database code to avoid creating redundant sessions.
