### ISSUE TITLE
ModuleNotFoundError while running the AutoGen+MemGPT example notebook

### ISSUE THREAD

**Issue by ViperVille007** [cpacker/MemGPT#164]
**Getting the following error message :**

from memgpt.autogen.memgpt_agent import create_autogen_memgpt_agent, create_memgpt_autogen_agent_from_config
**ModuleNotFoundError:** No module named 'memgpt.autogen'; 'memgpt' is not a package

I've tried updating memgpt using pip install pymemgpt -U
AutoGen is working fine on its own (without the added Memgpt functionalities)

**Comment by cpacker** [comment]
Are you running this via a colab notebook or locally? Can you paste the command you're using to run the script?

**Comment by ViperVille007** [comment]
I'm running it locally indeed (on VS Code)
I've just copy-pasted the file in the path  memgpt/autogen/examples/agent_groupchat.py and added it to the local directory of autogen I'm working with.
.
Then I use the command: python agent_groupchat.py 
(Which leads to the error I mentioned)

**Comment by cpacker** [comment]
@vivi is the closeable with the new AutoGen?

**Comment by dashsabe** [comment]
import memgpt.autogen.memgpt_agent as memgpt_autogen
ModuleNotFoundError: No module named 'memgpt'

**Comment by chnl** [comment]
I'm running across this issue with the latest pip installs - pymemgpt    0.2.11  -  pyautogen   0.2.6
