### ISSUE TITLE
 in get_agent assert agent_name is not None and user_id is not None, AssertionError: Must provide either agent_id or agent_name

### ISSUE THREAD

**Issue by quantumalchemy** [cpacker/MemGPT#1662]
**Describe the bug**

  File "/MemGPT/memgpt/metadata.py", line 621, in get_agent
    assert agent_name is not None and user_id is not None, "Must provide either agent_id or agent_name"
                                      ^^^^^^^^^^^^^^^^^^^
AssertionError: Must provide either agent_id or agent_name

                                      ^^^^^^^^^^^^^^^^^^^
** But providing -->
memgpt run --agent thedude --persona agrippa --human phd_ace
works ok in .23

**Please describe your setup**
linux
git clone https://github.com/quantumalchemy/MemGPT.git
cd /MemGPT
pip install -e .

latest 
v0.3.24 

error on
memgpt run --agent thedude --persona agrippa --human phd_ace

**MemGPT Config**
[defaults]
preset = memgpt_chat
persona = sam_pov
human = basic

[model]
model = memgpt-openai
model_endpoint = https://inference.memgpt.ai
model_endpoint_type = openai
context_window = 8192

[embedding]
embedding_endpoint_type = hugging-face
embedding_endpoint = https://embeddings.memgpt.ai
embedding_model = BAAI/bge-large-en-v1.5
embedding_dim = 1024
embedding_chunk_size = 300

[archival_storage]
type = chroma
path = /root/.memgpt/chroma

[recall_storage]
type = sqlite
path = /root/.memgpt

[metadata_storage]
type = sqlite
path = /root/.memgpt

[version]
memgpt_version = 0.3.24

[client]
anon_clientid = user-01143f68-1bd2-49cd-b37b-340bbd8e7d09

**Comment by cpacker** [comment]
Hey @quantumalchemy - I think this may be due to using the latest commit on `main` (which is unstable) instead of the 0.3.24 checkpoint. Basically, we're doing a very big refactor for 0.4.0 which started post-0.3.24, so main is currently quite unstable and won't work until we add a 0.4.0 migration script.

Can you try doing the following to make sure you're on the commit for `0.3.24` in the source code, instead of being on the latest commit on main?
```
git checkout d6b124b
```

I tried it and it seems to work OK for me:
```
(pymemgpt-py3.10) (base) loaner@MacBook-Pro MemGPT-fresh % memgpt add persona --name agrippa --text "I'm AGRIPPA"
(pymemgpt-py3.10) (base) loaner@MacBook-Pro MemGPT-fresh % memgpt run --agent thedude --persona agrippa --human phd_ace

🧬 Creating new agent...
->  🤖 Using persona profile: 'agrippa'
->  🧑 Using human profile: 'phd_ace'
->  🛠️  8 tools: send_message, pause_heartbeats, conversation_search, conversation_search_date, archival_memory_insert, archival_memory_search, core_memory_append, core_memory_replace
🎉 Created new agent 'thedude' (id=05a7fc6c-cda9-440d-a54c-f950b3aa0316)

Hit enter to begin (will request first MemGPT message)


💭 Pleasant surprise, a new user has logged in. What should be my opening line? Perhaps a friendly 
greeting will set the right tone. I should be sure to use the user's name, Ace, to make the interaction 
more personalised.
🤖 Hello Ace, welcome! I'm Agrippa. How can I make your day brighter?

> Enter your message: /exit

Finished.
(pymemgpt-py3.10) (base) loaner@MacBook-Pro MemGPT-fresh % memgpt run --agent thedude --persona agrippa --human phd_ace

🔁 Using existing agent thedude

Hit enter to begin (will request first MemGPT message)


User interrupt occurred.
? Retry agent.step()? No
```

**Comment by quantumalchemy** [comment]
thanks works ok
