### ISSUE TITLE
Stuck on Thinking... (Local LLM WebUI - API Confirmed with curl)

### ISSUE THREAD

**Issue by mikes-bowden** [cpacker/MemGPT#168]
I finally was able to get MemGPT working with WubUI. Well, specifically, I'm running AGiXT, which also runs WebUI and uses their API.

I've run a curl on the API and got a response back. Works great.

Whenever I run MemGPT against the local API, it says Thinking... and nothing else.

nvtop shows that the CPU is being used on the GPU, so I know it's querying the API and LLM, but it sits there doing nothing. The longest I let it sit was 20 minutes, and nothing happened. It never failed or stopped. I've had to force cancel it every time, as it does nothing but "Thinking...".

What am I doing wrong?

**Comment by cpacker** [comment]
Could be a bunch of things, my guess is either (1) backend is broken for some reason / not running inference (2) lack of token limit is causing "infinite" output from the LLM. Can you paste a comment with some more details (your exact model, the command you used to launch the web server, the output from the web server terminal window, output from MemGPT run with `--debug`) on the discussion page? #67
