### ISSUE TITLE
Add support for pre-loading archival memory for MemGPT AutoGen agent

### ISSUE THREAD

**Issue by cpacker** [cpacker/MemGPT#170]
See: https://github.com/cpacker/MemGPT/discussions/65#discussioncomment-7409842

---

Maybe we implement this by allowing AutoGen agent to load from a save-state?

So workflow is:

1. Create agent with `memgpt`
2. Modify AutoGen hook to point at saved `memgpt` state file

This way we don't have to recreate all of main.py separately for AutoGen.

Alternate workflow is have the config schema mimic main.py arguments and do pre-load on init.

**Comment by sarahwooders** [comment]
The updated `AgentConfig` should point to a loaded `data_source` (which is loaded via a separate load function from `memgpt load ...`), so could that help fix this issue?

**Comment by khawajaJunaid** [comment]
> See: [#65 (reply in thread)](https://github.com/cpacker/MemGPT/discussions/65#discussioncomment-7409842)
> 
> Maybe we implement this by allowing AutoGen agent to load from a save-state?
> 
> So workflow is:
> 
> 1. Create agent with `memgpt`
> 2. Modify AutoGen hook to point at saved `memgpt` state file
> 
> This way we don't have to recreate all of main.py separately for AutoGen.
> 
> Alternate workflow is have the config schema mimic main.py arguments and do pre-load on init.

hi @cpacker , I am trying this by creating a data source supported agent and then have the agent loaded in the autogen creation, can you tell me how the code would look like for loading a memgpt agent, would really appreciate !

**Comment by khawajaJunaid** [comment]
hi @vivi, does this PR close #342 this issue ?
