### ISSUE TITLE
Still facing the AZURE embedding issue

### ISSUE THREAD

**Issue by shagu2021** [cpacker/MemGPT#176]
git log
commit 29119898c500e55b9e34e0f817c56c333a77b70b

i still see the auth error when i use AZURE and embeddings
AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API 
key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See 

following is my command 

![image](https://github.com/cpacker/MemGPT/assets/98937940/081b2022-dfb1-41a5-a09b-cee87cdb158f)

MemGPT > memgpt --archival-storage-files-compute-embeddings="*.pdf" --persona=memgpt_doc --human=basic --use-azure-openai

**Comment by s-spillias** [comment]
similar issue: I have defined the new 'AZURE_OPENAI_EMBEDDING_DEPLOYMENT' variable using our deployment name for embedgginds. But it looks like it is trying to reach this through the gpt4 endpoint, whereas, we have a different endpoint for embeddings. 

The specific error is: 
**InvalidRequestError: The API deployment for this resource does not exist. If you created the deployment within the last
5 minutes, please wait a moment and try again.**

**Comment by cpacker** [comment]
@vivi I think this is because of a typo here: https://github.com/cpacker/MemGPT/blob/main/memgpt/openai_tools.py#L150

Patching now, will link the PR.

**Comment by vivi** [comment]
Define `AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT`. (EMBEDDING**S** -- see README). 

The patch we pushed makes everything consistent (to use `AZURE_OPENAI_EMBEDDINGS_DEPLOYMENT`) now.
