### ISSUE TITLE
Getting error when calling archival_memory_insert

### ISSUE THREAD

**Issue by distributev** [cpacker/MemGPT#1784]
For query tasks I have MemGPT configured and working properly using an API key with https://openrouter.ai/

In this configuration, each time it tries to call archival_memory_insert, MemGPT fails saying the openai API key is not valid.

My questions are:

1. Why an API key (OpenAI key or any other api key) would be required when saving some locally available data (from the context of the conversation) to a local database?
2. Considering that MemGPT already works (for questions->answers) with the API key from https://openrouter.ai/ why, only for saving calling archival_memory_insert, it tries to use an API key from another vendor (OpenAI) which seems not be related with the main system setup (via https://openrouter.ai/)

![memgpt-api-key-error](https://github.com/user-attachments/assets/e1d1d473-06ec-4f07-aa31-b50dffcf3a32)

**Comment by Sapessii** [comment]
Because it's calling openai api to get embeddings for the text to save

**Comment by distributev** [comment]
Can't this be done locally without any network call?

OpenAI embeddings are closed source under a paywall only? This means all other Ollama openai API compatible local providers still need an OpenAI key and pay OpenAI when using local models (just for embeddings)?

**Comment by sarahwooders** [comment]
If you want to run embedings locally, we recommend using Ollama https://docs.letta.com/models/ollama

**Comment by distributev** [comment]
Thank you for all your help.

Just by selecting embedding provider: local + pip install `pymemgpt[local]` did the trick with openrouter.ai

I do not use Ollama.
