### ISSUE TITLE
py files dropped to .memgpt/functions seems not to be picked up

### ISSUE THREAD

**Issue by distributev** [cpacker/MemGPT#1793]
Hello,

The existing documentation

https://memgpt.readme.io/docs/adding-custom-tools-to-memgpt

explains how to write "tools" functions but not how (and where) to deploy them.

There is an existing issue which is related and in which other people had similar difficulties

https://github.com/cpacker/MemGPT/issues/1543

From the MemGPT code I understood that the .memgpt/functions should be that location but I dropped few python 
files there and the python files are in that folder are not picked.

What I ended doing was to add my functions / custom tools in the existing MemGPT code-base in the file extras.py but this is less than Ideal because I need to to full _pip install MemGPT_ for every small thing I modify in extras.py (and sometimes even this does not suffice I need to do pip purge cache and sometimes I even had to remove the venv and start over just to see my new functions defined in extras.py picked up)

By reading the MemGPT code I found  .memgpt/functions referenced to load that location but that code even if it is in MemGPT codebase it is actually not used by MemGPT (dead code!).

I would also suggest (but this only after the existing .memgpt/functions functionality works) to have each agent load its own tools/functions from its own location (customizable) and not from a common shared location like .memgpt/functions is. This is to have each Agent being self contained.

**Comment by sarahwooders** [comment]
I'd recommend looking at the latest docs at https://docs.letta.com/agents/tools -`~/.memgpt/functions` was deprecated a while ago, but thanks for catching the dead code.

**Comment by distributev** [comment]
OK so I define 

def query_birthday_db(self, name: str):

in a new script

my_birthday.py

How will Letta load and know about the existence of my_birthday.py?

**Comment by sarahwooders** [comment]
You should be able to do: 

```
from my_birthday import query_birthday_db
from letta import create_client

client = create_client()
letta_tool = client.create_tool(query_birthday_db)

# check if tool is added 
print(client.list_tools())
```

The tools are persisted to sqlite, so you can access them across sessions.

**Comment by distributev** [comment]
You want to say that the full source for of the function query_birthday_db is persisted in sqllite when this is called letta_tool = client.create_tool(query_birthday_db) and then, at usage/runtime, the script my_birthday.py can be deleted and the tool will continue to work because it's function code is loaded from the the database?

**Comment by sarahwooders** [comment]
Yes, once your function is properly persisted in the DB as a `Tool` object, then that's what will be referenced, so you can delete `my_birthday.py`.

**Comment by distributev** [comment]
OK, this is good but it should be documented. People would not normally expect that python code is saved and used from a database.
