### ISSUE TITLE
FileNotFoundError: No file found for key sam_pov, path=memgpt\personas\examples\sam_pov.txt

### ISSUE THREAD

**Issue by Phiapsi** [cpacker/MemGPT#180]
Hey everyone,

i tried to run Dolphin2.1 Mistral 7B q8_0 gguf with LMStdio and memgpt.

Sadly it brakes while starting:

>C:\Windows\System32>memgpt --model Dolphin21MistralWrapper --no_verify
⚙️ Using legacy command line arguments.
None Dolphin21MistralWrapper ('sam_pov', 'memgpt\\personas\\examples')
Running... [exit by typing '/exit', list available commands with '/help']
⛔️ Warning - you are running MemGPT with Dolphin21MistralWrapper, which is not officially supported (yet). Expect bugs!
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\bauer\AppData\Local\Programs\Python\Python311\Lib\site-packages\memgpt\main.py:148 in   │
│ run                                                                                              │
│                                                                                                  │
│   145 │   ),  # TODO: just pass in?                                                              │
│   146 ):                                                                                         │
│   147 │   loop = asyncio.get_event_loop()                                                        │
│ > 148 │   loop.run_until_complete(                                                               │
│   149 │   │   main(                                                                              │
│   150 │   │   │   persona,                                                                       │
│   151 │   │   │   human,                                                                         │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │               archival_storage_faiss_path = ''                                               │ │
│ │                    archival_storage_files = ''                                               │ │
│ │ archival_storage_files_compute_embeddings = ''                                               │ │
│ │                    archival_storage_sqldb = ''                                               │ │
│ │                                     debug = False                                            │ │
│ │                                     first = False                                            │ │
│ │                                     human = None                                             │ │
│ │                                      loop = <ProactorEventLoop running=False closed=False    │ │
│ │                                             debug=False>                                     │ │
│ │                                     model = 'Dolphin21MistralWrapper'                        │ │
│ │                                 no_verify = True                                             │ │
│ │                                   persona = None                                             │ │
│ │                          use_azure_openai = False                                            │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\bauer\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py:653 in         │
│ run_until_complete                                                                               │
│                                                                                                  │
│    650 │   │   if not future.done():                                                             │
│    651 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')             │
│    652 │   │                                                                                     │
│ >  653 │   │   return future.result()                                                            │
│    654 │                                                                                         │
│    655 │   def stop(self):                                                                       │
│    656 │   │   """Stop running the event loop.                                                   │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   future = <Task finished name='Task-1' coro=<main() done, defined at                        │ │
│ │            C:\Users\bauer\AppData\Local\Programs\Python\Python311\Lib\site-packages\memgpt\… │ │
│ │            exception=FileNotFoundError('No file found for key sam_pov,                       │ │
│ │            path=memgpt\\personas\\examples\\sam_pov.txt')>                                   │ │
│ │ new_task = True                                                                              │ │
│ │     self = <ProactorEventLoop running=False closed=False debug=False>                        │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\bauer\AppData\Local\Programs\Python\Python311\Lib\site-packages\memgpt\main.py:309 in   │
│ main                                                                                             │
│                                                                                                  │
│   306 │   memgpt_agent = presets.use_preset(                                                     │
│   307 │   │   presets.DEFAULT,                                                                   │
│   308 │   │   cfg.model,                                                                         │
│ > 309 │   │   personas.get_persona_text(*chosen_persona),                                        │
│   310 │   │   humans.get_human_text(*chosen_human),                                              │
│   311 │   │   memgpt.interface,                                                                  │
│   312 │   │   persistence_manager,                                                               │
│                                                                                                  │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │               archival_storage_faiss_path = ''                                               │ │
│ │                    archival_storage_files = ''                                               │ │
│ │ archival_storage_files_compute_embeddings = ''                                               │ │
│ │                    archival_storage_sqldb = ''                                               │ │
│ │                                azure_vars = []                                               │ │
│ │                                       cfg = <memgpt.config.Config object at                  │ │
│ │                                             0x000001A9A70B6B90>                              │ │
│ │                              chosen_human = ('cs_phd', 'memgpt\\humans\\examples')           │ │
│ │                            chosen_persona = ('sam_pov', 'memgpt\\personas\\examples')        │ │
│ │                                     debug = False                                            │ │
│ │                                     first = False                                            │ │
│ │                                     human = None                                             │ │
│ │                             human_persona = ('cs_phd', 'memgpt\\humans\\examples')           │ │
│ │                            memgpt_persona = ('sam_pov', 'memgpt\\personas\\examples')        │ │
│ │                                     model = 'Dolphin21MistralWrapper'                        │ │
│ │                                 no_verify = True                                             │ │
│ │                       persistence_manager = <memgpt.persistence_manager.InMemoryStateManager │ │
│ │                                             object at 0x000001A9A70B4B10>                    │ │
│ │                                   persona = None                                             │ │
│ │                          use_azure_openai = False                                            │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\Users\bauer\AppData\Local\Programs\Python\Python311\Lib\site-packages\memgpt\personas\persona │
│ s.py:17 in get_persona_text                                                                      │
│                                                                                                  │
│   14 │   │   with open(file_path, "r") as file:                                                  │
│   15 │   │   │   return file.read().strip()                                                      │
│   16 │   else:                                                                                   │
│ > 17 │   │   raise FileNotFoundError(f"No file found for key {key}, path={file_path}")           │
│   18                                                                                             │
│                                                                                                  │
│ ┌─────────────────────── locals ────────────────────────┐                                        │
│ │       dir = 'memgpt\\personas\\examples'              │                                        │
│ │ file_path = 'memgpt\\personas\\examples\\sam_pov.txt' │                                        │
│ │  filename = 'sam_pov.txt'                             │                                        │
│ │       key = 'sam_pov'                                 │                                        │
│ └───────────────────────────────────────────────────────┘                                        │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: No file found for key sam_pov, path=memgpt\personas\examples\sam_pov.txt

I am only a hobby python programmer and i dont find the problem myself. Same Problem like #70 

No changes, i used pip install memgpt. I also tried to give a specific Persona same error

**Comment by vivi** [comment]
Should be fixed by https://github.com/cpacker/MemGPT/commit/ba83873922af265a20226eeea7c5b05b43744d66.
