### ISSUE TITLE
Security issue when create agent is called from different user simultaneously

### ISSUE THREAD

**Issue by Sapessii** [cpacker/MemGPT#1825]
**Describe the bug**

Hi, when the create agent endpoint is called simultaneously from different users, the user_id is always stick with the first user, hence resulting in multiple users that can access to the chat of others.

I think it's related with the middleware setting the set_current_user function is called.

**Comment by cpacker** [comment]
Thanks for bringing this up @Sapessii ! Just opened a fix in PR #1834 - once it passes test will get it merged in ASAP.

**Comment by Sapessii** [comment]
Awesome thank you so much!

**Comment by Sapessii** [comment]
Hi! @cpacker, I just tried the fix but is not getting the header correctly, it's working when using

`user_id: str = Header(..., alias="user_id")`

**Comment by Sapessii** [comment]
@cpacker sure no problem, I just took it from an older version of memgpt :) thanks to you!

**Comment by Sapessii** [comment]
@cpacker sure no problem :) thanks to you!

**Comment by cpacker** [comment]
@Sapessii can you check my comments in https://github.com/cpacker/MemGPT/pull/1843?

I think this seems to be working (at least in that PR). Will merge it in shortly.

**Comment by Sapessii** [comment]
@cpacker working perfectly! thank you so much
