### ISSUE TITLE
json schema doesn't update after tool editing via ADE

### ISSUE THREAD

**Issue by ketchalegend** [cpacker/MemGPT#1874]
**Describe the bug**

When editing a tool via the ADE, the changes are saved, but the json_schema doesn't reflect the updates. After modifying the tool and making a REST API call to verify the state, I noticed that the json_schema remained unchanged.

For example, I initially created a basic roll_d20 tool. After editing it to add a new function, the json_schema still showed the original version without the new changes.

<img width="651" alt="Bildschirmfoto 2024-10-12 um 14 05 46" src="https://github.com/user-attachments/assets/fb6bb7f6-0bee-44b8-aaa8-c3403860fbb2">

**Comment by mattzh72** [comment]
I see - I'll add code to autogenerate the schema if the `source_code` is updated in the Tool.
