### ISSUE TITLE
In-memory or persistant?

### ISSUE THREAD

**Issue by Numeri** [cpacker/MemGPT#19]
Is this currently just in-memory (and thus reset when you end the program) or can it save the updated persona and archival memory files to the disk?

My 10 minutes of experimenting suggest that it's just in-memory – I tried `\save` and `\memorywarning`, but neither of those actually write the updated archival memory to disk

**Comment by somykoron-it** [comment]
Same happened in my case

**Comment by cpacker** [comment]
Thanks for catching this bug! It should be fixed in the latest patch (#27), but please let us know if it's still not working for you (you can reopen the issue).
