### ISSUE TITLE
Persona and Human not working

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [cpacker/MemGPT#190]
I placed text files in the correct directory (under .memgpt/human & .memgpt/persona in my own windows user account) the files were detected and loaded properly as I could see the information on first time load of MemGPT. I can also see the details with /memory however they do not appear to have an effect. The system randomly gives itself a name each time and claims it does not know my name. I was sure to follow the examples and format the .txt files the right way. 

I also tried this with the default examples (sam & sam_pov) and got the same results. It knows the information but does not apply it.

I have tried to troubleshoot and even started completely fresh (deleted all saved states and config files) and the experience is the same.

![image](https://github.com/cpacker/MemGPT/assets/123831682/7767d6da-fef3-46e9-9e91-e4718c98d64d)

**Comment by web3wes** [comment]
<img width="1108" alt="Screenshot 2023-10-29 at 11 06 34 PM" src="https://github.com/cpacker/MemGPT/assets/97464975/78c3add6-df78-4a52-82d7-b18ea4422bdb">

**Comment by cpacker** [comment]
From discord:

> Since the discussion about the persona and human elements not working I'm writing to follow up and let you know that it appears to have been a 'wrapper' issue. First with no wrapper (default gets applied) the dysfunctionality exists. Second with the wrong wrapper applied the issue exists but some functionality (recognition of persona and human) is present but still broken. With the proper wrapper, in this case 'airboros' everything works perfectly.
