### ISSUE TITLE
How to invoke multiple humans with groupchat 

### ISSUE THREAD

**Issue by deerleo** [cpacker/MemGPT#191]
Hello, 
I would like to develop a groupchat bot, which means MemGPT will have to deal with multiple users chatting at the same time. I made an API wrapper, but only can load single human at once. how to load multiple humans or make it recognized it's in a groupchat context, so that it won't keep calling every one the same name.  It would be better if MemGPT can remember everyone's name and hobby at the groupchat session.

**Comment by vivi** [comment]
Could you add the code you're trying to run? Thanks!

**Comment by danx0r** [comment]
Is autoGPT integration a potential solution?
https://github.com/cpacker/MemGPT/discussions/65

**Comment by cpacker** [comment]
https://memgpt.readthedocs.io/en/latest/autogen/
