### ISSUE TITLE
Removed LM Studio Support? [KeyError: 'choices']

### ISSUE THREAD

**Issue by ProjCRys** [cpacker/MemGPT#194]
It was just working fine yesterday and I made sure to start the server from my LM Studio. 

Here's the context:
set OPENAI_API_BASE "http://localhost:1234/v1"
set BACKEND_TYPE "lmstudio"
python MemGPT/main.py

⚙️ Found saved config file.
? Use most recent config file 'C:\Users\ADMIN\.memgpt\configs\2023-10-29_09_37_06_PM_PDT-0700.json'? Yes
Running... [exit by typing '/exit', list available commands with '/help']
💭 Bootup sequence complete. Persona activated. Testing messaging functionality.
Hit enter to begin (will request first MemGPT message)
[A[K
Warning: no wrapper specified for local LLM, using the default wrapper

MaxRetryError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/v1/completions
(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E40BF1E4A0>: Failed to establish a
new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

[Lone lines of code]

During handling of the above exception, another exception occurred:

[Lone lines of code]

ConnectionError: HTTPConnectionPool(host='localhost', port=1234): Max retries exceeded with url: /v1/v1/completions
(Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001E40BF1E4A0>: Failed to establish a
new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

[Lone lines of code]

ValueError: Was unable to connect to host http://localhost:1234/v1

**Comment by ProjCRys** [comment]
Wait I think the problem lies in LM Studio as I check my program that uses LM Studio Server Interference

**Comment by ProjCRys** [comment]
Here's the logs of LM Studio:
[2023-10-30 12:59:35.066] [ERROR] Unexpected endpoint or method. (POST /v1/v1/completions). Returning 200 anyway.
[2023-10-30 12:59:43.348] [ERROR] Unexpected endpoint or method. (POST /v1/v1/completions). Returning 200 anyway.
[2023-10-30 12:59:58.554] [ERROR] Unexpected endpoint or method. (POST /v1/v1/completions). Returning 200 anyway.
[2023-10-30 13:00:44.066] [ERROR] Unexpected endpoint or method. (POST /v1/v1/completions). Returning 200 anyway.

**Comment by cpacker** [comment]
The endpoint address is incorrect, notice how you have two `/v1`s (`/v1/v1`)

Should be no `/v1` in the base URL:
```
set OPENAI_API_BASE "http://localhost:1234"
```

Feel free to reopen if this doesn't work.

**Comment by ProjCRys** [comment]
It didn't work...


set OPENAI_API_BASE "http://localhost:1234"
set BACKEND_TYPE "lmstudio"

KeyError: 'choices'

**Comment by cpacker** [comment]
Something seems to be going wrong with the environment variables - if you're getting this error:

"ValueError: Was unable to connect to host http://localhost:1234/v1"

It means that OPENAI_API_BASE is still being detected as `http://localhost:1234/v1`, not `http://localhost:1234` (even though you set it - see the code [here](https://github.com/cpacker/MemGPT/blob/main/memgpt/local_llm/chat_completion_proxy.py#L52)) - I'm not sure why that is.

Can you try on a fresh terminal window? Or maybe try restarting (https://github.com/cpacker/MemGPT/issues/179#issuecomment-1784209759)? Thanks for your patience.

**Comment by ProjCRys** [comment]
I somehow fixed it by setting it inside a virtual env:


Here's the batch file I created to run it.
@echo off
setlocal

:: Set the path to your Python 3.10.0 installation
set PYTHON_PATH=..\path\to\python.exe

:: Set the path to the directory where you want to create the virtual environment
set VENV_DIR=..\path\to\MemGPT_Setup\venv

:: Set the path to the requirements file
set REQUIREMENTS_FILE=..\path\to\MemGPT\requirements.txt

:: Set the environment variables
set OPENAI_API_BASE=http://localhost:1234
set BACKEND_TYPE=lmstudio

:: Create and activate the virtual environment
%PYTHON_PATH% -m venv %VENV_DIR%
call %VENV_DIR%\Scripts\activate

:: Install the required packages using pip
pip install -r %REQUIREMENTS_FILE%

:: Run your Python script with the environment variables set
set PYTHONPATH=%PYTHONPATH%;%VENV_DIR%\Lib\site-packages
python MemGPT/main.py

:: Deactivate the virtual environment
deactivate

endlocal

**Comment by cpacker** [comment]
Great, thank you for posting your solution! Glad it's working.
