### ISSUE TITLE
Groq models are not being loaded

### ISSUE THREAD

**Issue by davidsells** [cpacker/MemGPT#1948]
# Groq models are not being loaded
## System Information
- **MacOS Version**: 14.5
- **Letta Image**: lettaai/letta:0.5.1

## Steps Taken
1. Clone Repo
2. Cleared all LLM keys from shell ( unset GROQ_API_KEY )
3. Created a new GROQ_API_KEY from the Groq website
4. Create .env with GROQ_API_KEY="..." 
5. Executed docker compose up
6. Visited http://localhost:8083/agents
7. Clicked on create agent
8. Model list is empty

## Additional Information
If I set ANTHROPIC_API_KEY or OPENAI_API_KEY, the associated models would show up in the model list

**Comment by mattzh72** [comment]
It should show up now!
