### ISSUE TITLE
Azure embeddeding issue

### ISSUE THREAD

**Issue by shagu2021** [cpacker/MemGPT#196]
following are the list of env variable 
![image](https://github.com/cpacker/MemGPT/assets/98937940/4d80fcc7-0fef-4a62-85a8-251b4f3c0c96)
this is the my current git version 
commit b037c27e3d1783617e7d4afd418a93d8c0a66ac4

and i still getting the following problem
AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API 
key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See 
https://platform.openai.com/account/api-keys for details.

**Comment by vivi** [comment]
Did you export the variables in your shell?

e.g., does running `echo $AZURE_OPENAI_ENDPOINT` etc. output what you expect?

**Comment by vivi** [comment]
What is the output of `pip show pymemgpt`?

**Comment by shagu2021** [comment]
Here is the output of pip show pymemgpt

***@***.***

**Comment by shagu2021** [comment]
here is the output 
of pip show pymemgpt
![image](https://github.com/cpacker/MemGPT/assets/98937940/f74a0e62-5d48-4926-8c90-7d88f29f4f1e)

**Comment by vivi** [comment]
that is an outdated version, please update it and try again: `pip install pymemgpt -U`

**Comment by shagu2021** [comment]
updated the pymemgpt

![image](https://github.com/cpacker/MemGPT/assets/98937940/cb823df1-c23f-41b9-8ca9-bff82db45c09)

but after updating i am getting some new error 

![image](https://github.com/cpacker/MemGPT/assets/98937940/56dce1ca-de9d-43a3-8f1e-df4485d81e5e)

my tmp folder permission status
ls -ld /tmp
drwxrwxrwt. 206 root root 36K Oct 30 09:47 /tmp

**Comment by vivi** [comment]
Try to delete your memgpt conda environment and reinstall pymemgpt again? Seems like it thinks that something is cached when it's not.

**Comment by shagu2021** [comment]
Thanks vivi, after reinstalling everything i can able to create embeddings now , thanks a lot

**Comment by vivi** [comment]
No problem, let us know if you have any other issues.
