### ISSUE TITLE
the length of prompt will be too longer

### ISSUE THREAD

**Issue by jiezhangGt** [cpacker/MemGPT#198]
Hello, by reading the code, I found that the prompt is formed by concatenating and combining the `agent.messages` list. I am curious, as the conversation progresses, the `agent.messages` list becomes larger and the prompt becomes longer. What happens when it exceeds the maximum length that the model can handle? How can we ensure that memGPT remains a permanent chatbot?

**Comment by vivi** [comment]
It will summarize messages / clip the messages / write things out to archival memory over the course of the conversation.

https://github.com/cpacker/MemGPT/blob/main/memgpt/agent.py#L609
