### ISSUE TITLE
Unable to function on the first message using text-generation-UI

### ISSUE THREAD

**Issue by jackfood** [cpacker/MemGPT#199]
What's wrong? I am using text-generation-UI and have the following setting
![image](https://github.com/cpacker/MemGPT/assets/11504716/986bccde-6e90-4628-b9c6-6ea83ac55b9c)
![image](https://github.com/cpacker/MemGPT/assets/11504716/8f177bf4-1950-4b99-8472-d3d5c078748d)

but error:
![image](https://github.com/cpacker/MemGPT/assets/11504716/a67cfa46-2dcd-458a-8cb4-b160b641c517)

![image](https://github.com/cpacker/MemGPT/assets/11504716/51076847-fa59-493a-9d54-a8d103170eb0)

![image](https://github.com/cpacker/MemGPT/assets/11504716/d778c654-462b-4237-8a1c-18f443244390)

**Comment by ProjCRys** [comment]
have you tried

set OPENAI_API_BASE=http://127.0.0.1:5000
set BACKEND_TYPE=webui

also uncheck openai checkbox 

If this doesnt work try creating a bat file that creates a virtual environment:


Here's what I wrote for mine:
@echo off
setlocal

:: Set the path to your Python 3.10.0 installation
set PYTHON_PATH=path\to\python.exe

:: Set the path to the directory where you want to create the virtual environment
set VENV_DIR=path\to\place\venv

:: Set the path to the requirements file
set REQUIREMENTS_FILE=path\to\MemGPT\requirements.txt

:: Set the environment variables
set OPENAI_API_BASE=http://127.0.0.1:5000
set BACKEND_TYPE=webui

:: Create and activate the virtual environment
%PYTHON_PATH% -m venv %VENV_DIR%
call %VENV_DIR%\Scripts\activate

:: Install the required packages using pip
pip install -r %REQUIREMENTS_FILE%

:: Run your Python script with the environment variables set
set PYTHONPATH=%PYTHONPATH%;%VENV_DIR%\Lib\site-packages
python MemGPT/main.py

:: Deactivate the virtual environment
deactivate

endlocal

**Comment by cpacker** [comment]
Yeah don't use any extensions. If you're having trouble try reinstalling web UI from scratch, and make sure not to add any extensions etc.

**Comment by danx0r** [comment]
This is likely fixed by https://github.com/cpacker/MemGPT/pull/300 which is in main now
