### ISSUE TITLE
Archive count not in first message?

### ISSUE THREAD

**Issue by tractorjuice** [cpacker/MemGPT#201]
Does the initialize_message_sequence call in agent.py (line 190) mean that on initialisation, it does not pass the recall or archive memory, therefore the first call to the LLM states that the Archive and Recall memories are 0?

I'm seeing this in my port of MemGPT to Streamlit, but it could just be the way I've done it.

I'm only seeing the Archive/Recall counts update, once MemGPT has to make the first save to any memory.

**Comment by sarahwooders** [comment]
Archival/recall memory are saved separately in `persistence_manager` (https://github.com/cpacker/MemGPT/blob/main/memgpt/agent.py#L213C36-L213C55), which will be pre-filled if you're starting from a saved agent (if they had saved anything to archival/recall)

**Comment by tractorjuice** [comment]
I think my point is that because the initial message is generated (190) before it is saved by the persistence_manager, therefore the first message states recall and archive memories are 0?
