### ISSUE TITLE
/load causes crash

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [cpacker/MemGPT#205]
I hope this isn't a redundant post, I searched and didn't see this reported..

When attempting to use /load, memgpt crashes instantly.

![image](https://github.com/cpacker/MemGPT/assets/123831682/5ebc4d3d-f0df-4fa9-b0d8-8baed2888582)

**Comment by sarahwooders** [comment]
We will deprecate the `\load` command soon. If can run the updated cli if you install from source, and run `memgpt run`, `\save`, and then `memgpt run --agent <AGENT_NAME>` which will automatically load the previous agent state.

**Comment by ProjCRys** [comment]
would this also fix the issue on this error?

⚙️ Found saved config file.
? Use most recent config file 'C:\Users\ADMIN\.memgpt\configs\2023-10-30_08_25_34_AM_PDT-0700.json'? Yes
Running... [exit by typing '/exit', list available commands with '/help']
💭 Bootup sequence complete. Persona activated. Testing messaging functionality.
? Load in saved agent 'C:\Users\ADMIN\.memgpt\saved_state\2023-10-30_09_07_01_AM_PDT-0700.json'? Yes
Loaded checkpoint C:\Users\ADMIN\.memgpt\saved_state\2023-10-30_09_07_01_AM_PDT-0700.json
/load warning: loading persistence manager from C:\Users\ADMIN\.memgpt\saved_state\2023-10-30_09_07_01_AM_PDT-0700.persistence.pickle failed with: Ran out of input

**Comment by ProjCRys** [comment]
> We will deprecate the `\load` command soon. If can run the updated cli if you install from source, and run `memgpt run`, `\save`, and then `memgpt run --agent <AGENT_NAME>` which will automatically load the previous agent state.

would this also fix the issue on this error?

⚙️ Found saved config file.
? Use most recent config file 'C:\Users\ADMIN.memgpt\configs\2023-10-30_08_25_34_AM_PDT-0700.json'? Yes
Running... [exit by typing '/exit', list available commands with '/help']
💭 Bootup sequence complete. Persona activated. Testing messaging functionality.
? Load in saved agent 'C:\Users\ADMIN.memgpt\saved_state\2023-10-30_09_07_01_AM_PDT-0700.json'? Yes
Loaded checkpoint C:\Users\ADMIN.memgpt\saved_state\2023-10-30_09_07_01_AM_PDT-0700.json
/load warning: loading persistence manager from C:\Users\ADMIN.memgpt\saved_state\2023-10-30_09_07_01_AM_PDT-0700.persistence.pickle failed with: Ran out of input

**Comment by web3wes** [comment]
I have adopted this command and will be shifting to be used primarily as a rollback or failover memory to enable reverting to a previous state with a model.

**Comment by cpacker** [comment]
This should be fixed by #237, please reopen if this is still an issue @TheOnlyWiseJEDI
