### ISSUE TITLE
some TODOs on MemGPT CLI refactor

### ISSUE THREAD

**Issue by vivi** [cpacker/MemGPT#206]
- [x] Add prettytable to requirements.txt
- [ ] https://github.com/cpacker/MemGPT/blob/main/memgpt/agent.py#L365 -- use os.path.join (for windows compatibility)
- [ ] https://github.com/cpacker/MemGPT/blob/main/memgpt/embeddings.py#L10 -- Can we make this match https://github.com/cpacker/MemGPT/blob/main/memgpt/openai_tools.py#L150 more closely? For Azure, you don't necessarily need a deployment name. If you have a certain type of setup, you can just pass in azure_api_key and set the engine to text-embedding-ada-002. That's why we have this case: https://github.com/cpacker/MemGPT/blob/main/memgpt/openai_tools.py#L215 (only complain if a deployment is set for one of them)

**Comment by sarahwooders** [comment]
For the third point, the config code allows you to not have the deployment name set if the API key is set https://github.com/cpacker/MemGPT/blob/main/memgpt/cli/cli_config.py#L46, so the fields might be null. Does that logic match?

**Comment by vivi** [comment]
> For the third point, the config code allows you to not have the deployment name set if the API key is set https://github.com/cpacker/MemGPT/blob/main/memgpt/cli/cli_config.py#L46, so the fields might be null. Does that logic match?
Oh hmm I didn't realize this was llama_index's wrapper around OpenAI's embeddings. Could you test with the credentials I gave you (where there's no deployment name and just an API key) to see if what you currently have works? 

> And for the second point, I just copied the existing load code -- is there a more updated version, or is there an issue with the current code as well?
Just looked and yeah that's an issue in the existing [load](https://github.com/cpacker/MemGPT/blob/main/memgpt/main.py#L100) code too, we should fix both

**Comment by vivi** [comment]
also is there a reason why `.load()` isn't called here? https://github.com/cpacker/MemGPT/blob/main/memgpt/cli/cli.py#L64

**Comment by sarahwooders** [comment]
Thats for the case where the user put in `-y`, so it skips prompting the user and creates a config with all default values. Versus `.load()` loads from an existing config file.
