### ISSUE TITLE
The new version now needs to install transformers and torch, but I run it on a computer that will never use a local llm

### ISSUE THREAD

**Issue by oderwat** [cpacker/MemGPT#217]
I just use memgpt with a local llm that runs on another system in my network. Why do I suddenly need to install torch and transformers and have data downloaded from huggingface? The nice thing about memgpt was that it could be made 100% private and did not need any connection to the internet to work.

**Comment by sarahwooders** [comment]
Hi @oderwat - we recently migrated to using a VectorIndex for local archival memory, which needs a way to compute embeddings. For users who don't want to use the OpenAI or Azure, we default to a local HuggingFace model to compute embeddings. 

Do you have an embedding endpoint for your local LLM? If so, we could use that to compute embeddings. An alternative is to also make it possible to remove vector search as a requirement for archival memory (@cpacker thoughts?).

**Comment by oderwat** [comment]
I see. Currently, there is no endpoint for embeddings (I believe) as I just use textgen-webui. Personally I have two use cases for MemGPT: Fun + Work. Fun = Chatting with crazy agents (my dog, the devil, my evil self as replica), Work: Talking about a large amount of source code (Go) from many different projects with the ultimate goal to make it easy to write documentation, readme's, analysing bugs, and such stuff. Less about creating code itself (as for now).

I work on an intel iMac and run all my AI models on WSL2 Win11 with a RTX 3090 and 128 GB CPU RAM. I do not care at all about GPT-4 API / AZURE or anything else outside my control. This is my developer computer too, so I do not want to have stuff installed that is sending code or private information anywhere.

For me, it would obviously the best if all the demanding computational parts would be behind some API that I can run on different servers, while I love to use the terminal for connecting to MemGPT (no webui needed). I do not even want "config files". But I understand that people request that :)

**Comment by cpacker** [comment]
@sarahwooders another alternative is we can default to archival memory that does not use embedding-based search, eg it just uses string matching.

Maybe this should be an option if you run `memgpt configure` with local LLM parameters? Basically CLI will tell you "we noticed you're running local, do you want to download a (1) huggingface model to do local embeddings, (2) use openai to compute embeddings, (3) don't use embeddings at all, and just use archival search via text search.

**Comment by oderwat** [comment]
@cpacker Maybe you put it behind a unifying API, so it can be run on another server and this service can choose how it is implemented?

**Comment by sarahwooders** [comment]
Maybe we have have a `memgpt configure` option for embeddings: 
```
Do you want to enable embedding based search for archival memory? [Y/n]
What provider do you want to use for embeddings? 
> Open AI 
> Azure 
> Custom endpoint 
> Local model 
``` 
So then if you only want text based search, you select [n] for the first question.

**Comment by cpacker** [comment]
@sarahwooders this looks good to me!

Then @oderwat, if you want to enable embeddings but you're running memgpt on one computer (that has no compute) and pointing it towards your 3090 build that has the LLM endpoint running, you can start a separate embeddings endpoint (eg with [huggingface inference endpoints](https://huggingface.co/blog/inference-endpoints-embeddings)) on the 3090 machine and use the "Custom endpoint" selection.

**Comment by cpacker** [comment]
> BTW: I created my own "fork" and work with the version before the new config files because after that update, the models did not do the same as before, so I will wait a bit until it settles before updating PRs (or I delete them).

Also as a side question @oderwat , what do you mean by "the models did not do the same as before"? CLI updates shouldn't affect model performance if you're running your own models on the 3090 box, but of course maybe we added some bugs along the way.

We want to make sure any CLI updates work for our power users (like yourself) so that we can keep you on the latest builds if possible so you can make use of all latest improvements. We also understand if you want to use a more stable fork, but hopefully with your feedback we can make the latest builds just as stable as your fork.

**Comment by oderwat** [comment]
> To get started, you need to be logged in with a User or Organization account with a payment method on file (you can add one [here](https://huggingface.co/settings/billing)), then access Inference Endpoints at [https://ui.endpoints.huggingface.co](https://ui.endpoints.huggingface.co/endpoints)

@cpacker how is using the resource your pointed out NOT having data scanned by a third party?

About the update: I had some state files and also persona which did not act the same way as before. I did not have time to look at it and saw some follow-up fixes in the repo. So I decided to stay on the last version, which is doing quite what I want with all the changes (PRs) I made. I do not really consider me a power user though. It is just, that I really like what you do with memGPT and that it actually does a bit of what I was thinking that could make the whole AI much more interesting. Sadly I do not have enough time to work into that direction a lot myself.

**Comment by cpacker** [comment]
@oderwat my bad I was just trying to quickly scan the web for the easiest way to park your own embedding model behind an API endpoint and didn't read that link through, I thought it was for self-hosting not huggingface hosting. Here's an example of what I'm talking about, using FastChat: https://github.com/lm-sys/FastChat/issues/235

**Comment by oderwat** [comment]
I tried using FastChat some days ago, but ran into problems and as I had oobabooga running for quite some time I was happy to use that. I will look into that whole topic again eventually. But let me ask: The current implementation that gets the model from huggingface. Is this just expected to be slow on my intel Mac (also with 128 GB and i7), will it send data to the outside or just don't work?

**Comment by Mark0025** [comment]
> I see. Currently, there is no endpoint for embeddings (I believe) as I just use textgen-webui. Personally I have two use cases for MemGPT: Fun + Work. Fun = Chatting with crazy agents (my dog, the devil, my evil self as replica), Work: Talking about a large amount of source code (Go) from many different projects with the ultimate goal to make it easy to write documentation, readme's, analysing bugs, and such stuff. Less about creating code itself (as for now).
> 
> I work on an intel iMac and run all my AI models on WSL2 Win11 with a RTX 3090 and 128 GB CPU RAM. I do not care at all about GPT-4 API / AZURE or anything else outside my control. This is my developer computer too, so I do not want to have stuff installed that is sending code or private information anywhere.
> 
> For me, it would obviously the best if all the demanding computational parts would be behind some API that I can run on different servers, while I love to use the terminal for connecting to MemGPT (no webui needed). I do not even want "config files". But I understand that people request that :)
> 
> BTW: I created my own "fork" and work with the version before the new config files because after that update, the models did not do the same as before, so I will wait a bit until it settles before updating PRs (or I delete them).

Just curuouis if you would care to share your forked version?

**Comment by oderwat** [comment]
@Mark0025 Not really, these are just private experiment and "old" by now. I just conserved it for when nothing works again :). As said it basically is just an older commit from here plus all my PRs at that time. Nothing the world will miss. I should say that @cpacker and @sarahwooders making a great job here. I can wait for thinks stabilizing.
