### ISSUE TITLE
How To Use The Model Wrappers?

### ISSUE THREAD

**Issue by Rivelyn** [cpacker/MemGPT#230]
I've read through the docs, and I've seen examples trying to figure out why when I use --model I keep getting this error.

AttributeError: module 'memgpt.personas.personas' has no attribute 'DEFAULT_PRESET'

I use these commands:
set OPENAI_API_BASE=http://localhost:1234
set BACKEND_TYPE=lmstudio

Then:
python -m memgpt --model zephyr-7B-beta

**Comment by vivi** [comment]
Will push a patch for this soon, but for now run it with the flag `--persona sam`

**Comment by vivi** [comment]
Closing as this has been rolled into the newest release -- `pip install -U pymemgpt`
