### ISSUE TITLE
Failed core_memory_append and core_memory_replace calls

### ISSUE THREAD

**Issue by UBCK** [cpacker/MemGPT#233]
The `core_memory_append` and `core_memory_replace` function calls seem to fail for me because `object of type 'LocalArchivalMemory' has no len()`

```
function_call": {"name": "core_memory_append", "arguments": "{\n  \"name\": \"human\",\n  \"content\": \"name: alex\",\n  \"request_heartbeat\": true\n}"}}, 
{"role": "function", "name": "core_memory_append", "content": "{\"status\": \"Failed\", \"message\": \"Error calling function core_memory_append with args {'name': 'human', 'content': 'name: alex'}: object of type 'LocalArchivalMemory' has no len()\", 
\"time\": \"2023-10-31 08:42:22 PM PDT-0700\"}"}, {"role": "user", "content": "{\"type\": \"heartbeat\", \"reason\": \"Function call failed\", \"time\": \"2023-10-31 08:42:22 PM PDT-0700\"}"}
```
```
function_call": {"name": "core_memory_replace", "arguments": "{\n  \"name\": \"persona\",\n  \"old_content\": \"sam_pov\",\n  \"new_content\": \"alice_pov\",\n  \"request_heartbeat\": true\n}"}},
{"role": "function", "name": "core_memory_replace", "content": "{\"status\": \"Failed\", \"message\": \"Error calling function core_memory_replace with args {'name': 'persona', 'old_content': 'sam_pov', 'new_content': 'alice_pov'}: object of type 'LocalArchivalMemory' has no len()\",
 \"time\": \"2023-10-31 09:04:36 PM PDT-0700\"}"}, {"role": "user", "content": "{\"type\": \"heartbeat\", \"reason\": \"Function call failed\", \"time\": \"2023-10-31 09:04:36 PM PDT-0700\"}"}

**Comment by sarahwooders** [comment]
Can you share the version of MemGPT you're using and the command you ran?

**Comment by UBCK** [comment]
Should be the latest version, installed with the command `python3 -m pip install pymemgpt` about 3 hr ago.
Python version is 3.11
The command I used to run is just `memgpt run`

**Comment by sarahwooders** [comment]
Would you be able to post a screenshot of what commands you put into `mempt run`? Or do you see this immediately after running `memgpt run`? 

Also, could you share whats in your `~/.memgpt/config` file (with any keys/private information removed)?

**Comment by UBCK** [comment]
Here you go
![image](https://github.com/cpacker/MemGPT/assets/106644385/7214e6da-8725-4b1a-bca2-b3512a59be4a)
The error messages were found in the corresponding agent_state folder after `/save`
```
[defaults]
model = gpt-4
preset = memgpt_chat
model_endpoint = openai
persona = sam_pov
human = basic

[openai]
key = ***

[embedding]
model = openai
dim = 768
chunk_size = 300

[client]
anon_clientid = 00000000000000000000fc448240b8fb
```

**Comment by cpacker** [comment]
@sarahwooders this bug is happening because len() needs to be implemented for all memory classes (it should have been part of the abstract class).

See #236
