### ISSUE TITLE
Can I use OpenAI api proxy?

### ISSUE THREAD

**Issue by OmiiiDev** [cpacker/MemGPT#24]
Can I use OpenAI api proxy? If yes then how?

**Comment by cpacker** [comment]
What do you mean by proxy here? Can you share an example?

**Comment by harveyqing** [comment]
Hi, @OmiiiDev 

The OpenAI Python API has a ``proxy`` global variable, so you can set it after your import of the package.

Just as the following image,  here I set it in the ``openai_tools.py`` module in the ``memgpt`` project.

![image](https://github.com/cpacker/MemGPT/assets/6161267/4e48c2c5-41ac-4d84-a8d3-9b5a35ef7371)

**Comment by ddwinhzy** [comment]
I would like to know another solution, I don't know how to deal with it. It is to utilize OPENAI_BASE_URL, how to solve it with this method
