### ISSUE TITLE
[BUG] recall_memory, aka. the recall_memory_search function tool is not really work

### ISSUE THREAD

**Issue by 52cs** [cpacker/MemGPT#250]
The `recall_memory` in `InMemoryStateManager` is always empty.

What you do on `InMemoryStateManager.all_messages` take no effect on `InMemoryStateManager.recall_memory`.

It is the `agent.summarize_messages_inplace` do the `recall_memory`'s job.

But when llm decide the use the `recall_memory_search` function tool, it will be misleaded with empty return.

**Comment by vivi** [comment]
`recall_memory._message_logs = InMemoryStateManager.all_messages`. They point to the same list.

https://github.com/cpacker/MemGPT/blob/main/memgpt/persistence_manager.py#L68
