### ISSUE TITLE
There is nothing can animate the `page fault` in the traditional OS

### ISSUE THREAD

**Issue by 52cs** [cpacker/MemGPT#251]
There is no data exchange between main context(memory) and external context(disk),
so there is nothing can animate the `page fault` in the traditional OS as described in your paper.

**Comment by vivi** [comment]
I'm not sure what you mean. If you're referring to #250, I have already told you that this is not the case, things are in fact stored in recall memory.

We have various [examples](https://github.com/cpacker/MemGPT#data-sources-ie-chat-with-your-data) of loading data into external context.
