### ISSUE TITLE
This model's maximum context length is 4097 tokens for gpt3.5

### ISSUE THREAD

**Issue by moviwhat** [cpacker/MemGPT#252]
**Describe the bug**
python .\main.py  --archival_storage_files="memgpt/personas/examples/preload_archival/sina.txt" --persona=memgpt_doc --human=basic --model=gpt-3.5-turbo
 This model's maximum context length is 4097 tokens. However, your messages resulted in 6157 tokens (5438 in the messages, 719 in the functions). Please reduce the length of the messages or functions.

![image](https://github.com/cpacker/MemGPT/assets/29188295/9cacab3b-03c4-4d23-b242-f8def02b7ad6)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

---

**How did you install MemGPT?**

- From the official package? `pip install pymemgpt`
- From source?
  - With [poetry](https://github.com/cpacker/MemGPT#development)?
  - With `git clone git@github.com:cpacker/MemGPT.git` and `pip install -r requirements.txt`?

**Your setup (please complete the following information)**

- Your OS (Linux, MacOS, Windows)
- Where you're trying to run MemGPT from
  - Terminal? PowerShell? cmd.exe?
- Your python version (run `python --version`)
-  If you installed with `pip install pymemgpt`:
  - `pymemgpt` version (run `pip list | grep pymemgpt`)
- If you installed from source:
  - Your current git commit (run `git describe --tags`)

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- The exact model you're trying to use (link to the HuggingFace page you downloaded it from)
  - We need the EXACT model name, including quantization scheme, e.g.: `dolphin-2.1-mistral-7b.Q6_K.gguf` (not just `dolphin-2.1-mistral`)
- The local LLM backend you are using (web UI? LM Studio?)
- Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)
- Your hardware for the MemGPT command (same computer as the local LLM backend?)
- The full output (or as much as possible) of where the LLM is failing
  - If you can include screenshots, even better!

**Comment by vivi** [comment]
Try use `--model=gpt-3.5-turbo-16k`. We should remove `gpt-3.5-turbo` or make it point to the 16k version... @cpacker

**Comment by cpacker** [comment]
> Try use `--model=gpt-3.5-turbo-16k`. We should remove `gpt-3.5-turbo` or make it point to the 16k version... @cpacker

As long as 16k is generally accessible (which I think it is now?) yeah agreed make 3.5 an alias for 3.5 16k.

**Comment by 52cs** [comment]
@all

https://github.com/cpacker/MemGPT/issues/267

https://github.com/cpacker/MemGPT/blob/main/memgpt/main.py#L528-L530

try to change

```
user_message = system.get_heartbeat(constants.FUNC_FAILED_HEARTBEAT_MESSAGE)
```

to

```
user_message = system.get_heartbeat(new_messages)
```


If it still not work after doing this, you should enhance the corresponding prompt accordingly.

**Comment by 52cs** [comment]
@all

All right.
As replied here https://github.com/cpacker/MemGPT/issues/267#issuecomment-1791908341
The error msg of function call has been record in the message history and feedback in the next loop.

But it still not work, right?

It is time to rescue for the prompt engineering.

```
raise Exception(f"Request exceeds maximum context length (code={response.status_code}, msg={response.text}, URI={URI})")
```

Or, by adding `finish_reason: "length"` in `./memgpt/local_llm` as described here https://github.com/cpacker/MemGPT/issues/270

**Comment by vivi** [comment]
We just modified the summarizer in #213. Try `pip install -U pymemgpt` and rerunning your conversation. It should work, even on 4K context length gpt-3.5.

**Comment by 52cs** [comment]
@vivi 
Come on.
https://github.com/cpacker/MemGPT/pull/213 cannot help for this issue.

You must come back and review my proposals again carefully when your os is still aboved on this case.
https://github.com/cpacker/MemGPT/issues/270
https://github.com/cpacker/MemGPT/issues/271
https://github.com/cpacker/MemGPT/issues/272

**Comment by cpacker** [comment]
Yes, this issue is solved by #213. The error messages you're seeing in the OP are because of bugged summarizer calls. The summarizer is not an explicit tool/function that MemGPT uses, and is run in the background. It is an explicit design decision to run the summarizer this way as an automated process. The way the summarizer is written if there is a failed summarize call, it should be treated as an irrecoverable error and not something that is handled by the MemGPT agent.

Please keep it civil, thank you.

**Comment by 52cs** [comment]
You can make summarizer to an explicit tool/function.

Are you kidding me?
I still don't think https://github.com/cpacker/MemGPT/pull/213 can solve this problem.
Also, summarizer is not a good design. It just a workaround. It does the `recall_memory_search`'s work.
I cannot imagine the summarizer(summarizer(summarizer, ...), ...) of the messages after a very long long conversation will look like.

**Comment by cpacker** [comment]
Please re-read what @vivi and I wrote to understand what the error message means and why #213 directly addresses it.
