### ISSUE TITLE
MemGPT is not the first who support  self-editing

### ISSUE THREAD

**Issue by 52cs** [cpacker/MemGPT#253]
MemGPT is not the first who support self-editing. https://news.ycombinator.com/item?id=37901902

If I'm correct, [FastGPT](https://fastgpt.run/) is the first who support self-editing

**Comment by vivi** [comment]
Please use this forum for raising technical issues. You're welcome to continue this discourse in our discord.

Closing this as from a quick glance at FastGPT doesn't mention self-editing anywhere.
