### ISSUE TITLE
There is no `infinite context` agent

### ISSUE THREAD

**Issue by 52cs** [cpacker/MemGPT#254]
There is no `infinite context` agent, it is just function tool powered RAG.
That is not new. Everyone do large doc retrieval should use this method.

**Comment by vivi** [comment]
Again, please use this forum for raising technical issues. You're welcome to continue the discussion in our Discord.

MemGPT gives the LLM the ability to decide if/when to make multiple calls to retrieve/sift through documents. So the agent can decide, "I did not find the answer in the current page of documents, go to the next page".

On the other hand, RAG is usually 1shot and will feed ~1 context window length worth of documents to the LLM. If you increase the number of documents brought in, you will have to truncate the content of each document to make it fit in the context window, and this might truncate the answer you're looking for.
