### ISSUE TITLE
Unreachable line in code

### ISSUE THREAD

**Issue by Simsalaba** [cpacker/MemGPT#255]
return asyncio.run(self._a_generate_reply_for_user_message(messages=messages, sender=sender, config=config))

in memgpt_agent.py

It appears to be a mistake, since it directly follows another return statement which would exit the method, making this line unreachable. Additionally, there is no definition for _a_generate_reply_for_user_message in the code snippet you provided, which suggests that this is either an incomplete implementation or a leftover from an earlier version of the code.

**Comment by vivi** [comment]
Yep - this is a leftover, good catch! Feel free to raise a PR removing it :)

**Comment by cpacker** [comment]
fixed in https://github.com/cpacker/MemGPT/commit/2fa1dedcb637caec3e8d6844b2d28c1903837a98
