### ISSUE TITLE
how to load your own documents and chat on those docs using MeMGPT?

### ISSUE THREAD

**Issue by SHRESHTHA23** [cpacker/MemGPT#258]
Hi ,

I was trying to using this on my data source but it always gives the error cannot load the agent? Is there any detailed documentation on how to use MemGPT with your own data ?

**Comment by vivi** [comment]
See: https://github.com/cpacker/MemGPT#loading-data

If it has trouble loading the agent, it's possible that the agent is corrupted you can try create a new agent with `--agent <new_agent_name>`

**Comment by Ikarus321** [comment]
Hi there, 
I got it to load my Documents folder with (memgpt) C:\Users\d-us->memgpt load directory --name Documents --input-dir C:\Users\d-us-\Desktop\Documents . But the agent doesn't recognize anything i uploaded : "I'm sorry Chad, but I couldn't find any records of a 'Documents folder' in the archival memory. Could you guide me more specifically about the documents you want me to help with?"

Also, i can't use the /attach command  -> [A[KUnrecognized command: /attach 

Any ideas?

**Comment by Ikarus321** [comment]
(memgpt) C:\Users\d-us->memgpt attach --agent MemGPT --data-source Documents
Usage: memgpt [OPTIONS] COMMAND [ARGS]...
Try 'memgpt --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────╮
│ No such command 'attach'.

**Comment by cpacker** [comment]
We just added a tutorial for chatting with your docs here: https://memgpt.readthedocs.io/en/latest/example_data/

Make sure you're on the latest version (`pip install pymemgpt -U --pre`), and the tutorial should work (`/attach` will be available). Let us know if this still isn't working for you!
