### ISSUE TITLE
Allow MemGPTs to read/write from a file(s)

### ISSUE THREAD

**Issue by cpacker** [cpacker/MemGPT#26]
Enable workflow where MemGPT + user can co-edit a document together.

Add `write_to_text_file` function and `read_to_text_file` function.

**Comment by Yash-Ambekar** [comment]
@cpacker Please elaborate the feature request with some examples. I am interested to implement this feature.

**Comment by master-harvey** [comment]
Allowing the Aider CLI tool to work with memGPTs is probably the way to go here
https://github.com/cpacker/MemGPT/issues/62

**Comment by genericrich** [comment]
Use Cases:
* Document generation - "Create an outline for a business presentation, etc."
* HTML interface presentation - "Create a UI for navigating a MemGPT managed set of documents"
* Co-editing with MemGTP - "Create a set of documents I can edit in a word processor of my choice, which MemGPT can notice changes to and react over time to."

**Comment by cpacker** [comment]
Added in #174 (still needs a preset toggle via the CLI, coming in the next release).

@genericrich @Yash-Ambekar please feel free to open new PRs / issues with more feature requests.
