### ISSUE TITLE
[BUG] failed function handling

### ISSUE THREAD

**Issue by 52cs** [cpacker/MemGPT#267]
https://github.com/cpacker/MemGPT/blob/main/memgpt/main.py#L528-L530
```
user_message = system.get_heartbeat(constants.FUNC_FAILED_HEARTBEAT_MESSAGE)
```
should change to
```
user_message = system.get_heartbeat(new_messages)
```

----------------------------

When a function execution failed, there should be useful information raised to inform llm to make correct decision, instead of using FUNC_FAILED_HEARTBEAT_MESSAGE.

Example 1,
https://github.com/cpacker/MemGPT/blob/main/memgpt/memory.py#L61-L66
```
                error_msg = f"{error_msg} Consider summarizing existing core memories in 'persona' and/or moving lower priority content to archival memory to free up space in core memory, then trying again."
            raise ValueError(error_msg)
```

Example 2,

```
./memgpt/local_llm/lmstudio/api.py:52:                raise Exception(f"Request exceeds maximum context length (code={response.status_code}, msg={response.text}, URI={URI})")
```

These raise information is very helpful to make llm to make correct decision.
Otherwise, you may see infinite function call error https://github.com/cpacker/MemGPT/issues/252

**Comment by cpacker** [comment]
What you're describing already happens, if the LLM asks to call a function, and the function fails, the exception from the failed function execution is returned to the agent (in the "function" role): https://github.com/cpacker/MemGPT/blob/main/memgpt/agent.py#L964

The code you linked is an additional message that comes after the function error message that's put in the "user" role, that passes control back to the LLM and gives the LLM an opportunity to recover from a failed function call (eg by changing the parameters it used).
