### ISSUE TITLE
Local LLM with LMStudio, setup backend and type, but running main.py has not response.

### ISSUE THREAD

**Issue by bigjonyz** [cpacker/MemGPT#277]
I am using Zephyr-7b-beta with lmstudio, and I have gotten autogen to run smoothly now. However when I try to run memgpt it returns no response what so ever. I checked the openai base and backend type, both are set at the correct value.

The value of BACKEND_TYPE is: lmstudio
The value of OPENAI_API_BASE is: http://localhost:1234
(memgpt) PS L:\AI> pyton main.py --no_verify
pyton : The term 'pyton' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if   
a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pyton main.py --no_verify
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (pyton:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
(memgpt) PS L:\AI> python main.py --no_verify
E:\ProgramData\anaconda3\envs\memgpt\python.exe: can't open file 'L:\\AI\\main.py': [Errno 2] No such file or directory
(memgpt) PS L:\AI> cd E:\ProgramData\anaconda3\envs\memgpt\Lib\site-packages\memgpt
(memgpt) PS E:\ProgramData\anaconda3\envs\memgpt\Lib\site-packages\memgpt> python main.py --no_verify
(memgpt) PS E:\ProgramData\anaconda3\envs\memgpt\Lib\site-packages\memgpt> 

As you can see when I run the main.py file it will return back to prompt, no response or messages at all. I tried with my origianl autogen env and created a new env just for memgtp, still nothing.

**Comment by ProjCRys** [comment]
This is what I did to handle memgpt + lm studio.

https://www.youtube.com/watch?v=zHtFuQiqhIo

**Comment by Watchy94** [comment]
![lmstudio](https://github.com/cpacker/MemGPT/assets/31627737/76a1cc14-1706-4bf5-babf-374580e4b694)

**Comment by ProjCRys** [comment]
Okay, I managed to make it work with python main.py.

Here's the bat file I ran (change the directories where you want to place them.)

@echo off
setlocal

REM Define the paths
set VENV_PATH=D:\AI\ChatBots\MemGPT_Setup\venv
set MEMGPT_PATH=D:\AI\ChatBots\MemGPT_Setup\MemGPT
set PYTHON_PATH=C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\python.exe

REM Create the virtual environment
"%PYTHON_PATH%" -m venv "%VENV_PATH%"

if errorlevel 1 (
    echo Error: Unable to create the virtual environment. Press any key to exit.
    pause >nul
    exit /b
)

REM Activate the virtual environment
call "%VENV_PATH%\Scripts\activate"

if errorlevel 1 (
    echo Error: Unable to activate the virtual environment. Press any key to exit.
    pause >nul
    exit /b
)

REM Install required dependencies from the correct directory
pip install -r "%MEMGPT_PATH%\requirements-local.txt"
set OPENAI_API_BASE=http://localhost:1234
set BACKEND_TYPE=lmstudio

if errorlevel 1 (
    echo Error: Failed to install dependencies. Press any key to exit.
    pause >nul
    exit /b
)

REM Run the 'python -m memgpt' command
python MemGPT/main.py

if errorlevel 1 (
    echo Error: 'python -m memgpt' encountered an error. Press any key to exit.
    pause >nul
    exit /b
)

REM Deactivate the virtual environment
deactivate

REM Wait for the user to press any key before exiting
pause >nul

**Comment by bigjonyz** [comment]
Got it working with memgpt run --no_verify --model dolphin-2.1-mistral-7b
I used the following command to set the env variables:
conda env config vars set OPENAI_API_BASE=http://localhost:1234
conda env config vars set BACKEND_TYPE=lmstudio
conda env config vars set OPENAI_API_KEY=NULL
Then deactivated conda environment and reactivated it.

I used the following python code to check all variables:
`import os

#conda env config vars set OPENAI_API_BASE=http://localhost:1234
#conda env config vars set BACKEND_TYPE=lmstudio
#conda env config vars set OPENAI_API_KEY=NULL

variable_name = "BACKEND_TYPE"
value = os.getenv(variable_name)
if value:
    print(f"The value of {variable_name} is: {value}")
else:
    print(f"{variable_name} is not defined.")

variable_name1 = "OPENAI_API_BASE"
value = os.getenv(variable_name1)
if value:
    print(f"The value of {variable_name1} is: {value}")
else:
    print(f"{variable_name1} is not defined.")

variable_name2 = "OPENAI_API_KEY"
value = os.getenv(variable_name2)
if value:
    print(f"The value of {variable_name2} is: {value}")
else:
    print(f"{variable_name2} is not defined.")`

once I ran it, it returned response:
The value of BACKEND_TYPE is: lmstudio
The value of OPENAI_API_BASE is: http://localhost:1234
The value of OPENAI_API_KEY is: NULL

Then the memgpt ran fine with occasional JSON errors.

**Comment by bigjonyz** [comment]
Now I am trying to run MemGPT + Autogen with local dolphin-mistral-7B model, and I keep getting JSON error and this one in particular:

Traceback (most recent call last):
  File "l:\AI\memgpt-autogen.py", line 130, in <module>
    user_proxy.initiate_chat(
  File "E:\ProgramData\anaconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "E:\ProgramData\anaconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "E:\ProgramData\anaconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramData\anaconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramData\anaconda3\envs\autogen\Lib\site-packages\autogen\agentchat\groupchat.py", line 162, in run_chat
    speaker = groupchat.select_speaker(speaker, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramData\anaconda3\envs\autogen\Lib\site-packages\autogen\agentchat\groupchat.py", line 91, in select_speaker
    final, name = selector.generate_oai_reply(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramData\anaconda3\envs\autogen\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 609, in generate_oai_reply
    return True, oai.ChatCompletion.extract_text_or_function_call(response)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramData\anaconda3\envs\autogen\Lib\site-packages\autogen\oai\completion.py", line 1070, in extract_text_or_function_call
    choices = response["choices"]
              ~~~~~~~~^^^^^^^^^^^
KeyError: 'choices'

I am trying the example code found on Github autogen directory. What could be the problem?

**Comment by cpacker** [comment]
Should be fixed in latest `memgpt configure` setup (https://memgpt.readthedocs.io/en/latest/quickstart/) + AutoGen patches (https://memgpt.readthedocs.io/en/latest/autogen/).

Please reopen or create a new issue if you're still having issues.
