### ISSUE TITLE
ModuleNotFoundError: No module named 'memgpt'

### ISSUE THREAD

**Issue by dashsabe** [cpacker/MemGPT#299]
import os
import autogen
import memgpt.autogen.memgpt_agent as memgpt_autogen
import memgpt.autogen.interface as autogen_interface 
import memgpt.agent as agent
import memgpt.system as system
import memgpt.utils as utils
import memgpt.presets as presets
import memgpt.constants as constants
import memgpt.personas.personas as personas
import memgpt.humans.humans as humans
from memgpt.persistence_manager import InMemoryStateManager, InMemoryStateManagerWithPreloadedArchivalMemory, InMemoryStateManagerWithFaiss
import openai
openai.api_key = 'NULL'

config_list = [
    {
        "api_type": "open_ai",
        "api_base": "http://localhost:1234/v1",
        "api_key": "NULL"
    },
]

llm_config = {"config_list": config_list, "seed": 42}
user_proxy = autogen.UserProxyAgent(
    name="User_proxy",
    system_message="A human admin.",
    code_execution_config={"last_n_messages": 2, "work_dir": "groupchat"},
)

interface = autogen_interface.AutoGenInterface() # how MemGPT talks to AutoGen
persistence_manager = InMemoryStateManager()
persona = "I\'m a 10x engineer at a FAANG tech company."
human = "I\'m a team manager at a FAANG tech company."
memgpt_agent = presets.use_preset(presets.DEFAULT, 'gpt-4', persona, human, interface, persistence_manager)

# MemGPT coder
coder = memgpt_autogen.MemGPTAgent(
    name="MemGPT_coder",
    agent=memgpt_agent,
)

# non-MemGPT PM
pm = autogen.AssistantAgent(
    name="Product_manager",
    system_message="Creative in software product ideas.",
    llm_config=llm_config,
)

groupchat = autogen.GroupChat(agents=[user_proxy, coder, pm], messages=[], max_round=12)
manager = autogen.GroupChatManager(groupchat=groupchat, llm_config=llm_config)

user_proxy.initiate_chat(manager, message="Let's go Mario!")

pip list
Package            Version
------------------ ------------
aiohttp            3.8.6
aiosignal          1.3.1
aiostream          0.5.2
annotated-types    0.6.0
anyio              3.7.1
async-timeout      4.0.3
attrs              23.1.0
black              23.10.1
certifi            2023.7.22
cffi               1.16.0
charset-normalizer 3.3.2
click              8.1.7
colorama           0.4.6
dataclasses-json   0.5.14
datasets           2.14.6
demjson3           3.0.6
Deprecated         1.2.14
dill               0.3.7
diskcache          5.6.3
faiss-cpu          1.7.4
filelock           3.13.1
FLAML              2.1.1
frozenlist         1.4.0
fsspec             2023.10.0
geographiclib      2.0
geopy              2.4.0
greenlet           3.0.1
h3                 3.7.6
huggingface-hub    0.18.0
idna               3.4
iniconfig          2.0.0
joblib             1.3.2
jsonpatch          1.33
jsonpointer        2.4
langchain          0.0.330
langsmith          0.0.57
llama-index        0.8.59
markdown-it-py     3.0.0
marshmallow        3.20.1
mdurl              0.1.2
memgpt             0.1.0
multidict          6.0.4
multiprocess       0.70.15
mypy-extensions    1.0.0
nest-asyncio       1.5.8
nltk               3.8.1
numpy              1.26.1
openai             0.28.1
packaging          23.2
pandas             2.1.2
pathspec           0.11.2
pip                23.3
platformdirs       3.11.0
pluggy             1.3.0
prettytable        3.9.0
prompt-toolkit     3.0.36
pyarrow            14.0.0
pyautogen          0.1.14
pybars3            0.9.7
pycparser          2.21
pydantic           2.4.2
pydantic_core      2.10.1
Pygments           2.16.1
pymemgpt           0.1.17
PyMeta3            0.5.1
PyMuPDF            1.23.5
PyMuPDFb           1.23.5
pytest             7.4.3
python-dateutil    2.8.2
python-dotenv      1.0.0
pytz               2023.3.post1
PyYAML             6.0.1
questionary        2.0.1
regex              2023.10.3
requests           2.31.0
rich               13.6.0
setuptools         68.2.2
shellingham        1.5.4
six                1.16.0
sniffio            1.3.0
SQLAlchemy         2.0.23
tenacity           8.2.3
termcolor          2.3.0
tiktoken           0.5.1
timezonefinder     6.2.0
tqdm               4.66.1
typer              0.9.0
typing_extensions  4.8.0
typing-inspect     0.9.0
tzdata             2023.3
urllib3            1.26.18
wcwidth            0.2.9
wheel              0.41.2
wrapt              1.15.0
xxhash             3.4.1
yarl               1.9.2

(automemgpt) 

lm studio wizzard coder local hosted server 

python --version 
Python 3.11.3

Host Name:                 [REMOVED]
OS Name:                   Microsoft Windows 11 Pro
...
Registered Owner:          [REMOVED]
Registered Organization:   [REMOVED]
Product ID:                [REMOVED]
...
System Manufacturer:       Micro-Star International Co., Ltd.
...
BIOS Version:              American Megatrends International, LLC. 1.70, 5/17/2022
...
Domain:                    WORKGROUP
Logon Server:              \\[REMOVED]
...
Network Card(s):           3 NIC(s) Installed.
...
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
...

System Manufacturer:       Micro-Star International Co., Ltd.
System Model:              MS-7C59
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 49 Stepping 0 AuthenticAMD ~3800 Mhz
BIOS Version:              American Megatrends International, LLC. 1.70, 5/17/2022
...
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) I211 Gigabit Network Connection
                                 Connection Name: Ethernet
                                 Status:          Media disconnected  
                           [02]: Intel(R) Wi-Fi 6 AX200 160MHz        
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     [REMOVED]
                                 IP address(es)
                                 [01]: [REMOVED]
                           [03]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: Ethernet 4
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: [REMOVED]
                                 [02]: [REMOVED] 
...
ADVISOR_2023_DIR=C:\Program Files (x86)\Intel\oneAPI\advisor\2023.1.0
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\#REDACTED\AppData\Roaming
BACKEND_TYPE=webui
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_61080_JVZZKDNVVSNWLHXW
CLASSPATH=.;C:\Program Files (x86)\QuickTime\QTSystem\QTJava.zip
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=#REDACTED
ComSpec=C:\Windows\system32\cmd.exe
CONDA_DEFAULT_ENV=automemgpt
CONDA_EXE=C:\Users\#REDACTED\anaconda3\condabin\..\Scripts\conda.exe
CONDA_EXES="C:\Users\#REDACTED\anaconda3\condabin\..\Scripts\conda.exe"
CONDA_PREFIX=C:\Users\#REDACTED\anaconda3\envs\automemgpt
CONDA_PREFIX_1=C:\Users\#REDACTED\anaconda3
CONDA_PROMPT_MODIFIER=(automemgpt)
CONDA_PYTHON_EXE=C:\Users\#REDACTED\anaconda3\python.exe
CONDA_SHLVL=2
DriverData=C:\Windows\System32\Drivers\DriverData
EFC_10084=1
HOMEDRIVE=C:
HOMEPATH=\Users\#REDACTED
LOCALAPPDATA=C:\Users\#REDACTED\AppData\Local
LOGONSERVER=\\#REDACTED
NUMBER_OF_PROCESSORS=48
ONEAPI_ROOT=C:\Program Files (x86)\Intel\oneAPI\
OneDrive=C:\Users\#REDACTED\OneDrive
OneDriveConsumer=C:\Users\#REDACTED\OneDrive
OPENAI_API_BASE=http://localhost:1234/v1
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
OS=Windows_NT
Path=C:\Users\#REDACTED\anaconda3\envs\automemgpt;C:\Users\#REDACTED\anaconda3\envs\automemgpt\Library\mingw-w64\bin;C:\Users\#REDACTED\anaconda3\envs\automemgpt\Library\usr\bin;C:\Users\#REDACTED\anaconda3\envs\automemgpt\Library\bin;C:\Users\#REDACTED\anaconda3\envs\automemgpt\Scripts;C:\Users\#REDACTED\anaconda3\envs\automemgpt\bin;C:\Users\#REDACTED\anaconda3\condabin;E:\VulkanSDK\1.3.250.1\Bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\ImageMagick-7.1.1-Q16-HDRI;E:\A+ Programming Archive sourcecode Dir\Direct downloads\Graphics\Vulkan 1.3.243.0\Bin;C:\Program Files (x86)\Intel\oneAPI\tbb\latest\redist\intel64\vc_mt;C:\Program Files (x86)\Intel\oneAPI\tbb\latest\redist\ia32\vc_mt;C:\Program Files (x86)\Intel\oneAPI\compiler\latest\windows\redist\intel64_win\compiler;C:\Program Files (x86)\Intel\oneAPI\compiler\latest\windows\redist\ia32_win\compiler;C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft SQL Server\150\Tools\Binn;E:\A+ Programming Archive sourcecode Dir\mingw64\bin;C:\Program Files (x86)\QuickTime\QTSystem;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files (x86)\Incredibuild;C:\Users\#REDACTED\AppData\Local\Programs\Python\Python39;C:\Program Files\nodejs;C:\Users\#REDACTED\AppData\Local\Microsoft\WindowsApps;E:\A+ Programming Archive sourcecode Dir\mingw64\bin;F:\Users\#REDACTED\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\#REDACTED\.dotnet\tools;C:\Users\#REDACTED\AppData\Local\atom\bin;C:\Users\#REDACTED\.dotnet\tools;F:\AACode\bin;C:\Users\#REDACTED\AppData\Roaming\npm;C:\Users\#REDACTED\anaconda3;C:\Users\#REDACTED\anaconda3\Scripts;.
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 23 Model 49 Stepping 0, AuthenticAMD
PROCESSOR_LEVEL=23
PROCESSOR_REVISION=3100
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=(automemgpt) $P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\
PUBLIC=C:\Users\Public
QTJAVA=C:\Program Files (x86)\QuickTime\QTSystem\QTJava.zip
SESSIONNAME=Console
SSL_CERT_FILE=C:\Users\#REDACTED\anaconda3\Library\ssl\cacert.pem
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\#REDACTED\AppData\Local\Temp
TMP=C:\Users\#REDACTED\AppData\Local\Temp
USER

**Comment by cpacker** [comment]
Should be fixed in latest integration patch: https://memgpt.readthedocs.io/en/latest/autogen
