### ISSUE TITLE
azure: openai.InvalidRequestError:  'Resource not found'

### ISSUE THREAD

**Issue by machmuel** [cpacker/MemGPT#303]
Making memgpt run with Azure OpenAI leads to the error: failed with openai.InvalidRequestError, but didn't recognize the error message: 'Resource not found'

Happens with gpt-4 as well as gpt-3.5-turbo.

I installed via `git clone git@github.com:cpacker/MemGPT.git` (0.1.6-45-g9b7153a) and `pip install -r requirements.txt` (WINDOWS 10).

Running it from VS Code (PS). Python 3.10.13

![2023-11-04 14_59_56-openai_tools py - MemGPT (Workspace) - Visual Studio Code](https://github.com/cpacker/MemGPT/assets/31520600/459a7ddf-857d-4761-a4e6-39430d21b43a)

AZURE_OPENAI_ENDPOINT=https://openai-resource-france.openai.azure.com/
AZURE_OPENAI_VERSION=2023-07-01-preview

**Comment by cpacker** [comment]
Should be fixed in latest `memgpt configure` updates: https://memgpt.readthedocs.io/en/latest/endpoints/

Please reopen if this is not the case.
