### ISSUE TITLE
Archival memory error: LocalArchivalMemory.a_insert() got an unexpected keyword argument 'embedding'

### ISSUE THREAD

**Issue by aupathletic** [cpacker/MemGPT#311]
Hello,

I am in OSX and getting the following error when the agent tries to use the archival memory:

`LocalArchivalMemory.a_insert() got an unexpected keyword argument 'embedding'`

Do I have to do something to setup the archival memory?

The persitence_manager folder of the agent does have files inside like "2023-11-04_11_32_31_AM_PDT-0700.persistence.pickle"

Thanks!

**Comment by oderwat** [comment]
I think you are on an older version and should at first try to update it.

**Comment by aupathletic** [comment]
I installed with `pip install pymemgpt` today.
Should I install directly from the repo then?

**Comment by aupathletic** [comment]
Installed directly from the repo and it indeed works. Thanks!
