### ISSUE TITLE
`core_memory_append` causes hang 

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#324]
**Describe the bug**
I ran the command `memgpt --agent agent_19 --persona memgpt_doc --debug`, and after a couple back and forths it friend to append to its core memory, but was stuck thinking for at least 5 minutes. 

<img width="1537" alt="image" src="https://github.com/cpacker/MemGPT/assets/8505980/1cc2fb5a-150d-44f7-b09b-dc0654d2d24a">

---

**How did you install MemGPT?**
- From source?
  - With [poetry](https://github.com/cpacker/MemGPT#development)?
 - Git commit `7baf3e7ce4834c758eb58d114bd27c55d0d2f876` 

**Your setup (please complete the following information)**

- MacOS
- Terminal 
- Python version: 3.10

**Comment by sarahwooders** [comment]
May be the same issue as #322

**Comment by sarahwooders** [comment]
I've debuged this issue - it's due to the `__len__` function of archival memory taking forever since it pulls everything from the database.

**Comment by cpacker** [comment]
> I've debuged this issue - it's due to the `__len__` function of archival memory taking forever since it pulls everything from the database -- will be fixed by #325

Just ran into this issue too, let's try to merge into main asap
