### ISSUE TITLE
GPT-4-Turbo

### ISSUE THREAD

**Issue by apetl** [cpacker/MemGPT#347]
**Is your feature request related to a problem? Please describe.**
The current gpt 4 implementation is expensive

**Describe the solution you'd like**
Use the new gpt-4-1106-preview which is approximately 3x cheaper

**Comment by spasmodicon** [comment]
In linux, go .memgpt > config, open config and under [defaults] just change model to "gpt-4-1106-preview" and save. I think that works.

**Comment by cpacker** [comment]
Added, will be in the next build coming to pypi later tonight (0.19)
