### ISSUE TITLE
/attach produces `Unrecognized command` error on 0.1.17

### ISSUE THREAD

**Issue by web3wes** [cpacker/MemGPT#348]
It appears on windows machines mainly, but not exclusively, `pip install --upgrade pyemgpt` does not update the module user's devices. 

As a result users see `Unrecognized command: /attach` even after upgrade. 

<img width="446" alt="Screenshot 2023-11-07 at 12 26 47 AM" src="https://github.com/cpacker/MemGPT/assets/97464975/5f53ca2b-413a-4b11-b144-d7acaae68b48">

**Comment by cpacker** [comment]
Thank you for reporting! This should be fixed in the latest release that just went live (0.1.18), please let us know if it's still not working.
