### ISSUE TITLE
Readline package not used at all? And it is not available on Win platform

### ISSUE THREAD

**Issue by yhyu13** [cpacker/MemGPT#35]
Try pip install readline, shown not availble to windows platform

```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple, https://download.pytorch.org/whl/cu118
Collecting readline
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/f4/01/2cf081af8d880b44939a5f1b446551a7f8d59eae414277fd0c303757ff1b/readline-6.2.4.1.tar.gz (2.3 MB)
     ---------------------------------------- 2.3/2.3 MB 10.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: this module is not meant to work on Windows
      [end of output]
```

Readline is imported here, but it does not seems to be used anywhere, and memgpt runs fine when commenting this line out!
https://github.com/cpacker/MemGPT/blob/134df8f7ea68d4dd07a9f9d6cdac6b0c46c12ff3/main.py#L7

**Comment by vivi** [comment]
Sorry about this. This was done to support longer inputs on the MemGPT console. The right thing to do is probably to install `pyreadline3` and then

```
from pyreadline3 import Readline
readline = Readline()
```

Will patch shortly

**Comment by vivi** [comment]
Ah, could you try adding `import readline` back and then running
`pip install pyreadline3`

and see if that works?

**Comment by yhyu13** [comment]
> Ah, could you try adding `import readline` back and then running `pip install pyreadline3`
> 
> and see if that works?

@vivi Thanks! I think it works the way you suggested!
