### ISSUE TITLE
Add support for gpt-4-turbo

### ISSUE THREAD

**Issue by CUexter** [cpacker/MemGPT#354]
**Is your feature request related to a problem? I guess gpt-4-turbo would be faster ?

**Describe the solution you'd like**
Simply add options for using gpt-4-turbo in memgpt configure, i suppose that to tokenlimit need to be adjust too ? 

**Additional Context**
maybe wait after gpt-4-turbo is fully released yet ?

**Comment by poopato** [comment]
#349
