### ISSUE TITLE
Cannot load agents / new agents have no memory

### ISSUE THREAD

**Issue by ziontee113** [cpacker/MemGPT#356]
**Describe the bug**
MemGPT prompts me to select an existing agent, I pick one, no matter what I pick, MemGPT will crash instantly with error: `ValueError: Cannot load agent_1`

**To Reproduce**
1. `memgpt run`
2. Pick an already existing agent `agent_1`
3. MemGPT Crash

**Expected behavior**
I don't know because I haven't loaded existing agents successfully ever.

**Screenshots**
![Screenshot from 2023-11-07 18-37-20](https://github.com/cpacker/MemGPT/assets/102876811/616c435c-719e-4ef0-98f0-3a8746e79249)
![Screenshot from 2023-11-07 18-37-35](https://github.com/cpacker/MemGPT/assets/102876811/b75dba8e-8fdc-4b04-b7ee-545f2239bd84)

**Additional context**

Full error message
```
  /mnt/136gb_SSD/learn-python/MemGPT ❮ memgpt run                                                                                                                                         8s  MemGPT  18:30:45
? Would you like to select an existing agent? Yes
? Select agent: agent_1
Using existing agent agent_1
/load error: no .json checkpoint files found
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/136gb_SSD/learn-python/MemGPT/venv/lib/python3.11/site-packages/memgpt/cli/cli.py:117 in    │
│ run                                                                                              │
│                                                                                                  │
│   114 │   │   │   raise ValueError(f"Cannot override {agent_config.name} existing model {agent   │
│   115 │   │                                                                                      │
│   116 │   │   # load existing agent                                                              │
│ ❱ 117 │   │   memgpt_agent = AgentAsync.load_agent(memgpt.interface, agent_config)               │
│   118 │   else:  # create new agent                                                              │
│   119 │   │   # create new agent config: override defaults with args if provided                 │
│   120 │   │   typer.secho("Creating new agent...", fg=typer.colors.GREEN)                        │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │           agent = 'agent_1'                                                                  │ │
│ │    agent_config = AgentConfig()                                                              │ │
│ │     agent_files = ['agent_2', 'agent_3', 'agent_1']                                          │ │
│ │          agents = ['agent_2', 'agent_3', 'agent_1']                                          │ │
│ │          config = MemGPTConfig(                                                              │ │
│ │                   │   config_path='/home/ziontee113/.memgpt/config',                         │ │
│ │                   │   anon_clientid='00000000000000000000fcaa1403ba94',                      │ │
│ │                   │   preset='memgpt_chat',                                                  │ │
│ │                   │   model_endpoint='http://localhost:11434',                               │ │
│ │                   │   model='local',                                                         │ │
│ │                   │   openai_key=None,                                                       │ │
│ │                   │   azure_key=None,                                                        │ │
│ │                   │   azure_endpoint=None,                                                   │ │
│ │                   │   azure_version=None,                                                    │ │
│ │                   │   azure_deployment=None,                                                 │ │
│ │                   │   azure_embedding_deployment=None,                                       │ │
│ │                   │   default_persona='sam_pov',                                             │ │
│ │                   │   default_human='basic',                                                 │ │
│ │                   │   default_agent=None,                                                    │ │
│ │                   │   embedding_model='http://localhost:11434',                              │ │
│ │                   │   embedding_dim=1536,                                                    │ │
│ │                   │   embedding_chunk_size=300,                                              │ │
│ │                   │   archival_storage_type='local',                                         │ │
│ │                   │   archival_storage_path=None,                                            │ │
│ │                   │   archival_storage_uri=None,                                             │ │
│ │                   │   recall_storage_type='local',                                           │ │
│ │                   │   recall_storage_path=None,                                              │ │
│ │                   │   recall_storage_uri=None,                                               │ │
│ │                   │   persistence_manager_type=None,                                         │ │
│ │                   │   persistence_manager_save_file=None,                                    │ │
│ │                   │   persistence_manager_uri=None                                           │ │
│ │                   )                                                                          │ │
│ │           debug = False                                                                      │ │
│ │     embed_model = OpenAIEmbedding(                                                           │ │
│ │                   │   model_name='text-embedding-ada-002',                                   │ │
│ │                   │   embed_batch_size=10,                                                   │ │
│ │                   │   callback_manager=<llama_index.callbacks.base.CallbackManager object at │ │
│ │                   0x7f74f0000fd0>,                                                           │ │
│ │                   │   deployment_name=None,                                                  │ │
│ │                   │   additional_kwargs={},                                                  │ │
│ │                   │   api_key='yourkeyhere',                                                 │ │
│ │                   │   api_type='open_ai',                                                    │ │
│ │                   │   api_base='http://localhost:11434',                                     │ │
│ │                   │   api_version=''                                                         │ │
│ │                   )                                                                          │ │
│ │           first = False                                                                      │ │
│ │           human = None                                                                       │ │
│ │           model = None                                                                       │ │
│ │       no_verify = False                                                                      │ │
│ │ original_stdout = <colorama.ansitowin32.StreamWrapper object at 0x7f7503a6b210>              │ │
│ │         persona = None                                                                       │ │
│ │          preset = None                                                                       │ │
│ │    select_agent = True                                                                       │ │
│ │ service_context = ServiceContext(                                                            │ │
│ │                   │   llm_predictor=LLMPredictor(                                            │ │
│ │                   │   │   system_prompt=None,                                                │ │
│ │                   │   │   query_wrapper_prompt=None,                                         │ │
│ │                   │   │   pydantic_program_mode=<PydanticProgramMode.DEFAULT: 'default'>     │ │
│ │                   │   ),                                                                     │ │
│ │                   │   prompt_helper=PromptHelper(                                            │ │
│ │                   │   │   context_window=3900,                                               │ │
│ │                   │   │   num_output=256,                                                    │ │
│ │                   │   │   chunk_overlap_ratio=0.1,                                           │ │
│ │                   │   │   chunk_size_limit=None,                                             │ │
│ │                   │   │   separator=' '                                                      │ │
│ │                   │   ),                                                                     │ │
│ │                   │   embed_model=OpenAIEmbedding(                                           │ │
│ │                   │   │   model_name='text-embedding-ada-002',                               │ │
│ │                   │   │   embed_batch_size=10,                                               │ │
│ │                   │   │   callback_manager=<llama_index.callbacks.base.CallbackManager       │ │
│ │                   object at 0x7f74f0000fd0>,                                                 │ │
│ │                   │   │   deployment_name=None,                                              │ │
│ │                   │   │   additional_kwargs={},                                              │ │
│ │                   │   │   api_key='yourkeyhere',                                             │ │
│ │                   │   │   api_type='open_ai',                                                │ │
│ │                   │   │   api_base='http://localhost:11434',                                 │ │
│ │                   │   │   api_version=''                                                     │ │
│ │                   │   ),                                                                     │ │
│ │                   │   node_parser=SimpleNodeParser(                                          │ │
│ │                   │   │   text_splitter=SentenceSplitter(                                    │ │
│ │                   │   │   │   chunk_size=300,                                                │ │
│ │                   │   │   │   chunk_overlap=20,                                              │ │
│ │                   │   │   │   separator=' ',                                                 │ │
│ │                   │   │   │   paragraph_separator='\n\n\n',                                  │ │
│ │                   │   │   │   secondary_chunking_regex='[^,.;。？！]+[,.;。？！]?',          │ │
│ │                   │   │   │   chunking_tokenizer_fn=<function                                │ │
│ │                   split_by_sentence_tokenizer.<locals>.split at 0x7f74f0167ba0>,             │ │
│ │                   │   │   │   callback_manager=<llama_index.callbacks.base.CallbackManager   │ │
│ │                   object at 0x7f74f0000fd0>,                                                 │ │
│ │                   │   │   │   tokenizer=functools.partial(<bound method Encoding.encode of   │ │
│ │                   <Encoding 'gpt2'>>, allowed_special='all')                                 │ │
│ │                   │   │   ),                                                                 │ │
│ │                   │   │   include_metadata=True,                                             │ │
│ │                   │   │   include_prev_next_rel=True,                                        │ │
│ │                   │   │   metadata_extractor=None,                                           │ │
│ │                   │   │   callback_manager=<llama_index.callbacks.base.CallbackManager       │ │
│ │                   object at 0x7f74f0000fd0>                                                  │ │
│ │                   │   ),                                                                     │ │
│ │                   │   llama_logger=<llama_index.logger.base.LlamaLogger object at            │ │
│ │                   0x7f74f032c190>,                                                           │ │
│ │                   │   callback_manager=<llama_index.callbacks.base.CallbackManager object at │ │
│ │                   0x7f74f0000fd0>                                                            │ │
│ │                   )                                                                          │ │
│ │        strip_ui = False                                                                      │ │
│ │             yes = False                                                                      │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /mnt/136gb_SSD/learn-python/MemGPT/venv/lib/python3.11/site-packages/memgpt/agent.py:376 in      │
│ load_agent                                                                                       │
│                                                                                                  │
│    373 │   │   json_files = glob.glob(os.path.join(directory, "*.json"))  # This will list all   │
│    374 │   │   if not json_files:                                                                │
│    375 │   │   │   print(f"/load error: no .json checkpoint files found")                        │
│ ❱  376 │   │   │   raise ValueError(f"Cannot load {agent_name}")                                 │
│    377 │   │                                                                                     │
│    378 │   │   # Sort files based on modified timestamp, with the latest file being the first.   │
│    379 │   │   filename = max(json_files, key=os.path.getmtime)                                  │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ agent_config = AgentConfig()                                                                 │ │
│ │   agent_name = 'agent_1'                                                                     │ │
│ │          cls = <class 'memgpt.agent.AgentAsync'>                                             │ │
│ │    directory = '/home/ziontee113/.memgpt/agents/agent_1/agent_state'                         │ │
│ │    interface = <module 'memgpt.interface' from                                               │ │
│ │                '/mnt/136gb_SSD/learn-python/MemGPT/venv/lib/python3.11/site-packages/memgpt… │ │
│ │   json_files = []                                                                            │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Cannot load agent_1
```

---

**How did you install MemGPT?**

1. Create & enter a new `venv`
2. `pip install pymemgpt`
3. Set environment varables
```bash
export OPENAI_API_BASE=http://localhost:11434
export BACKEND_TYPE=ollama
export OLLAMA_MODEL=dolphin2.2-mistral:latest
export OPENAI_API_KEY=yourkeyhere # otherwise it's gonna crash asking for OPENAI_API_KEY
```
**Your setup (please complete the following information)**

- Your OS --> Arch Linux
- Where you're trying to run MemGPT from --> ZSH terminal
- Your python version --> 3.11.3

**Comment by khawajaJunaid** [comment]
3

> **Describe the bug** MemGPT prompts me to select an existing agent, I pick one, no matter what I pick, MemGPT will crash instantly with error: `ValueError: Cannot load agent_1`
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. `memgpt run`
> 2. Pick an already existing agent `agent_1`
> 3. MemGPT Crash
> 
> **Expected behavior** I don't know because I haven't loaded existing agents successfully ever.
> 
> **Screenshots** ![Screenshot from 2023-11-07 18-37-20](https://user-images.githubusercontent.com/102876811/281024802-616c435c-719e-4ef0-98f0-3a8746e79249.png) ![Screenshot from 2023-11-07 18-37-35](https://user-images.githubusercontent.com/102876811/281024804-b75dba8e-8fdc-4b04-b7ee-545f2239bd84.png)
> 
> **Additional context**
> 
> Full error message
> 
> ```
>   /mnt/136gb_SSD/learn-python/MemGPT ❮ memgpt run                                                                                                                                         8s  MemGPT  18:30:45
> ? Would you like to select an existing agent? Yes
> ? Select agent: agent_1
> Using existing agent agent_1
> /load error: no .json checkpoint files found
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ /mnt/136gb_SSD/learn-python/MemGPT/venv/lib/python3.11/site-packages/memgpt/cli/cli.py:117 in    │
> │ run                                                                                              │
> │                                                                                                  │
> │   114 │   │   │   raise ValueError(f"Cannot override {agent_config.name} existing model {agent   │
> │   115 │   │                                                                                      │
> │   116 │   │   # load existing agent                                                              │
> │ ❱ 117 │   │   memgpt_agent = AgentAsync.load_agent(memgpt.interface, agent_config)               │
> │   118 │   else:  # create new agent                                                              │
> │   119 │   │   # create new agent config: override defaults with args if provided                 │
> │   120 │   │   typer.secho("Creating new agent...", fg=typer.colors.GREEN)                        │
> │                                                                                                  │
> │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
> │ │           agent = 'agent_1'                                                                  │ │
> │ │    agent_config = AgentConfig()                                                              │ │
> │ │     agent_files = ['agent_2', 'agent_3', 'agent_1']                                          │ │
> │ │          agents = ['agent_2', 'agent_3', 'agent_1']                                          │ │
> │ │          config = MemGPTConfig(                                                              │ │
> │ │                   │   config_path='/home/ziontee113/.memgpt/config',                         │ │
> │ │                   │   anon_clientid='00000000000000000000fcaa1403ba94',                      │ │
> │ │                   │   preset='memgpt_chat',                                                  │ │
> │ │                   │   model_endpoint='http://localhost:11434',                               │ │
> │ │                   │   model='local',                                                         │ │
> │ │                   │   openai_key=None,                                                       │ │
> │ │                   │   azure_key=None,                                                        │ │
> │ │                   │   azure_endpoint=None,                                                   │ │
> │ │                   │   azure_version=None,                                                    │ │
> │ │                   │   azure_deployment=None,                                                 │ │
> │ │                   │   azure_embedding_deployment=None,                                       │ │
> │ │                   │   default_persona='sam_pov',                                             │ │
> │ │                   │   default_human='basic',                                                 │ │
> │ │                   │   default_agent=None,                                                    │ │
> │ │                   │   embedding_model='http://localhost:11434',                              │ │
> │ │                   │   embedding_dim=1536,                                                    │ │
> │ │                   │   embedding_chunk_size=300,                                              │ │
> │ │                   │   archival_storage_type='local',                                         │ │
> │ │                   │   archival_storage_path=None,                                            │ │
> │ │                   │   archival_storage_uri=None,                                             │ │
> │ │                   │   recall_storage_type='local',                                           │ │
> │ │                   │   recall_storage_path=None,                                              │ │
> │ │                   │   recall_storage_uri=None,                                               │ │
> │ │                   │   persistence_manager_type=None,                                         │ │
> │ │                   │   persistence_manager_save_file=None,                                    │ │
> │ │                   │   persistence_manager_uri=None                                           │ │
> │ │                   )                                                                          │ │
> │ │           debug = False                                                                      │ │
> │ │     embed_model = OpenAIEmbedding(                                                           │ │
> │ │                   │   model_name='text-embedding-ada-002',                                   │ │
> │ │                   │   embed_batch_size=10,                                                   │ │
> │ │                   │   callback_manager=<llama_index.callbacks.base.CallbackManager object at │ │
> │ │                   0x7f74f0000fd0>,                                                           │ │
> │ │                   │   deployment_name=None,                                                  │ │
> │ │                   │   additional_kwargs={},                                                  │ │
> │ │                   │   api_key='yourkeyhere',                                                 │ │
> │ │                   │   api_type='open_ai',                                                    │ │
> │ │                   │   api_base='http://localhost:11434',                                     │ │
> │ │                   │   api_version=''                                                         │ │
> │ │                   )                                                                          │ │
> │ │           first = False                                                                      │ │
> │ │           human = None                                                                       │ │
> │ │           model = None                                                                       │ │
> │ │       no_verify = False                                                                      │ │
> │ │ original_stdout = <colorama.ansitowin32.StreamWrapper object at 0x7f7503a6b210>              │ │
> │ │         persona = None                                                                       │ │
> │ │          preset = None                                                                       │ │
> │ │    select_agent = True                                                                       │ │
> │ │ service_context = ServiceContext(                                                            │ │
> │ │                   │   llm_predictor=LLMPredictor(                                            │ │
> │ │                   │   │   system_prompt=None,                                                │ │
> │ │                   │   │   query_wrapper_prompt=None,                                         │ │
> │ │                   │   │   pydantic_program_mode=<PydanticProgramMode.DEFAULT: 'default'>     │ │
> │ │                   │   ),                                                                     │ │
> │ │                   │   prompt_helper=PromptHelper(                                            │ │
> │ │                   │   │   context_window=3900,                                               │ │
> │ │                   │   │   num_output=256,                                                    │ │
> │ │                   │   │   chunk_overlap_ratio=0.1,                                           │ │
> │ │                   │   │   chunk_size_limit=None,                                             │ │
> │ │                   │   │   separator=' '                                                      │ │
> │ │                   │   ),                                                                     │ │
> │ │                   │   embed_model=OpenAIEmbedding(                                           │ │
> │ │                   │   │   model_name='text-embedding-ada-002',                               │ │
> │ │                   │   │   embed_batch_size=10,                                               │ │
> │ │                   │   │   callback_manager=<llama_index.callbacks.base.CallbackManager       │ │
> │ │                   object at 0x7f74f0000fd0>,                                                 │ │
> │ │                   │   │   deployment_name=None,                                              │ │
> │ │                   │   │   additional_kwargs={},                                              │ │
> │ │                   │   │   api_key='yourkeyhere',                                             │ │
> │ │                   │   │   api_type='open_ai',                                                │ │
> │ │                   │   │   api_base='http://localhost:11434',                                 │ │
> │ │                   │   │   api_version=''                                                     │ │
> │ │                   │   ),                                                                     │ │
> │ │                   │   node_parser=SimpleNodeParser(                                          │ │
> │ │                   │   │   text_splitter=SentenceSplitter(                                    │ │
> │ │                   │   │   │   chunk_size=300,                                                │ │
> │ │                   │   │   │   chunk_overlap=20,                                              │ │
> │ │                   │   │   │   separator=' ',                                                 │ │
> │ │                   │   │   │   paragraph_separator='\n\n\n',                                  │ │
> │ │                   │   │   │   secondary_chunking_regex='[^,.;。？！]+[,.;。？！]?',          │ │
> │ │                   │   │   │   chunking_tokenizer_fn=<function                                │ │
> │ │                   split_by_sentence_tokenizer.<locals>.split at 0x7f74f0167ba0>,             │ │
> │ │                   │   │   │   callback_manager=<llama_index.callbacks.base.CallbackManager   │ │
> │ │                   object at 0x7f74f0000fd0>,                                                 │ │
> │ │                   │   │   │   tokenizer=functools.partial(<bound method Encoding.encode of   │ │
> │ │                   <Encoding 'gpt2'>>, allowed_special='all')                                 │ │
> │ │                   │   │   ),                                                                 │ │
> │ │                   │   │   include_metadata=True,                                             │ │
> │ │                   │   │   include_prev_next_rel=True,                                        │ │
> │ │                   │   │   metadata_extractor=None,                                           │ │
> │ │                   │   │   callback_manager=<llama_index.callbacks.base.CallbackManager       │ │
> │ │                   object at 0x7f74f0000fd0>                                                  │ │
> │ │                   │   ),                                                                     │ │
> │ │                   │   llama_logger=<llama_index.logger.base.LlamaLogger object at            │ │
> │ │                   0x7f74f032c190>,                                                           │ │
> │ │                   │   callback_manager=<llama_index.callbacks.base.CallbackManager object at │ │
> │ │                   0x7f74f0000fd0>                                                            │ │
> │ │                   )                                                                          │ │
> │ │        strip_ui = False                                                                      │ │
> │ │             yes = False                                                                      │ │
> │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
> │                                                                                                  │
> │ /mnt/136gb_SSD/learn-python/MemGPT/venv/lib/python3.11/site-packages/memgpt/agent.py:376 in      │
> │ load_agent                                                                                       │
> │                                                                                                  │
> │    373 │   │   json_files = glob.glob(os.path.join(directory, "*.json"))  # This will list all   │
> │    374 │   │   if not json_files:                                                                │
> │    375 │   │   │   print(f"/load error: no .json checkpoint files found")                        │
> │ ❱  376 │   │   │   raise ValueError(f"Cannot load {agent_name}")                                 │
> │    377 │   │                                                                                     │
> │    378 │   │   # Sort files based on modified timestamp, with the latest file being the first.   │
> │    379 │   │   filename = max(json_files, key=os.path.getmtime)                                  │
> │                                                                                                  │
> │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
> │ │ agent_config = AgentConfig()                                                                 │ │
> │ │   agent_name = 'agent_1'                                                                     │ │
> │ │          cls = <class 'memgpt.agent.AgentAsync'>                                             │ │
> │ │    directory = '/home/ziontee113/.memgpt/agents/agent_1/agent_state'                         │ │
> │ │    interface = <module 'memgpt.interface' from                                               │ │
> │ │                '/mnt/136gb_SSD/learn-python/MemGPT/venv/lib/python3.11/site-packages/memgpt… │ │
> │ │   json_files = []                                                                            │ │
> │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> ValueError: Cannot load agent_1
> ```
> 
> **How did you install MemGPT?**
> 
> 1. Create & enter a new `venv`
> 2. `pip install pymemgpt`
> 3. Set environment varables
> 
> ```shell
> export OPENAI_API_BASE=http://localhost:11434
> export BACKEND_TYPE=ollama
> export OLLAMA_MODEL=dolphin2.2-mistral:latest
> export OPENAI_API_KEY=yourkeyhere # otherwise it's gonna crash asking for OPENAI_API_KEY
> ```
> 
> **Your setup (please complete the following information)**
> 
> * Your OS --> Arch Linux
> * Where you're trying to run MemGPT from --> ZSH terminal
> * Your python version --> 3.11.3

how did you terminate your agent ?

**Comment by ziontee113** [comment]
> how did you terminate your agent ?

I used `Ctrl+D` to terminate.

**Comment by cpacker** [comment]
This should not be an issue anymore due to autosaving / clean close, but please reopen if I am mistaken.

**Comment by Aishikboy109** [comment]
I am using memgpt python client and eaaaach time I runthe code, a new agent is created with fresh memory. I cannot find any documentation regarding how to load existing agents in the python client. Here's my code :


```
from memgpt import MemGPT
# from memgpt.generate_text import generate_text
# Create a MemGPT client object (sets up the persistent state)
client = MemGPT(
    quickstart="memgpt_hosted",
    config={
        "throw_if_exists": True,
    }
)

# You can set many more parameters, this is just a basic example
agent_id = client.create_agent(
    agent_config={
        "persona": "sam_pov",
        "human": "aishik",
        # "name": "Robert"
    }
)
# agent_id = client.load_agent("./agent_7/config.json")
# agent_id = client.load_from_json_file("./agent_7/config.json")

# Now that we have an agent_name identifier, we can send it a message!
# The response will have data from the MemGPT agent
while True:
  q = input("USER >>> ")
  if q == "/exit":
    break
  # my_message = "call me Aishik"
  response = client.user_message(agent_id=agent_id, message=q)
  # print(response)
  key = "assistant_message"
  for i in response:
      if key in i:
          print(i.get(key))
          
# print(agent_id)

```
