### ISSUE TITLE
[question ]Regarding the GPT-4 API

### ISSUE THREAD

**Issue by shalimujiang** [cpacker/MemGPT#36]
I saw in the README.md file that it mentions using the GPT-4 API, but I don't have access to the official OpenAI GPT-4 API. I'm wondering if I can use a third-party service that offers OpenAI GPT-4 API, like this website: https://docs.aiproxy.io/guide/quick-start. If it's possible, how should I set it up?

**Comment by cpacker** [comment]
To get an OpenAI API key that has GPT-4 access follow these instructions: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

Quite a few people have been commenting on the Discord about their issues with getting working keys, so maybe hop on the Discord and search for "api key" to see if anyone else has the same issues.
