### ISSUE TITLE
MemGPT not making use of more than one GPU

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [cpacker/MemGPT#363]
I got my second GPU today, when I tested performance I noticed that MemGPT isn't making use of additional GPU's except for 1 second each time you submit something. The image included is self explanatory,  I simply flipped from the cli window to the browser to pose the same question.

![image](https://github.com/cpacker/MemGPT/assets/123831682/9d6f27fb-a8b7-44fd-91d4-bfe027bbbb52)

**Comment by cpacker** [comment]
What backend are you using? GPU usage will be determined by the backend, if webui, make sure you do CUDA_VISIBLE_DEVICES correctly + roll the sliders to the right on GPU memory usage.

**Comment by TheOnlyWiseJEDI** [comment]
This is necessary even though both GPU's are showing and working fine in
webui already?

I did already move both sliders over before opening the issue ticket. The
graphic I included shows how they are both being used when I am using the
webui html chat interface but not when using memgpt in the cli.

**Comment by cpacker** [comment]
_Closing b/c usage of GPUs with a custom LLM backend is more about the LLM backend setup than MemGPT_
