### ISSUE TITLE
Allow MemGPT to access the web? 

### ISSUE THREAD

**Issue by ProjCRys** [cpacker/MemGPT#375]
**Is your feature request related to a problem? Please describe.**
This would be useful so that MemGPT could have knowledge to currents events as well as add what they learned to their archive. 

**Describe the solution you'd like**
It could make http requests on google or any search engines then grab the first few results as reference.

**Comment by cpacker** [comment]
Closing b/c HTTP requests are part of the included `memgpt_extras` preset
