### ISSUE TITLE
Running configure looses all settings and overwrites old config loosing some settings. 

### ISSUE THREAD

**Issue by agiletechnologist** [cpacker/MemGPT#377]
**Describe the bug**
Running memgpt configure to reconfigure loses previous settings.  This should read the previous config if exists and set those options as default selected options or values for prompts. Reconfiguring options are 1 or 2 changes.  for example persona or human may need to be changed. 

**To Reproduce**
1. Run memgpt configure
2. configure a custom human
3. Run memgpt configure again
4. See that all saved configurations selected are lost or must be set again.

**Expected behavior**
Should have the default options set to saved configuration if configuration file exists. 

---

**How did you install MemGPT?**

- From the official package? `pip install pymemgpt`
- From source?
 - With `git clone git@github.com:cpacker/MemGPT.git` and `pip install -r requirements.txt`?

**Your setup (please complete the following information)**

- Your OS:  Windows
- Where you're trying to run MemGPT from
  - Terminal & PowerShell & cmd.exe
- Your python version (run `python --version`) Python 3.11.6
-  If you installed with `pip install pymemgpt`:
  - `pymemgpt` version (run `pip list | grep pymemgpt`) pymemgpt 0.1.18
- If you installed from source:
  - Your current git commit (run `git describe --tags`) 0.1.15-90-g7d6aa40

**Comment by sarahwooders** [comment]
Add in #389
