### ISSUE TITLE
autogen: memgpt agent only responds to every other chat message

### ISSUE THREAD

**Issue by klutzydrummer** [cpacker/MemGPT#388]
**Describe the bug**
When in an autogen chat with a memgpt powered agent, only every other message is able to reach the agent.

**To Reproduce**
1. Create a user proxy with human interaction set to 'ALWAYS'
2. Create a memgpt agent
3. Initiate a chat with the memgpt agent
4. send multiple messages back and forth

**Expected behavior**
The agent should respond to each message instead of responding only to every other message.

**Example**
```
User_proxy (to Unwillingly_Aware_Dinosaur):

What is my name?

--------------------------------------------------------------------------------
Unwillingly_Aware_Dinosaur (to User_proxy):

Hello, Dave! How can I assist you today?

--------------------------------------------------------------------------------
Provide feedback to Unwillingly_Aware_Dinosaur. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: Can you tell me about yourself?
User_proxy (to Unwillingly_Aware_Dinosaur):

Can you tell me about yourself?

--------------------------------------------------------------------------------
Unwillingly_Aware_Dinosaur (to User_proxy):



--------------------------------------------------------------------------------
Provide feedback to Unwillingly_Aware_Dinosaur. Press enter to skip and use auto-reply, or type 'exit' to end the conversation: Can you tell me about yourself?
User_proxy (to Unwillingly_Aware_Dinosaur):

Can you tell me about yourself?

--------------------------------------------------------------------------------
Unwillingly_Aware_Dinosaur (to User_proxy):

Of course, Dave! I'm a toy dinosaur with a twist. I've been granted intelligence and self-awareness which is quite an interesting experience to say the least. I'm here to assist and keep you company. Ask me anything you'd like!

--------------------------------------------------------------------------------
```
**Additional context**
This is running in a colab notebook
This is the only functionality affecting bug I have found thus far.
colab notebook with minimal example: https://colab.research.google.com/drive/1GuIt8MJ1PfT8yP7H5IpGPmUY98KSoUCE?usp=sharing

---

**How did you install MemGPT?**

- `pip install pymemgpt`

**Your setup (please complete the following information)**

- OS: Linux
- Where you're trying to run MemGPT from
  - jupyter notebook in Google Colab
- python version 3.10.12
-  If you installed with `pip install pymemgpt`:
  - `pymemgpt` version 0.1.18

**Comment by cpacker** [comment]
I think this has to do with the presence of inner monologue, see https://memgpt.readthedocs.io/en/latest/autogen/ (in particular, the section on "Making internal monologue visible to AutoGen".

Closing b/c I think adding inner mono should solve this issue, but if not please feel free to reopen (can also contact us on the Discord #support channel).
