### ISSUE TITLE
Documentation: additional infos to run on Windows

### ISSUE THREAD

**Issue by AxelBL** [cpacker/MemGPT#39]
I'd suggest the following updates to the documentation:

**Add your OpenAI API key to your environment:**
- on Linux/Mac: export OPENAI_API_KEY=YOUR_API_KEY
- on Windows: setx OpenAI_API_KEY = YOUR_API_KEY

**"Use MemGPT to talk to your Database:"**
- on Linux/Mac: pip install readline
- on Windows: pip install pyreadline
(or add to requirements.txt)

**Comment by cpacker** [comment]
Thank you! Information added to the README: https://github.com/cpacker/MemGPT/blob/main/README.md#running-memgpt-locally

If there are any mistakes or you think the information could be reworded / reorganized to make it more clear, feel free to re-open this issue or create PR with the README edits directly.
