### ISSUE TITLE
Missing menu to choose pre-existing agent

### ISSUE THREAD

**Issue by danx0r** [cpacker/MemGPT#391]
**Describe the bug**
CLI no longer offers menu of agents

**To Reproduce**
`memgpt run --no_verify`

**Expected behavior**
User is presented with list of agents to choose from (if any exist)

**Actual behavior**
```New agent always created unless user specifies with --agent```

**Additional context**
after running configure:
```
ubuntu@ip-172-31-40-1 ~/MemGPT (main) [SIGINT]> memgpt run --no_verify --model dolphin-2.1-mistral-7b
Creating new agent...
Created new agent agent_3.
Hit enter to begin (will request first MemGPT message)^C  
Aborted.
ubuntu@ip-172-31-40-1 ~/MemGPT (main) [1]> memgpt run --no_verify --model dolphin-2.1-mistral-7b
Creating new agent...
Created new agent agent_4.
Hit enter to begin (will request first MemGPT message)
```
---

**How did you install MemGPT?**
  - With `git clone git@github.com:cpacker/MemGPT.git` and `pip install -r requirements.txt`

**Your setup (please complete the following information)**

- Your OS (Linux, MacOS, Windows)
  - Ubuntu 22.04
  - 
- Where you're trying to run MemGPT from
  - Terminal
- Your python version (run `python --version`)
 - 3.10.12
-  If you installed with `pip install pymemgpt`:
  - `pymemgpt` version (run `pip list | grep pymemgpt`)
- If you installed from source:
  - Your current git commit (run `git describe --tags`)
  - 1ef9e91

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- The exact model you're trying to use (link to the HuggingFace page you downloaded it from)
  - We need the EXACT model name, including quantization scheme, e.g.: `dolphin-2.1-mistral-7b.Q6_K.gguf` (not just `dolphin-2.1-mistral`)
  - dolphin-2.2.1-mistral-7b unquantized
- The local LLM backend you are using (web UI? LM Studio?)
  - webui
- Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)
  - AWS EC2 g5.2xlarge
- Your hardware for the MemGPT command (same computer as the local LLM backend?)
  - ditto
- The full output (or as much as possible) of where the LLM is failing
  - If you can include screenshots, even better!
  - see above

**Comment by cpacker** [comment]
_Closing b/c I don't think this is an issue in the current version, please reopen if I'm mistaken_
