### ISSUE TITLE
Not running with the LLM selected on LM Studio.

### ISSUE THREAD

**Issue by venturaEffect** [cpacker/MemGPT#394]
**Describe the bug**
I'm using LM Studio with MemGPT, and as I seeing and followed some tutorials.

**To Reproduce**

On the memgpt enviroment inside the folder .memgpt:

1. I added: set OPENAI_API_BASE="http://http://localhost:1234" 
2. And set BACKEND_TYPE="lmstudio". 
3. To test if it really takes the LLM I selected on LM Studio I connected an uncensored LLM. 
4. Then I asked some unlegal stuff just for test if it is taking the LLM I'm running on the server.
5.  The funny thing is, It doesnt be the LLM selected on LM Studio because it tells me is not allowed to answer this, 
6. And second even if I changed the "human" on the config.json of the agent it still keeps selecting another human.

**Expected behavior**
It should work with the LLM selected on LM Studio

**Screenshots**
<img width="1266" alt="HERMES_MEMGPT" src="https://github.com/cpacker/MemGPT/assets/29057173/bfbc1283-c8d1-4860-a128-7c05d8cc82bd">

<img width="1273" alt="HERMES_LMSTUDIO" src="https://github.com/cpacker/MemGPT/assets/29057173/53230671-d118-46b0-a607-738554358b00">

**Additional context**

---

**How did you install MemGPT?**

- From the official package? `pip install pymemgpt`
- From source?
  - With [poetry](https://github.com/cpacker/MemGPT#development)?
  - With `git clone git@github.com:cpacker/MemGPT.git` and `pip install -r requirements.txt`?

**Your setup (please complete the following information)**

- Your OS is Windows

- Running it on Powershell

- Latest Python version

-  If you installed with `pip install pymemgpt`:
  - `pymemgpt` version (run `pip list | grep pymemgpt`)

Yes

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- The exact model you're trying to use (link to the HuggingFace page you downloaded it from) 

TheBloke(Nous Heremes 13B q5_0 gguf

  - We need the EXACT model name, including quantization scheme, e.g.: `dolphin-2.1-mistral-7b.Q6_K.gguf` (not just `dolphin-2.1-mistral`)
  
TheBloke/Nous-Hermes-13B-GGUF/Nous-Hermes-13B.Q5_0.gguf

- The local LLM backend you are using (web UI? LM Studio?)

LM Studio

- Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)

Local computer

- Your hardware for the MemGPT command (same computer as the local LLM backend?)

yes

- The full output (or as much as possible) of where the LLM is failing
<img width="1266" alt="HERMES_MEMGPT" src="https://github.com/cpacker/MemGPT/assets/29057173/5198a74c-7a78-4839-814f-ea145dfd40e2">

  - If you can include screenshots, even better!

**Comment by venturaEffect** [comment]
I saw the url was wrong now updated to: set OPENAI_API_BASE="http://localhost:1234"

Even after making this. It doesn't take the models of the LM Studio. Not sure which model is but not the one I'm selecting on LM Studio. Tried by putting an uncesored. No success it doesn't answer me, telling it violates the guidelines. Tried with code llama instruct... and also not working. Just asking for a simple python script and it doesn't know how to write code. Weird...

**Comment by cpacker** [comment]
@venturaEffect sorry for the delayed response! I don't see anything wrong with your setup but the workflow for local LLMs has also been updated since your post: https://memgpt.readthedocs.io/en/latest/lmstudio/

You can check if MemGPT is using the LM Studio backend by watching the server logs in LM Studio - if you see output happening while "Thinking...." is happening on the MemGPT side, it means it's using LM Studio (and the model selected in LM Studio). LLMs can behave weirdly, even an "uncensored LLM" can still act censored depending on how it was trained / prompted.
