### ISSUE TITLE
Migrate pytest tests to automatically setup local postgres server

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#403]
We've been using a hosted server for testing, but it'll be easier for contributors to run tests if we automatically setup postgres via #393

**Comment by Shoumik-Gandre** [comment]
Hello @sarahwooders

Does this mean that when we run pytest, the command should create a docker container that will spin up a postgress database?

If so, I would like to work on it.

**Comment by cpacker** [comment]
@Shoumik-Gandre check https://github.com/cpacker/MemGPT/tree/main/db for a dockefile
