### ISSUE TITLE
No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by Slyefox** [cpacker/MemGPT#406]
I'm very new at this.

Microsoft Windows 10 Pro 10.0.19045 Build 19045
13th Gen Intel(R) Core(TM) i7-13700K, 3400 Mhz, 16 Core(s), 24 Logical Processor(s) 64GB RAM
MSI Geforce RTX 4060Ti 16 GB

Using Miniconda 3 64 Bit Anaconda Powershell Prompt. I was attempting to install MemGPT to run with local models and webui by following a MemGPT tutorial by Matthew Berman, who was using a Mac. I successfully loaded oobabooga and textgen webui. I'm using the Airoboros 13B quantized model and all of that is functioning smoothly. I ran into one bump during the first part of the MemGPT installation due to using import instead of set during the API setup but I figured that one out. Conda is created and active but now I'm receiving the following error after running pip install -r requirements.txt:

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Where am I going wrong? I'm including screenshots of everything I've done...

![MemGPT 1](https://github.com/cpacker/MemGPT/assets/150399013/f2494279-8809-4f3c-9bcd-fba35301ad35)
![MemGPT 2](https://github.com/cpacker/MemGPT/assets/150399013/b4ceeb69-91a5-4e78-be51-c74bc022b88f)

**Comment by sarahwooders** [comment]
You should do `pip install -e .'[local]'` instead. We also have a python package now so you can just do `pip install 'pymemgpt[local]'`

I recommend looking at the docs if you are trying to run the local models, as some of the tutorial are out of date https://memgpt.readthedocs.io/en/latest/local_llm/

**Comment by sarahwooders** [comment]
Fixed documentation in #516
