### ISSUE TITLE
How to launch docqa example with embeddings?  Sample code broken.

### ISSUE THREAD

**Issue by ProgramItUp** [cpacker/MemGPT#408]
**Describe the bug**
The instructions for running docqa need to be updated `MemGPT/memgpt/personas/examples/docqa/README.md`

**To Reproduce**
After following the instructions, the run command:
`python3 main.py --archival_storage_faiss_path=<ARCHIVAL_STORAGE_FAISS_PATH> --persona=memgpt_doc --human=basic`
in MemGPT/memgpt/personas/examples/docqa/README.md 
Causes the error: 
`Warning: Running legacy run command. You may need to `pip install pymemgpt[legacy] -U`. Run `memgpt run` instead.`
Following the suggestion to `pip install pymemgpt[legacy] -U` did not help.

I tried: 
`memgpt run archival_storage_faiss_path=memgpt/personas/docqa/llamaindex-api-docs --persona=memgpt_doc --human=basic`
but got the error
`Got unexpected extra argument (archival_storage_faiss_path=memgpt/personas/docqa/llamaindex-api-docs)`

**Expected behavior**
Execute the docqa example.

**How did you install MemGPT?**
pip install pymemgpt
pip install pymemgpt[legacy] -U

- Your OS (Linux, MacOS, Windows)
Linux 
- Your python version (run `python --version`)
Python=3.11
pymemgpt           0.1.18

**Comment by ProgramItUp** [comment]
After reading the cli documentation it looks like the correct new way should be to use the 
`memgpt load index`

I tried 
`memgpt load index --dir /home/me/code/MemGPT/memgpt/personas/examples/docqa/llamaindex-api-docs/ --name llama_index_embeddings`
but got the error:
`FileNotFoundError: [Errno 2] No such file or directory: '/home/marc/code/MemGPT/memgpt/personas/examples/docqa/llamaindex-api-docs/org/docstore.json'`

**Comment by sarahwooders** [comment]
Sorry for the delayed response - if you have a cached faiss file, that's not supported for `memgpt load`. What data are you trying to load into MemGPT?
