### ISSUE TITLE
MemGPTAgent error in messages_processed_up_to_idx calculation 

### ISSUE THREAD

**Issue by anjaleeps** [cpacker/MemGPT#409]
**Describe the bug**
I'm using MemGPT 0.1.18 for an Autogen integration task and I'm seeing the following error. After the initial user message, MemGPTAgent doesn't pick up new user messages and instead replies by saying something along the lines of no new messages from the user. The message gets added to the agent's `chat_messages` dict but doesn't get picked up as a new message inside the `_generate_reply_for_user_message` method in MemGPTAgent class when sending the reply. When debugging, I saw that the `new_messages` list counts the response from Open AI as well as an additional system message when calculating the new `messages_processed_up_to_idx`. 

**To Reproduce**
I got this issue when trying to run this code with human input mode set to `ALWAYS` in user proxy. 
[https://github.com/tylerprogramming/ai](https://github.com/tylerprogramming/ai)

**Expected behavior**
Correctly detect when there are new user messages.

**How did you install MemGPT?**

- Installed with `pip install pymemgpt`
- Later ran `pip install pymemgpt -U --pre` to get the latest version.

**Setup**

- OS (Windows)
- Where you're trying to run MemGPT from
  - Pycharm
- Your python version: 3.11

**Comment by cpacker** [comment]
Hi @anjaleeps - so sorry for the delayed response here! I believe this bug should be patched in the latest version(s) of MemGPT (the summarization logic was rewritten a few weeks ago).

Please feel free to reopen this issue / create a new issue if you're still having this problem (or ping us on the MemGPT Discord server on the #support channel).
