### ISSUE TITLE
Context window exception after 8192 tokens

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [cpacker/MemGPT#428]
Using: text-generation-webui
Model: ehartford_dolphin-2.2.1-mistral-7b - not quantized
Wrapper: airoboros-l2-70b-2.1
Installed: using pip install -r requirements
OS: Windows 10
Shell: cmd.exe
Python: Python 3.11.3
pymemgpt installed: yes
Hardware: 12th Gen i7 64GB/RAM, TWO GPU's, both are RTX3060 12GB RAM
LLM and MemGPT on same system

Name: pymemgpt
Version: 0.2.1
Summary: Teaching LLMs memory management for unbounded context
Home-page:
Author: Charles Packer
Author-email: contact@charlespacker.com
License: Apache License
Location: C:\Users\rjx316\.conda\envs\memgpt\Lib\site-packages
Editable project location: E:\MemGPT
Requires: demjson3, llama-index, openai, prettytable, pymupdf, pytz, questionary, setuptools, tiktoken, tqdm, typer

Prior to this update I was receiving an error that explained that the token count had been exceeded (i,e..  Exception: Request exceeds maximum context length (8309 > 8192 tokens)

In previous versions of memgpt this was recoverable by answering Yes to a retry. Now in this update the exception is not recoverable. Once the token limit is exceeded an error is produced and retrying does not work, it repeats  and at this point the agent is trashed and forever unusable. After about 10-15 minutes of conversation this happens to every agent. I have created several to test and see if it is consistent and it is easily repeatable.

![context_exception](https://github.com/cpacker/MemGPT/assets/123831682/5291950c-b13b-4226-9d6a-9a1df2fd8616)

**Comment by fungnoth** [comment]
Same issue. Here's a quick fix
Go to memgpt/memory.py line 144.
Or search for `messages=message_sequence,` in the file
Add `context_window=context_window,` after that. 

So it should look like
`    response = create(
        model=model,
        messages=message_sequence,
        context_window=context_window,
 )`
