### ISSUE TITLE
Websocket server/client not functional

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [cpacker/MemGPT#445]
Using: text-generation-webui
Model: ehartford_dolphin-2.2.1-mistral-7b - not quantized
Wrapper: airoboros-l2-70b-2.1
Installed: using pip install -r requirements
OS: Windows 10
Shell: cmd.exe
Python: Python 3.11.3
pymemgpt installed: yes
Hardware: 12th Gen i7 64GB/RAM, TWO GPU's, both are RTX3060 12GB RAM
LLM and MemGPT on same system

When attempting to test the websocket server and client I am unable to successfully make it work either with an existing agent or a new one.

First:  Attempting to use an existing agent..
With a setting of LOAD_AGENT = "agent_10"     (confirmed agent does exist, I can use it from the CLI with 'memgpt run')

Results:
__________________________________Server
![image](https://github.com/cpacker/MemGPT/assets/123831682/3f462fcf-8f3a-478a-87e7-e3c745800de2)
__________________________________Client
![image](https://github.com/cpacker/MemGPT/assets/123831682/fbb52bc2-038a-4971-9283-bc03ecf0ed70)

**Note: I am using a local LLM

Second: Attempting to allow creation of a new agent..
With a setting of LOAD_AGENT = None

Results:
__________________________________Server
![image](https://github.com/cpacker/MemGPT/assets/123831682/b9b1b12a-db12-4364-82f0-681c73e54d9a)
__________________________________Client
![image](https://github.com/cpacker/MemGPT/assets/123831682/487ab7cd-3445-4e62-b8cf-06cf2f0371f0)

Note: An Agent does get created however looking at the config file I can see the parameters are entirely wrong for my local LLM even if it had worked - this would be another failure
![image](https://github.com/cpacker/MemGPT/assets/123831682/62fcaeed-39d8-4bae-82b2-8e9d90bffe0a)

Looking at the implementation of websockets I find myself wishing that it didn't work this way. I think it would be nice if things began as normal with 'memgpt run' and after selecting an agent just have a question posed as to whether to continue with the CLI or redirect to a websocket connection. I realize that doesn't facilitate the ability to create a new agent on-the-fly but I personally can't see a need for that anyway but that's just me. The current strategy will suffice however as you can see, currently I cannot get what is implemented to function at all.

**Comment by cpacker** [comment]
I think this is because a big PR that got merged in after the websockets PR broke the websockets PR, will patch asap.

**Comment by cpacker** [comment]
Also the initial websocket protocol is very alpha and is expected to change to support more functionality

**Comment by cpacker** [comment]
Patched in https://github.com/cpacker/MemGPT/commit/e55efae44f29e38c6791d4e39427c244102ceb79, however there is another PR incoming that you will require for backwards compatibility with old configs (so I could recommend waiting until the next tag to upgrade).

**Comment by TheOnlyWiseJEDI** [comment]
tyvm
