### ISSUE TITLE
LanceDB Integration

### ISSUE THREAD

**Issue by PrashantDixit0** [cpacker/MemGPT#456]
Only Postgres is integrated with MemGPT.

To provide flexibility with other vectorDBs, I have integrated LanceDB as a vectorDB #455

**Comment by PrashantDixit0** [comment]
Merged LanceDB Integration

**Comment by oderwat** [comment]
I used configure to enable lancedb but on usage I only get "Table with name lancedb_tbl not present". What do we need to do, to make this actually work? The docs don't tell about additional steps.

**Comment by PrashantDixit0** [comment]
At what step you are getting this error?

**Comment by oderwat** [comment]
When it tries to save something to the storage. It also totally panics when I `/memory`.

**Comment by PrashantDixit0** [comment]
Ok I'll look into it and add support of it in docs asap. Once done I'll inform you

**Comment by PrashantDixit0** [comment]
Added Bug Fix, once this is merged you can test it

**Comment by PrashantDixit0** [comment]
@oderwat You can try once this PR is merged, for me it worked seemlessly now.
