### ISSUE TITLE
presets error 

### ISSUE THREAD

**Issue by Mocro020** [cpacker/MemGPT#459]
trying to run memgpt with autogen in 3.10 canda env and get a import error at presets. if i add __init__.py in presets folder it lets me import presets but wont let me use any presets.. I am far from a pro to tell you forget something so can you please help me fix the preset  issue :)

O i also installed with pip and than tried source and also deleted env and created a new one

**Comment by sarahwooders** [comment]
What version of MemGPT are you using? Can you show the output of `memgpt version`?

**Comment by Mocro020** [comment]
I am running pymemgpt  0.2.3    and installed it from source now, but happens with pip and git installation

**Comment by Mocro020** [comment]
lol sorry somehow python path was gone from systemvar
