### ISSUE TITLE
Meta-question about the content sent to the LLM server.

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [cpacker/MemGPT#465]
I was looking at the content you send to the AI server.

You talk to it very humanlike, almost like to a friend, even child. I was close to expecting you to tuck the LLM in and wish it nice dreams.

Now this might come across as condescending, but that is not my intent.

Do you think, we are already there yet that an NLP AI LLM can actually comprehend that or would it handle just keywords better, ie normal user <-> computer interaction, the way it's used with stable diffusion.

**Comment by cpacker** [comment]
There is a community-contributed condensed system prompt that you can play with here: https://github.com/cpacker/MemGPT/blob/main/memgpt/prompts/system/memgpt_chat_compressed.txt

It's much more concise than the default. If you try it out and get results, let us know! Would be interested to know how well it performs compared to the lengthier version.
