### ISSUE TITLE
'content' may not be included in one message of the message list which  was sent to azure openai api  as parameters  and then the api  returned error http code

### ISSUE THREAD

**Issue by weixiu00** [cpacker/MemGPT#467]
**Describe the bug**
a message from LLM can be like this

    {
        "role":"assistant",
        "function_call":{
            "name":"send_message",
            "arguments":"{\n  \"message\": \"Sure! Here is a Python function that prints numbers from 1 to 10:\"\n}"
        }
    }

the message will be added into  the messages list which will be sent to LLM later
but 'content' is required in every mesage in the messages list

**To Reproduce**
can be reproduced occasionally after performing many steps

**Expected behavior**
veriy every messge added into the message list?

**Comment by cpacker** [comment]
Thank you for catching this.

I believe this patch should solve the problem for Azure:
https://github.com/cpacker/MemGPT/blob/main/memgpt/openai_tools.py#L186-L190
