### ISSUE TITLE
I am getting the following error.   memgpt_agent=presets.use_preset(presets.DEFAULT_PRESET, model='gpt-4', persona=persona, human=human, interface=interface, persistence_manager=persistence_manager, agent_config=llm_config)                  ^^^^^^^^^^^^^^^^^^ AttributeError: module 'memgpt.presets' has no attribute 'use_preset'

### ISSUE THREAD

**Issue by arifjahangir2413** [cpacker/MemGPT#475]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

---

**How did you install MemGPT?**

- From the official package? `pip install pymemgpt`
- From source?
  - With [poetry](https://github.com/cpacker/MemGPT#development)?
  - With `git clone git@github.com:cpacker/MemGPT.git` and `pip install -r requirements.txt`?

**Your setup (please complete the following information)**

- Your OS (Linux, MacOS, Windows)
- Where you're trying to run MemGPT from
  - Terminal? PowerShell? cmd.exe?
- Your python version (run `python --version`)
-  If you installed with `pip install pymemgpt`:
  - `pymemgpt` version (run `pip list | grep pymemgpt`)
- If you installed from source:
  - Your current git commit (run `git describe --tags`)

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- The exact model you're trying to use (link to the HuggingFace page you downloaded it from)
  - We need the EXACT model name, including quantization scheme, e.g.: `dolphin-2.1-mistral-7b.Q6_K.gguf` (not just `dolphin-2.1-mistral`)
- The local LLM backend you are using (web UI? LM Studio?)
- Your hardware for the local LLM backend (local computer? operating system? remote RunPod?)
- Your hardware for the MemGPT command (same computer as the local LLM backend?)
- The full output (or as much as possible) of where the LLM is failing
  - If you can include screenshots, even better!

**Comment by sarahwooders** [comment]
Can you share what version you are on? You can see it with `memgpt version`.

**Comment by techriffic** [comment]
getting the same error, used pip install pymemgpt
pip list | grep pymemgpt
pymemgpt                 0.2.3
python --version
Python 3.11.6

lmstudio macos sonama m1 16gb

**Comment by 9740155** [comment]
When importing, use: 
`import memgpt.presets.presets as presets`
That will resolve that issue. The next issue is another parameter for the agentconfig, which is hard to locate examples. I'm still trying to figure that out

**Comment by techriffic** [comment]
thank you, yes i found out about import memgpt.presets.presets as presets
and used it but script still wont work, is there an update on memgpt or autogen? how come everyone was using the script from before but no we have to use import memgpt.presets.presets as presets
and still fix another issue

**Comment by jordanknightbr** [comment]
Hello guys!
Just install the version 0.1.6. It's worked for me.

`pip install pymemgpt==0.1.6`

**Comment by techriffic** [comment]
i created new conda env and used 0.1.6 but still no luck, tried both 
import memgpt.presets.presets as presets
mport memgpt.presets as presets

**Comment by lhy4430** [comment]
pymemgpt           0.2.4
and I have also meet the erro:  File "/home/luohanyu/test_api.py", line 33, in <module>
    memgpt_agent = presets.use_preset(presets.DEFAULT, 'gpt-3.5-turbo', persona, human, interface, persistence_manager)
                   ^^^^^^^^^^^^^^^^^^
AttributeError: module 'memgpt.presets' has no attribute 'use_preset'

**Comment by Armanasq** [comment]
Still, I have the same problem here, tested almost with all versions
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], [line 53](vscode-notebook-cell:?execution_count=1&line=53)
     [51](vscode-notebook-cell:?execution_count=1&line=51) persona = "I am a 10x engineer, trained in Python. I was the first engineer at Uber."
     [52](vscode-notebook-cell:?execution_count=1&line=52) human = "Im a team manager at this company"
---> [53](vscode-notebook-cell:?execution_count=1&line=53) memgpt_agent=presets.use_preset(presets.DEFAULT_PRESET, model='gpt-4', persona=persona, human=human, interface=interface, persistence_manager=persistence_manager, agent_config=llm_config)
     [56](vscode-notebook-cell:?execution_count=1&line=56) if not USE_MEMGPT:
     [57](vscode-notebook-cell:?execution_count=1&line=57)     # In the AutoGen example, we create an AssistantAgent to play the role of the coder
     [58](vscode-notebook-cell:?execution_count=1&line=58)     coder = autogen.AssistantAgent(
     [59](vscode-notebook-cell:?execution_count=1&line=59)         name="Coder",
     [60](vscode-notebook-cell:?execution_count=1&line=60)         llm_config=llm_config,
     [61](vscode-notebook-cell:?execution_count=1&line=61)         system_message=f"I am a 10x engineer, trained in Python. I was the first engineer at Uber",
     [62](vscode-notebook-cell:?execution_count=1&line=62)         human_input_mode="TERMINATE",
     [63](vscode-notebook-cell:?execution_count=1&line=63)     )

AttributeError: module 'memgpt.presets' has no attribute 'DEFAULT_PRESET'
