### ISSUE TITLE
Bug: Attribute error when running main.py

### ISSUE THREAD

**Issue by sahusiddharth** [cpacker/MemGPT#476]
**Describe the bug**
AttributeError: 'Agent' object has no attribute as 'context_window'

**To Reproduce**
1. Run 
```
python3 main.py
```
2. Follow the steps, after selecting which user

**Expected behavior**

---

**How did you install MemGPT?**

Followed both `pip install pymemgpt` and  `git clone git@github.com:cpacker/MemGPT.git` and `pip install -r requirements.txt`
**Your setup (please complete the following information)**

- Your OS: Linux
- Where you're trying to run MemGPT from
  - Terminal? PowerShell? cmd.exe?
- Your python version: 3.10
-  If you installed with `pip install pymemgpt`: 0.2.2

**Comment by sarahwooders** [comment]
Instead of running `python main.py` can you try installing the latest version with `pip install -U pymemgpt` and running `memgpt run`?

**Comment by sahusiddharth** [comment]
Yes it's working 

Question: after selecting LLM inference provider, asking for override default endpoint, what should I do next? a small explanation would be greatly appreciated.

Thank-you

**Comment by sahusiddharth** [comment]
@sarahwooders Thank-you It's working now
