### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '~/.memgpt/agents'

### ISSUE THREAD

**Issue by johnsonafool** [cpacker/MemGPT#479]
**Describe the bug**
While using the example, create_autogen_memgpt_agent return FileNotFoundError: [Errno 2] No such file or directory: '~/.memgpt/agents', I wonder if it's related to agents not properly set during new version of `MemGPT` was released

```py
coder = create_autogen_memgpt_agent(
        "MemGPT_coder",
        persona_description="I am a 10x engineer, trained in Python. I was the first engineer at Uber (which I make sure to tell everyone I work with).",
        user_description=f"You are participating in a group chat with a user ({user_proxy.name}) and a product manager ({pm.name}).",
        interface_kwargs={"debug": DEBUG},
    )
```

**Expected behavior**
Successfully run the example code, I inspected this error in local development first, and then I ran the exact same code provided on [memgpt_coder_autogen.ipynb - Colaboratory](https://colab.research.google.com/github/cpacker/MemGPT/blob/main/memgpt/autogen/examples/memgpt_coder_autogen.ipynb) and still gave me same error

**How did you install MemGPT?**

`pip install pymemgpt`

**Your setup (please complete the following information)**

- Your OS (Linux, MacOS, Windows)
  - MacOS
- Where you're trying to run MemGPT from
  - MacOS Terminal
- Your python version (run `python --version`)
  - 3.11.5
-  If you installed with `pip install pymemgpt`:
  - 0.2.3

**Comment by cullenbohannon** [comment]
I guess one would expect memgpt dependencies to be installed, but that doesn't happen properly in a virtual environment

Try `pip install transformers torch`
Then run `memgpt configure` first and follow up on any other missing dependencies.

You might also need to set your `OPENAI_API_KEY = "xxxx"` before running the config.
After the config is successful, you should be able to `memgpt run`, which will create an agent if the setup was successful.

Hope it helps.
