### ISSUE TITLE
MEMGPT Extraordinarily slow - if it works at all

### ISSUE THREAD

**Issue by TheOnlyWiseJEDI** [cpacker/MemGPT#482]
Installed uisng:

git pull
pip install -e .

Using:   the latest webui with openai extension
MemGPT version:   0.2.3

When I use my LLM via the webui html interface it's super zippy. After saying 'hello' I get a response within 3 seconds. Likewise I have a discord bot that connects to the openai API of webui and it too is super fast (same response time)

When I start MemGPT using 'memgpt run' and then press enter for the first message the response time is 7 minutes. Sometimes a touch less. The next thing I type can take 2 to 5 minutes before a response comes back.

I'm not sure what further detail you need I tried to make a video for this but it on that effort I couldn't even get a response after pressing enter for the first message and I gave up. It's painfully slow.

I tried using an existing agent, tried creating a new agent. The results are the same either way. I tried to edit the config.json and remove the wrapper specification to see if that made a difference but it was the same. I tried this because this lag reminded me of what happened if I created an agent and did not specify a wrapper. A super long delay.

Once it does respond with a first message and I type something else the delays in communication are the same.

Please let me know what else I can tell you that will help. At the moment I can't even use MemGPT at all.

In the pic below you see 4 lines  at the bottom you see the webui output window indicating output times. The first line is 3 seconds and that is the result of typing 'hello' into the webui html chat window. The following 3 lines are the response times from Step 1. pressing enter for the first message 2. Saying Hi, how are you?  3. Saying "I am doing fine" after it responded asking how I am.

![image](https://github.com/cpacker/MemGPT/assets/123831682/c9bbe7e7-e242-40ac-bbff-4c437b7f3129)

**Comment by ibenitez** [comment]
It happens exactly the same.

With OpenAI API: 8341.07 ms
With MemGPT: 421544.73 ms ~ 50x slow

I running local LLM with llama-cpp-python

![image](https://github.com/cpacker/MemGPT/assets/794621/e8e5fff6-a14e-47e0-9d09-23b0385a0c0b)
