### ISSUE TITLE
No module named pytest

### ISSUE THREAD

**Issue by sahusiddharth** [cpacker/MemGPT#486]
**Describe the bug**
There is no module name pytest which is being imported in test_storage.py

**To Reproduce**
1. Want execute test_storage.py 
2. Running Command
```
python3 tests/test_storage.py
```

**How did you install MemGPT?**

- From the official package?
 `pip install pymemgpt`

**Your setup (please complete the following information)**

- Your OS 'Linux'
- Where you're trying to run MemGPT from 'Terminal'
- Your python version '3.10'
-  If you installed with `pip install pymemgpt`: '0.2.3'

**Comment by sarahwooders** [comment]
For the developer environment, we recommend using poetry. 

```
pip install poetry 
poetry install -E dev (-E whatever else you need) 
poetry run pytest tests/test_storage.py
```
