### ISSUE TITLE
The LangChain library has ConversationBuffer Memory, ConversationSummary Memory, and ConversationBufferWindow Memory. Kindly share how your implementation of memory differs from theirs

### ISSUE THREAD

**Issue by KartikeyBartwal** [cpacker/MemGPT#50]

**Comment by cpacker** [comment]
Those all correspond to different types of conversational context (refer to section 2.1 in the paper: https://arxiv.org/pdf/2310.08560.pdf). In the MemGPT repo, we implement a recursive summary for conversational context, but conversational context is just one part of memory in MemGPT.

**Comment by KartikeyBartwal** [comment]
I see, thank you for providing clarity.
