### ISSUE TITLE
Grammar does not update with new functions

### ISSUE THREAD

**Issue by cpacker** [cpacker/MemGPT#526]
**Describe the bug**

Grammar is hardcoded to the base functions - if you use the new [custom functions](https://memgpt.readthedocs.io/en/latest/functions/), you cannot use [grammar-based sampling](https://github.com/cpacker/MemGPT/blob/main/memgpt/local_llm/grammars/json_func_calls_with_inner_thoughts.gbnf) since the grammar will only allow sampling based on prior functions.

To fix we need to dynamically generate the grammar file based on the linked functions.

**Comment by jimlloyd** [comment]
I might work on this. I am currently tracing through some of the related code. I have a basic question: The grammar fie is loaded and sent with each API request to the backend LLM server, right?

And in any one call API all, only one function call can appear in the request? Is so, can't we scan the prompt, determine which (if any) function is called, and then load the grammar for that one function only?
 
Having a separate grammar per function would probably make it easier to support custom functions.

**Comment by cpacker** [comment]
> I might work on this. I am currently tracing through some of the related code. I have a basic question: The grammar fie is loaded and sent with each API request to the backend LLM server, right?

yep!

> And in any one call API all, only one function call can appear in the request? Is so, can't we scan the prompt, determine which (if any) function is called, and then load the grammar for that one function only?

generally speaking we're assuming 'auto' on the function calling, which means the LLM gets to decide which function to call, so you don't know ahead of time

**Comment by cpacker** [comment]
Assume there are the following grammar generator functions:

`generate_grammar_for_function`:

- Takes a JSON schema (for a function) as input, and outputs a partial grammar file/snippet

`generate_grammar_for_model_wrapper`;

- Takes a prompt/LLM output format, and generates a grammar for it
- Uses `generate_grammar_for_function` to enumerate the grammars for all the possible functions

Where the output format may be something like:
```json
{
  "inner_thoughts": "string",
  "function_name": "string",
  "function_params": "JSON stringified"
}
```

This can probably be inserted here:
https://github.com/cpacker/MemGPT/blob/main/memgpt/local_llm/chat_completion_proxy.py#L77-L78

Instead of:
```python
        if "grammar" in wrapper:
            grammar_name = "json_func_calls_with_inner_thoughts"
...
```

Do:
```python
        if "grammar" in wrapper:
            # model_wrapper informs you what the expect LLM output style/format is
            # functions contains the JSON schema of the functions available to the LLM
            grammar_name = generate_grammar_for_model_wrapper(model_wrapper, functions)
...
```

Then inside the individual `local_llm/*/api.py` files, you need to modify the grammar arg to be treated as a string:

Instead of:
```python
    # Set grammar
    if grammar is not None:
        request["grammar_string"] = load_grammar_file(grammar)
```

Do:
```python
    # Set grammar
    if grammar is not None:
        if grammar.endswith('.gnbf'):  # it's a file, load it
            request["grammar_string"] = load_grammar_file(grammar)
        else:  # it's the string itself, not a file
            request["grammar_string"] = grammar
```
