### ISSUE TITLE
openai version required for local llm + autogen

### ISSUE THREAD

**Issue by CoderTom314** [cpacker/MemGPT#527]
llama-index 0.8.62 requires openai <1
pymemgpt 0.2.4 requires openai<0.29.0
pyautogen 0.2.0 requires openai~=1.2

Cannot resolve dependency conflicts

**Comment by questmapping** [comment]
Same here when trying to install pyautogen and pymemgpt together
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llama-index 0.8.62 requires openai<1, but you have openai 1.3.6 which is incompatible.
pymemgpt 0.2.4 requires openai<0.29.0,>=0.28.1, but you have openai 1.3.6 which is incompatible.`

**Comment by sarahwooders** [comment]
Unfortunately we haven't upgraded to the OpenAI v1 API yet, so you need to use `pyautogen==0.1.14`. We're adding a autogen extra to specify the version to use in #530

**Comment by cpacker** [comment]
As an update to this, in a future PR we are also stripping the `openai` package so you should be able to update `autogen` as you wish and not have to worry about an `openai` version conflict with MemGPT: #534
