### ISSUE TITLE
Is VIRTUAL CONTEXT a good description of MEMGPT ?

### ISSUE THREAD

**Issue by jabogithub** [cpacker/MemGPT#53]
Just to be sure: so MEMGPT uses the principle of PAGING, that is used in Operating Systems to circumvent the limitation of RAM size, when a much larger memory size is needed? Which is called VIRTUAL MEMORY. In the case of LLMs we could call it VIRTUAL CONTEXT ?

**Comment by cpacker** [comment]
Yep that's correct!
