### ISSUE TITLE
ERRORS with memgpt load dirctory --input-files ./MemGPT-WhitePaper.pdf --name MemGPT-Whitepaper

### ISSUE THREAD

**Issue by agiletechnologist** [cpacker/MemGPT#535]
**Describe the bug**
Perform a load of MemGPT-whitepaper and name it MemGPT-Whitepaper:
`memgpt load directory --input-files ./MemGPT-WhitePaper.pdf --name MemGPT-Whitepaper`

1. table name created during load: memgpt_memgpt_whitepaper  it appears all "memgpt"s are stripped, including the name. as seen in  agent1/config.json
`"data_sources": [
        "whitepaper"
    ],`

**To Reproduce**
1. On the CLI, execute `memgpt load directory --input-files ./MemGPT-WhitePaper.pdf --name MemGPT-Whitepaper`
2. Look in the Postgresql database for table name: memgpt_memgpt_whitepaper
3. On CLI, execute `memgpt run --agent agent1`
4. /attach it lists only whitepaper select it.
5. Look in agent1/config.json
6. See error: `"data_sources": [
        "whitepaper"
    ],` 

**Expected behavior**
It should use memgpt_whitepaper as this is a legitimate name, and the memgpt should not be stripped of the name.
I should only strip the first memgpt. the second one is an actual name starting with memgpt_whitepaper

---

**How did you install MemGPT?**

- `pip install -U pymemgpt`

**Your setup (please complete the following information)**

- Your OS: Linux
- Where you're trying to run MemGPT from
  - Terminal
- Your python version: Python 3.11.2
- `pymemgpt` version: pymemgpt           0.2.4`

**Comment by sarahwooders** [comment]
Thanks for reporting this issue! This was indeed a bug with the database table listing, and should be fixed in #535.
