### ISSUE TITLE
Core memory edit: `ValueError: Content not found in human (make sure to use exact string)`

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#552]
**Describe the bug**
Error with core memory change (correcting name from "Chad" -> "Sarah")

**Please describe your setup**

- [x] MemGPT version
  - `main`
- [x] How did you install memgpt?
  - `pip install -e .` 
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)? MacOD
  - How are you running `memgpt`? bash 

**Screenshots**
```
trying first_json
💭 Updating core memory for human name...
⚡🧠 [function] updating memory with core_memory_replace
         Human
        → Sarah
Error calling function core_memory_replace: Content not found in human (make sure to use exact string)
Traceback (most recent call last):
  File "/Users/sarahwooders/repos/MemGPT/memgpt/agent.py", line 516, in handle_ai_response
    function_response_string = function_to_call(**function_args)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarahwooders/repos/MemGPT/memgpt/functions/function_sets/base.py", line 82, in
core_memory_replace
    new_len = self.memory.edit_replace(name, old_content, new_content)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sarahwooders/repos/MemGPT/memgpt/memory.py", line 98, in edit_replace
    raise ValueError("Content not found in human (make sure to use exact string)")
ValueError: Content not found in human (make sure to use exact string)

⚡🔴 [function] Error: Error calling function core_memory_replace: Content not found in human (make sure
to use exact string)
```

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [x] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`): `BAAI/bge-large-en-v1.5`
- [x] The local LLM backend you are using (web UI? LM Studio?): vLLM 
- [x] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?): GCP L4 instances

**Comment by cpacker** [comment]
I think this is just an LLM-using-functions-incorrectly error (if I'm reading it correctly).

The LLM was supposed to call:
```python
core_memory_replace(name="human", old_content="Chad", new_content="Sarah")
```

but instead called / generated JSON to call:
```python
core_memory_replace(name="human", old_content="Human", new_content="Sarah")
```
