### ISSUE TITLE
configure command corrupts api key

### ISSUE THREAD

**Issue by BabellDev** [cpacker/MemGPT#563]
**Describe the bug**
I installed pymemgpt and proceeded to run `memgpt configure`.  Next I ran `memgpt run` and I received an HTTP 401 error.  I edited the generated config file and found the openai key was corrupted:

```
[openai]
key = YOUR_API_KEY=sk-MyApiKey1234
```

I remove `YOUR_API_KEY` and it then works as expected.

**Please describe your setup**

- [ ] MemGPT version:  
  - `0.2.5`
- [ ] How did you install memgpt?
  - `pip install pymemgpt`
- [ ] Describe your setup
  - Windows
  - Anaconda Shell

**Comment by BabellDev** [comment]
Disregard, this was me being foolish with my env var.

**Comment by JMA6971** [comment]
> Disregard, this was me being foolish with my env var.

can you share how you fixed it? think I did the same
