### ISSUE TITLE
Allow arbitrary Azure deployment names

### ISSUE THREAD

**Issue by cpacker** [cpacker/MemGPT#578]
**Describe the bug**

From Discord:

> Just one minor detail the API path is hardcoded and assumes the deployment is called "gpt-4" or "whatever_is_the_model_name". If I name the deployment anything else in Azure OpenAI studio, it breaks.

**Comment by vinayak-revelation** [comment]
To give a concrete example: if my deployment name in azure is memgpt-gpt4-azure

currently memgpt resolves it to:
https://azure-vk-gpt4.openai.azure.com/openai/deployments/**gpt-4**/chat/completions?api-version=2023-07-01-preview

However the actual endpoint is:
https://azure-memgpt-gpt4.openai.azure.com/openai/deployments/**memgpt-gpt4-azure**/chat/completions?api-version=2023-07-01-preview

The stuff is bold is the problem (thanks MSFT!). So for now I just called my deployment gpt4 in azure ai studio and it worked.

**Comment by cpacker** [comment]
@vinayak-revelation I tested with custom deployment names on my Azure OpenAI account and it works fine (on https://github.com/cpacker/MemGPT/pull/594). Will close this issue when the PR is merged in.

FYI, make sure you're setting all of these variables before running `memgpt configure`:
```sh
export AZURE_OPENAI_KEY="..."
export AZURE_OPENAI_VERSION="2023-08-01-preview"
export AZURE_OPENAI_ENDPOINT="https://YOURENDPOINT.openai.azure.com"
export AZURE_OPENAI_DEPLOYMENT="mymodel"
export AZURE_OPENAI_EMBEDDING_ENDPOINT="https://YOURENDPOINT.openai.azure.com"
export AZURE_OPENAI_EMBEDDING_DEPLOYMENT="mydeployment"
```
