### ISSUE TITLE
Error with Azure OpenAI embeddings

### ISSUE THREAD

**Issue by vassilisv** [cpacker/MemGPT#588]
**Describe the bug**
The command 'memgpt load directory ...' fails with the following error:

openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

Verified embedding deployment, endpoint URL and keys are correct and set in the environment and MemGPT config.

Was able to resolve by updating the embedding_model() function in embeddings.py to use the AzureOpenAIEmbedding instead of OpenAIEmbedding (when the endpoint is Azure).

```
return AzureOpenAIEmbedding(
    model=model,
    deployment_name=deployment,
    api_key=config.azure_key,
    azure_endpoint = config.azure_endpoint,
    api_type="azure",
    api_version=config.azure_version,
)
```

**Please describe your setup**

- [x] MemGPT version
  - What is the output of `memgpt version`? (eg "0.2.4"): 0.2.6
- [x] How did you install memgpt?
  - `pip install pymemgpt`? `pip install pymemgpt-nightly`? `git clone`?: git clone
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?: MacOS
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal): Terminal

**Comment by vassilisv** [comment]
> I'm not able to find a class named AzureOpenAIEmbedding() Setup description:
> 
> 1. memgpt version: 0.2.6
> 2. Installation method: `git clone` followed by `pip install pymemgpt`
> 3. Linux OS, running on bash inside VScode, with `conda` env

It should be in the [llama_index.embeddings package](https://docs.llamaindex.ai/en/latest/examples/customization/llms/AzureOpenAI.html#) and you will need to import it in the embeddings.py file. I have llama_index v0.9.10.

```
from llama_index.embeddings import OpenAIEmbedding, AzureOpenAIEmbedding
```

Could do a PR, but not sure if this is the right way to fix this problem or just a workaround.

**Comment by maxwell-01** [comment]
I think raise a PR for this, I was playing with langchain earlier and pretty sure I had to use `AzureOpenAIEmbedding` instead of `OpenAIEmbedding` with `azure_endpoint` instead of `api_base`.

Thanks for posting this - it got memgpt working for me 👍

**Comment by vassilisv** [comment]
> I think raise a PR for this, I was playing with langchain earlier and pretty sure I had to use `AzureOpenAIEmbedding` instead of `OpenAIEmbedding` with `azure_endpoint` instead of `api_base`.
> 
> Thanks for posting this - it got memgpt working for me 👍

No problem will do a PR. 

By the way, next problem I ran into after fixing this one, was quota limit errors when creating embeddings for more than a few files. I had to update the embedding_retry_decorator in llama_index.embeddings.openai. This is probably more specific to the quota limits and number of files I am working with, so likely not an issue for most.
