### ISSUE TITLE
Tkinter input and auto-loading most recent conversation for selected profile.

### ISSUE THREAD

**Issue by MrDOSmile** [cpacker/MemGPT#60]
I've added a few changes to your program and added a few things.
Added -memgpt_run.bat (This allows you to autoload all profiles and personas, select or create a new one)
Added -personamaker.py and - profilemaker.py respectively. (They get called during the memgpt_run.bat)
Changed -main.py (Attached is a text file. I've added the code I injected in there. Just a simple tkinter window for longer context with MemGPT instead of the terminal, and auto-loading the latest conversation based off of the profile selected.)

[addedcode.txt](https://github.com/cpacker/MemGPT/files/13058903/addedcode.txt)
[memgpt_run.txt](https://github.com/cpacker/MemGPT/files/13058909/memgpt_run.txt)
[personamaker.txt](https://github.com/cpacker/MemGPT/files/13058914/personamaker.txt)
[profilemaker.txt](https://github.com/cpacker/MemGPT/files/13058915/profilemaker.txt)

**Comment by rjohnson318** [comment]
I think this would be great to add. So it autoloads everything when you launch so you do not have to separate actions.

**Comment by cpacker** [comment]
Closing because some of these features seem dated to the updated CLI. However @MrDOSmile if you think the current CLI can still be improved with additional features feel free to reopen / open a PR.
