### ISSUE TITLE
memgpt run - ModuleNotFoundError: No module named 'openai.openai_object'

### ISSUE THREAD

**Issue by relston** [cpacker/MemGPT#610]
**Describe the bug**
Running `memgpt run` results in a `ModuleNotFoundError: No module named 'openai.openai_object'` error.

**Please describe your setup**
- [x] MemGPT version
  `0.2.6`
- [x] How did you install memgpt?
  `pip3 install pymemgpt transformers torchvision`
- [x] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?
    via docker image `debian:stable-slim`
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal)
    `. venv/bin/activate && memgpt run`

**Additional context**
```dockerfile
FROM debian:stable-slim
RUN apt-get update 
RUN apt-get -y install cmake build-essential \
                pkg-config libgoogle-perftools-dev \
                git python3.11-full python3.11-venv
WORKDIR /usr/src/app
RUN python3.11 -m venv venv && \
    . venv/bin/activate && \
    pip3 install pymemgpt transformers torchvision 
RUN . venv/bin/activate && pip3 install openai
COPY entrypoint.sh /usr/src/app/entrypoint.sh
ENTRYPOINT ["/bin/bash", "/usr/src/app/entrypoint.sh"]
CMD ["memgpt", "run"]
```
Running memgpt in a container
```bash
docker run --rm -it -e OPENAI_API_KEY=${OPENAI_API_KEY} \
            -v ${PWD}/technical-notes/tools/MemGPT:/root/.memgpt \
            memgpt 
```
Output
```bash
⚡ docker run --rm -it -e OPENAI_API_KEY=${OPENAI_API_KEY} \
            -v /home/relston/text-docs:/usr/src/app/journal \
            -v ${PWD}/technical-notes/tools/MemGPT:/root/.memgpt \
            memgpt
? Would you like to select an existing agent? Yes
? Select agent: helper
config.json: 100%|██████████████████████████████████████████████████████████████| 743/743 [00:00<00:00, 652kB/s]
pytorch_model.bin: 100%|█████████████████████████████████████████████████████| 134M/134M [00:16<00:00, 8.30MB/s]
tokenizer_config.json: 100%|████████████████████████████████████████████████████| 366/366 [00:00<00:00, 287kB/s]
vocab.txt: 100%|█████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 2.08MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████| 711k/711k [00:00<00:00, 4.63MB/s]
special_tokens_map.json: 100%|█████████████████████████████████████████████████| 125/125 [00:00<00:00, 90.7kB/s]
[nltk_data] Downloading package punkt to /tmp/llama_index...
[nltk_data]   Unzipping tokenizers/punkt.zip.
Using existing agent helper
Traceback (most recent call last):
  File "/usr/src/app/venv/bin/memgpt", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/usr/src/app/venv/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/typer/core.py", line 778, in main
    return _main(
           ^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/memgpt/cli/cli.py", line 151, in run
    memgpt_agent = Agent.load_agent(interface, agent_config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/memgpt/agent.py", line 296, in load_agent
    persistence_manager = LocalStateManager.load(os.path.join(directory, filename), agent_config)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.11/site-packages/memgpt/persistence_manager.py", line 52, in load
    data = pickle.load(f)
           ^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'openai.openai_object'
```

**Comment by relston** [comment]
If I start a band new session without prior configuration it seems to work.
Perhaps there is an incompatibility with configs generated from an earlier version (from a month ago)?

**Comment by mruderman** [comment]
I am having a similar issue (also after upgrading from an older version). This is for v0.27 under Ubuntu 22.04.
@relston were you able to find a workaround to get your old agent to work again? I'm kicking myself for not backing up the last version.

**Comment by mruderman** [comment]
I tried the agent I had used up through 0.2.4 on 0.2.5 and 0.2.6. Does not work on 0.2.5 or 0.2.6. For me, looks like 0.2.4 is the last version that works. @relston can you check your logs to see if your last working version was also 0.2.4 (or at the very least that might the most recent version you can upgrade to if your below that and still need your old agent).

**Comment by relston** [comment]
@mruderman I looked back, and the last version I had working was `0.2.3`. I have only recently come back to this until recently (using `0.2.6` now), where I experienced the above issue after upgrading. Based on your observations I would guess `0.2.5` introduced some breaking change somewhere in the configs.

I ended up backing up my config folder, rebuilding a new config (`memgpt config`), and manually copying over the presets, system_prompts, humans, personas, etc. 

Still needed to create a fresh agent though 🙁

**Comment by cpacker** [comment]
Sorry about this bug @relston @mruderman! I'll try to add a patch for it ASAP.

Basically what's happening is some old save files use the openai library, which we stripped as a core dependency to make integrations with other libraries easier. I'm surprised that this error is popping up though since openai should still get installed via the llama-index dependency. If either of you are on discord, could you DM me a zip file of an agent that's corrupted for you? (the folder inside `~/.memgpt/agents`, eg `~/.memgpt/agents/corrupted_agent`)

**Comment by mruderman** [comment]
Thanks @cpacker so very appreciated! I'll send a zip file now to you on Discord.
