### ISSUE TITLE
Persona exceeds 2000 characters

### ISSUE THREAD

**Issue by sanegaming** [cpacker/MemGPT#612]
**Describe the bug**
When I create a persona I can edit the file and fill it up as big as I like, then use memgpt run --persona superbigpersona and it loads the agent. However, then if you ask it to modify the person you get a 2000 character exceed error and the function fails. 

I would expect either the memgpt run command to not allow you to run with error message saying its too large or present a warning asking for confirmation to continue anyways, if you do continue and then later on want to use this function there is not an easy way to reduce the persona length.

**Please describe your setup**

- [ ] MemGPT version
  - 0.2.7
- [ ] How did you install memgpt?
  - Git clone, with the poetry local and server install 
- [ ] Describe your setup
  - What's your OS (Windows/MacOS/Linux)?  Ubuntu 22.04
  - How are you running `memgpt`? (`cmd.exe`/Powershell/Anaconda Shell/Terminal) Terminal / tmux / api

**Screenshots**
N/a

**Additional context**
Can provide more if needed, pretty easy to reproduce. Just add to ANNA and then ask anna to update their name.

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [ ] The exact model you're trying to use (e.g. `dolphin-2.1-mistral-7b.Q6_K.gguf`) OpenHeremes-2.5B-Q6_k
- [ ] The local LLM backend you are using (web UI? LM Studio?) Ollama
- [ ] Your hardware for the local LLM backend (local computer? operating system? remote RunPod?) Ubuntu Server / local to ollama

**Comment by cpacker** [comment]
@sanegaming thanks for this issue

#695 is related, but I don't think it completely does all the UX you're thinking of (instead if only handles persona files that are too long on first load)

However, I think that may be enough? Since the persona files are only read once on init anyways

If you think this is enough lmk and I'll close this issue

**Comment by sanegaming** [comment]
> @sanegaming thanks for this issue
> 
> #695 is related, but I don't think it completely does all the UX you're thinking of (instead if only handles persona files that are too long on first load)
> 
> However, I think that may be enough? Since the persona files are only read once on init anyways
> 
> If you think this is enough lmk and I'll close this issue

Sorry for the delay, I do agree that probably is enough. How is this handled on the API when creating an agent though? Is there a error response for length too long or something?

**Comment by cpacker** [comment]
> > @sanegaming thanks for this issue
> > #695 is related, but I don't think it completely does all the UX you're thinking of (instead if only handles persona files that are too long on first load)
> > However, I think that may be enough? Since the persona files are only read once on init anyways
> > If you think this is enough lmk and I'll close this issue
> 
> Sorry for the delay, I do agree that probably is enough. How is this handled on the API when creating an agent though? Is there a error response for length too long or something?

I haven't tested it but I think what will happen is the ValueError will be returned via a 500 or potentially 4XX on the inputs.

(Going to close this for now)
