### ISSUE TITLE
Missing imports for llama_index loaders

### ISSUE THREAD

**Issue by cpacker** [cpacker/MemGPT#614]
**Describe the bug**

Potential missing imports related to llama_index ([discord link](https://discord.com/channels/1161736243340640419/1182085762506821642/1182085958284361869)):
- html2text
- docx2txt

Possible issue on import naming? Need to check against llama-index version pinned:

```
File "H:\MemGPT\memgpt\cli\cli_load.py", line 116, in load_webpage
    from llama_index import SimpleWebPageReader
ImportError: cannot import name 'SimpleWebPageReader' from 'llama_index' (C:\Programs\Python\Python310\lib\site-packages\llama_index\__init__.py)
```
```
- from llama_index import SimpleWebPageReader
+ from llama_index.readers import SimpleWebPageReader
```

**Comment by OTR** [comment]
@cpacker Please re-open this Issiue, it wasn't fixed yet

# GIVEN

## My environment

**Python version: 3.11.7**

I installed latest **version of MemGPT** with commands:

```sh
mkdir test_fix_llama_import
cd test_fix_llama_import
python -m venv .
Scripts\activate
pip install git+https://github.com/cpacker/MemGPT.git
pip install transformers torch psycopg
```

PIP output, it say it cloned the repository **up to this commit:** 
https://github.com/cpacker/MemGPT/commit/f88f930354c1cc5c771100d6b7b94df46c91bd85

```sh
pip install git+https://github.com/cpacker/MemGPT.git
Collecting git+https://github.com/cpacker/MemGPT.git
  Cloning https://github.com/cpacker/MemGPT.git to c:\users\user\appdata\local\temp\pip-req-build-t43j4mwv
  Running command git clone --filter=blob:none --quiet https://github.com/cpacker/MemGPT.git 'C:\Users\User\AppData\Local\Temp\pip-req-build-t43j4mwv'
  Resolved https://github.com/cpacker/MemGPT.git to commit f88f930354c1cc5c771100d6b7b94df46c91bd85
```

Output of **pip freeze** :

https://gist.github.com/OTR/5dfa8b0c1aa9d8e2f911ffe769c6981b

# WHEN

I try to use MemGPT CLI with arguments `load webpage`

```sh
$ memgpt load webpage --urls https://llamaindex.ai --name llama-docs
```

# THEN

It throws an Exception:

```python
\....\site-packages\memgpt\cli\cli_load.py", line 215, in load_webpage
    from llama_index import SimpleWebPageReader
ImportError: cannot import name 'SimpleWebPageReader' from 'llama_index'
```

pointing at that line of code: https://github.com/cpacker/MemGPT/blob/f88f930354c1cc5c771100d6b7b94df46c91bd85/memgpt/cli/cli_load.py#L215

Full **traceback** listing: https://gist.github.com/OTR/7cd91ca300f44e99d3b655483b230639

## Docs

Also, please provide some documentation for CLI and for docs on web site https://memgpt.readme.io/

With examples of OPTIONS for `--name` and for `--urls`

I am getting a program crash but I don't even know how to correctly use this command.

Is it right or not?

`$ memgpt load webpage --urls https://docs.llamaindex.ai --name llama-index-docs`

![image](https://github.com/cpacker/MemGPT/assets/49165533/d5855100-4333-4ba2-98c3-3b79cf9019ab)
