### ISSUE TITLE
Azure OpenAI support

### ISSUE THREAD

**Issue by tyoh-love** [cpacker/MemGPT#63]
It would be wonderful if you could add the Azure OpenAI as option.

We are on the path of developing the elderly care soft  robots using  Azure AI services like Prompt Flow, and found the MemGPT could evolve the care robot as emotion support level with long term  human  interaction !!!!

Https://hyodol.com

**Comment by MrXandbadas** [comment]
Isnt this just changing some env variables to make openai completions to the Azure endpoints?

Your work sounds amazing! I can't wait to see where it goes!

**Comment by cpacker** [comment]
Hi @tyoh-love, we just added Azure support in the latest commit, see the extra Azure steps here: https://github.com/cpacker/MemGPT#running-memgpt-locally.

We were unable to test it, so if you try it and it doesn't work, please let us know here and we'll patch it.

**Comment by tyoh-love** [comment]
it works!!   
one minor thing : AZURE_OPENAI_ENDPOINT means full api endpoint in Azure. 
It would be better to rename it as AZURE_OPENAI_APIBASE

Thank you!!!
