### ISSUE TITLE
Does embedding api is forced?

### ISSUE THREAD

**Issue by lucasjinreal** [cpacker/MemGPT#640]
Could be optional?

**Comment by sarahwooders** [comment]
What do you mean by its forced? MemGPT needs a way to compute embeddings to support vector search over archival memory.

**Comment by cpacker** [comment]
You can also use the "local" option to compute embeddings locally, so nothing leaves your machine. Going to close this issue since I assume this is what you meant, but feel free to reopen if you don't understand / we misunderstood.
