### ISSUE TITLE
PydanticUserError with latest pymemgpt and pyautogen with Azure Open AI

### ISSUE THREAD

**Issue by ompanda** [cpacker/MemGPT#659]
raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@mo

**Comment by cpacker** [comment]
Can you provide more details?

- Azure version
- pymemgpt version num. and install method (pip? git?)
- pyautogen version num. and install method
- full stack trace

Also, does this error happen when using the pinned version of pyautogen in pyproject.toml? (=0.2.0)

**Comment by ompanda** [comment]
issue got resolved by upgrading langchain to latest version
