### ISSUE TITLE
Question: database size

### ISSUE THREAD

**Issue by tytung2020** [cpacker/MemGPT#68]
Just a question, does the long context technique here includes the size of outside database that it connects to (via the method shown in the example)?
Not issue, just a question.

**Comment by cpacker** [comment]
MemGPT has access to data you give it in databases. When it wants to read the contents of this data, it has to page it in via function calls. These function calls are paginated (in the functions we give provide in this repo), so data gets pulled into LLM context in chunks.

**Comment by kyleboddy** [comment]
I found this answer and the documentation a bit unclear - say my DB dump file is 1 TB. Is that too large / ineffective at its size? 200 GB? 500 GB?

**Comment by henriqueccapozzi** [comment]
Nice question @kyleboddy 

Giving my cents on this topic,

The function that loads the database get all the data from all the found tables and put it into memory, so you'll likely need to have as much RAM as the data you want with some added value that I can't tell how big I'll need to be

references
https://github.com/cpacker/MemGPT/blob/849782dd82b58c61c61997521c4e5d8a27adcdd4/memgpt/utils.py#L275
https://github.com/cpacker/MemGPT/blob/849782dd82b58c61c61997521c4e5d8a27adcdd4/memgpt/utils.py#L280-L282
