### ISSUE TITLE
Persona Exceeding memory

### ISSUE THREAD

**Issue by tomsib2001** [cpacker/MemGPT#7]
I wanted to provide a quite extensive persona and apparently it is too much:

ValueError: Edit failed: Exceeds 2000 character limit (requested 7194). Consider summarizing existing core memories in 'persona' and/or moving lower priority content to archival memory to free up space in core memory, then trying again.

My persona includes a quite large example of what I want the agent to give me when I ask for a final answer. How can I put this example in archival memory from the start?

**Comment by akrabulislam** [comment]
Great idea

**Comment by cpacker** [comment]
@tomsib2001 you can modify the constants here to allow for larger personas: https://github.com/cpacker/MemGPT/blob/main/memgpt/constants.py#L18-L20

However if you're using base gpt-4 with only 8k tokens I wouldn't recommending increasing it too much. Instead (like it seems you're doing) I would recommend putting data into archival, then telling MemGPT in the first message (or even inside the persona file) that eg "there's data in archival that has X and I want to do Y with it".

What's your ideal workflow for your setup/data? We can try to streamline the insert into archival process to make it more intuitive.

**Comment by tomsib2001** [comment]
I'm not sure how to answer your question directly so I'll give you as many details as I can:
I wanted to try to have MemGPT infer some properties of some code (sorry, I have to stay vague: imagine for example I want to produce a list of functions present in the code and a description of their behavior, in a well-defined format like json or csv). I have already tried directly inferring these properties from the code with a custom prompt, but I feel like an agent operating with memory would be more effective:
- I could give it a larger piece of code;
- I could break down the tasks into several steps and it could keep track in its memory of which tasks have been done, for which parts of the code;
- I can give it one, or many examples of this task being done on some pieces of code so that if it's unsure what to do it can look up this or these examples

However, my first trials (with GPT4 8k)  have proven to be much too costly; as amazing as MemGPT is, it consumes a lot of chatGPT tokens even for the most mundane internal calls. I'm hopin some day I can try it on a local LLama-2, when I get around to buying GPUs...

**Comment by cpacker** [comment]
Hey @tomsib2001, I'm going to close this since it seems like the solution is to preload (or expand the persona limit in the constants).

If you want help setting this code + MemGPT setup (or even running on local LLMs), feel free to open a new issue or discussion and I'm happy to help out (or ping me on Discord).
