### ISSUE TITLE
can not find the file

### ISSUE THREAD

**Issue by legaltextai** [cpacker/MemGPT#70]
when try to load the txt file, it can not find it. defaults to 'basic.txt'? 

```
raise FileNotFoundError(f"No file found for key {key}, path={file_path}")
FileNotFoundError: No file found for key basic, path=/Users/home/Downloads/MemGPT/memgpt/humans/examples/basic.txt
```

**Comment by cpacker** [comment]
When you run main.py, it will look for the persona (bot personality) file located in https://github.com/cpacker/MemGPT/tree/main/memgpt/personas/examples, and likewise it will look for the human (user personality) file located in https://github.com/cpacker/MemGPT/tree/main/memgpt/humans/examples.

These have defaults - if you want to provide your own persona file, for example, "custom.txt" with some custom instructions ("You are a super cool bot that does magic tricks"), create the "custom.txt" file inside the personas/examples directory, add the content inside it ("You are a .... "), then run main.py with the extra flag:

```sh
# using arg "custom" since we created "custom.txt"
python main.py --persona custom
```

If this still doesn't work for you, please let me know and I'll reopen the issue (and please include a full stack trace / screenshot of your command + outputs which will help a lot).
