### ISSUE TITLE
update my profile

### ISSUE THREAD

**Issue by legaltextai** [cpacker/MemGPT#72]
so when i chat , and update my information, apparently it is not saved in the default profile. does it have an option to save information i share and refer to it automatically next time? Thanks

**Comment by cpacker** [comment]
Use `/save` and `/load`. By default, `/load` will load the most recent files created with `/save`, but you can pass a specific .json file if you want to load a specific checkpoint/model.

https://github.com/cpacker/MemGPT#interactive-cli-commands
