### ISSUE TITLE
is it supposed to save info across chat session?

### ISSUE THREAD

**Issue by rickoneeleven** [cpacker/MemGPT#75]
seems to be persistent for the one session (running locally), but if i try /save /memorylimit /exit

when i start a new session, nothing has been written to /Users/rick111/onedrive/MemGPT/memgpt/humans/examples/ryan.txt

starting with: python main.py --human ryan.txt

**Comment by MrDOSmile** [comment]
It's not written to that location. I personally changed the location the conversations save to and added my own profile conversation auto-loader.

**Comment by legaltextai** [comment]
it does not save with /save for me either

**Comment by rickoneeleven** [comment]
> It's not written to that location. I personally changed the location the conversations save to and added my own profile conversation auto-loader.

ahhh thanks, i'll pull your repo later

**Comment by cpacker** [comment]
@rickoneeleven use `/save` and `/load`. By default, `/load` will load the most recent files created with `/save`, but you can pass a specific .json file if you want to load a specific checkpoint/model. Files are stored in `/saved_state`.

The .txt human and persona files are only used at the very beginning, so they won't be updated - MemGPT "ingests" them and uses them to initialize its memory state (which you can see with `/memory`). When you do `/save`, part of what's getting saved is MemGPT's current memory state.

So if you load with a human.txt file that says "Name: Chad", you tell MemGPT to correct it to "Brad", you'll notice the txt file didn't change, but the output of `/memory` did. Now when you `/load` that specific checkpoint later, if you do `/memory`, you should still see the updated memory (Brad, not Chad).

@legaltextai @rickoneeleven let me know if this is still unclear or if things are broken and I can reopen the issue.

https://github.com/cpacker/MemGPT#interactive-cli-commands

**Comment by rickoneeleven** [comment]
ahhhhhhhhhhhhh! awesome, thank you. It was my misunderstanding, appreciate your detailed response.
