### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by Naozumi520** [cpacker/MemGPT#792]
**Describe the bug**
Missing files

**Please describe your setup**

- [x] MemGPT version
  - 0.2.11
- [x] How did you install memgpt?
  - `pip install pymemgpt`
- [x] Describe your setup
  - Windows 11
  - How are you running `memgpt`? (`cmd.exe`)

**Screenshots**
![image](https://github.com/cpacker/MemGPT/assets/52615455/c89433e5-d7ed-449d-8f29-5d8fa8d9a04f)

**Additional context**

```
C:\Users\Naozu\Desktop\Natsuki>memgpt configure
? Select LLM inference provider: local
? Select LLM backend (select 'openai' if you have an OpenAI compatible proxy): openai
? Enter default endpoint: http://127.0.0.1:5198/v1/
? Select default model (recommended: gpt-4): [see all options]
Warning: not all models shown are guaranteed to work with MemGPT
? Select default model (recommended: gpt-4): gpt-3.5-turbo
? Select embedding provider: local
? Select default preset: memgpt_chat
? Select default persona: memgpt_starter
? Select default human: basic
? Select storage backend for archival data: local
📖 Saving config to C:\Users\Naozu\.memgpt\config

C:\Users\Naozu\Desktop\Natsuki>memgpt run --agent memgpt_starter --model-endpoint-type webui --model-endpoint http://localhost:5198/v1
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Naozu\\AppData\\Local\\llama_index\\models--BAAI--bge-small-en-v1.5\\snapshots\\c202d20b1417db2e392c8aad36b6056867218dce\\config.json'
```

---

If you're not using OpenAI, please provide additional information on your local LLM setup:

**Local LLM details**

If you are trying to run MemGPT with local LLMs, please provide the following information:

- [x] The exact model you're trying to use (My SFT version of `blossom-v3_1-yi-34b`)
- [x] The local LLM backend you are using (web UI)
- [x] Your hardware for the local LLM backend (local computer, windows11)

**Comment by Alino** [comment]
First I had issues installing it (python sucks with dependencies) so I used the poetry way and that worked. But then when trying to run it, I get

<img width="584" alt="image" src="https://github.com/cpacker/MemGPT/assets/763194/1e197d85-5ae5-4cd9-a67d-3eb1d006f6d4">

**Comment by cpacker** [comment]
@Alino it looks like your `memgpt run` is calling a version of MemGPT installed into Python 3.9 (notice the path going `/lib/python3.9/...`).

Maybe try `pip uninstall pymemgpt`, then redo the poetry install with `poetry install`? Then the output of `which memgpt` should look like:
```
.../pypoetry/virtualenvs/pymemgpt-Pn3VVUO-py3.10/bin/memgpt
```

Also just an FYI this error is related to trying to use MemGPT with Python 3.9 - we only support 3.10-3.12 (https://github.com/cpacker/MemGPT/blob/main/pyproject.toml#L18).

**Comment by cpacker** [comment]
Going to close because I think should solve your problem but feel free to reopen if it doesn't
