### ISSUE TITLE
Determine how to handle changing embedding models/dimensions 

### ISSUE THREAD

**Issue by sarahwooders** [cpacker/MemGPT#849]
**Is your feature request related to a problem? Please describe.**
For DB tables storing recall memory, archival memory, and external data sources, we have an embedding column. This embedding column needs to have a pre-defined size (e.g. `Vector(N)`) when the table is created and cannot be changes. This may cause issues for users as if they wish to change their embedding model, they will need to delete all data in these tables. 

**Describe the solution you'd like**

There are two possible solutions I can think of: 

**Option 1: Allow embeddings of different dimentionality to be saved in the same database** 

We can implement this by setting the embedding column size to `Vector(4098)` (or whatever is the maximum feasible embedding size), and zero-pad any vectors of smaller dimentionality. This will not affect vector similarity search and allow embeddings of different dimensions to be. 

Add the following columns to `AgentState` and `Source` tables (both which rely on embedding search)" 
* `embedding_model` - The model used to compute any embeddings
* `embedding_dim` - The dimentions of the embeddings 

For a single agent or source, we will still force usage of the same embedding model -- however _across_ users (sharing the same DB), this solution would allow usage of different embedding models. 

**Option 2: Force all embeddings in the database to be computed with the same model** 

This will disallow changing the embedding endpoint, and have the embedding model/endpoint for all users specified in `MemGPTConfig` which configures the server. 

If users or the service manager change their embedding endpoint, we will need to run some migration process on the DB that: 
1. Saves existing embeddings to some cache DB (to avoid future recomputation) 
2. Delete the existing DB table 
3. Re-compute embeddings with the new model for all rows that contained embeddings

**Comment by robbyt** [comment]
@sarahwooders have you considered copying the main config into the agent upon creation?

Consider the main config to be the primary template, and then each agent a copy of that prototype template. That way, migrating major settings can be done per-agent.

**Comment by sarahwooders** [comment]
@robbyt yes the agent contains the embedding model information (in `AgentState.embedding_config`). This issue should be resolved with #852
