### ISSUE TITLE
 AttributeError: 'MemGPTConfig' object has no attribute 'model'

### ISSUE THREAD

**Issue by CUexter** [cpacker/MemGPT#858]
**Describe the bug**
In memgpt 0.2.12, when running memgpt configure, after selecting the default endpoint. The error pops out.

**Please describe your setup**

- [ ] MemGPT version
  0.2.12
- [ ] How did you install memgpt?
  Git clone, poetry
- [ ] Describe your setup
  Linux terminal

**Screenshots**

**Additional context**

**Comment by sarahwooders** [comment]
This should be fixed with #852 but please re-open if not!
