### ISSUE TITLE
Warning: AutoGen message was missing fields 

### ISSUE THREAD

**Issue by bitsnaps** [cpacker/MemGPT#860]
**Describe the bug**
A warning message appears when running the MemGPT_Autogen using an open LLM (based on `Mistral`) example:
```
Warning: AutoGen message was missing fields 
```

Describe of setup:
- latest MemGPT version
  - `memgpt version == `0.2.11`
- Installation of memgpt:
  - `pip install pymemgpt pymemgpt`
- OS setup
  - Linux/Colab with GPU T4.
  
Model:
- [x] The exact model :`dolphin-2.6-mistral-7B-GPTQ`
- [X] The local LLM backend: webui

**Comment by bitnom** [comment]
This also happens with openai.
