### ISSUE TITLE
main.py:328: DeprecationWarning: There is no current event loop   loop = asyncio.get_event_loop()

### ISSUE THREAD

**Issue by JonMike12341234** [cpacker/MemGPT#87]
C:\Users\Admin\Desktop\MemGPT\MemGPT>main.py --model gpt-3.5-turbo
C:\Users\Admin\Desktop\MemGPT\MemGPT\main.py:328: DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()
  
    1 You can create a new event loop in your thread if it does not have one. Here is a
     simple example:

   import asyncio

   loop = asyncio.new_event_loop()
   asyncio.set_event_loop(loop)

   2 You can upgrade your code to use asyncio.run(), which is the recommended way of
     running asyncio programs since Python 3.7. It automatically manages the event loop
     and closes it when the program finishes. For example:

   asyncio.run(your_async_function())

**Comment by sarahwooders** [comment]
Yes the async code needs to be removed, per #141

**Comment by cpacker** [comment]
@sarahwooders is there a way to silence this error for the time being via recommended python version or code diff?

**Comment by cpacker** [comment]
Default agent is now sync, can close @vivi ?

**Comment by vivi** [comment]
@cpacker default agent is not async (yet). closing this so that we can consolidate to #141
