### ISSUE TITLE
[Chat UI] Extend server.py with MemGPTConfig defaults & Model Availability

### ISSUE THREAD

**Issue by arduenify** [cpacker/MemGPT#920]
**Is your feature request related to a problem? Please describe.**
Currently, the `get_server_config_api_config_get` endpoint does not return the full `MemGPTConfig` defaults, which are crucial for initializing `AgentState` in the CLI. This limitation makes it challenging to populate defaults in the agent creation screen within the chat UI.

**Describe the solution you'd like**
1. Modify the [get_server_config_api_config_get endpoint](https://memgpt.readme.io/reference/get_server_config_api_config_get) to return the complete `MemGPTConfig` defaults as defined in [config.py](https://github.com/cpacker/MemGPT/blob/main/memgpt/config.py#L40). This change will allow the chat UI to automatically populate the default settings in the agent creation screen.
2. Implement a `get_available_models` function in `server.py`. This function should be capable of taking in an endpoint and returning a list of models available at that endpoint. When `GET http://localhost:8283/api/config` is called, it should internally call `get_available_models` on the endpoint it's returning, allowing the chat UI to use this data for model selection in the dropdown.

**Describe alternatives you've considered**
An alternative is to manually configure these settings, but it lacks the dynamic and user-friendly aspect of having them automatically populated based on the current configuration and available models.

**Additional context**
I can work on the REST API & React codebases if you don't mind handling the things I have listed above @cpacker. Let me know what you think!

**Comment by cpacker** [comment]
LGTM! Thanks for the quick update, will get these endpoints up ASAP
