### ISSUE TITLE
Error on Fedora 39 - SUCCESS!

### ISSUE THREAD

**Issue by philiprhoades** [cpacker/MemGPT#950]
I get the same error as #820 

but if I do "git clone" instead I get:

```
Collecting typer[all]<0.10.0,>=0.9.0 (from pymemgpt==0.3.0)
  Using cached typer-0.9.0-py3-none-any.whl (45 kB)
INFO: pip is looking at multiple versions of pymemgpt to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'pymemgpt' requires a different Python: 3.12.0 not in '<3.12,>=3.10'
```

I don't know Python but I would really like to get this working! - I have a use case that has been waiting for about ten years for this tech . .

Thanks,
Phil.

**Comment by CUexter** [comment]
downgrade your version of python. You need to use Python 3.11 or Python 3.10

**Comment by philiprhoades** [comment]
@CUexter ,

Thanks for responding but no improvement:

# rpm -qa | grep -e "^python3.1"
python3.11-libs-3.11.7-2.fc39.x86_64
python3.11-3.11.7-2.fc39.x86_64
python3.11-tkinter-3.11.7-2.fc39.x86_64

Thanks.

**Comment by CUexter** [comment]
you tried running `python --version` ?

**Comment by CUexter** [comment]
im not a fedora user but it is possible to install 2 versions of python on the same machine. You should be able to change which version is used

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CUexter** [comment]
https://linuxconfig.org/how-to-switch-between-python-versions-on-fedora-linux

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by philiprhoades** [comment]
OK, I installed v3.11 and worked out how to switch between them but I find that clunky and I don't really want to mess with apps that depend on python on my workstation so I set up a VM with podman and a Fedora 38 image - which used python3.11 and made some more progress being able to run: 

```
memgpt run
```
I now get a downloaded web page followed by:

```
) for address: https://api.memgpt.ai/v1/completions. Make sure that the vLLM server is running and reachable at https://api.memgpt.ai/v1/completions.
? Retry agent.step()? (Y/n)
```
Retrying doesn't help - what do I do now?

Thanks,
Phil.

**Comment by philiprhoades** [comment]
People,

I'm not sure what changed on the MemGPT server side but the chat is now working!

I attach a copy of the first chat re Cryonics and Neural Archives and my project to create "Avatar Phi Rho" - which went very well and was exactly what I was hoping for! - for people's interest.

I will now get more involved in this project and contribute where and as much as I can . . 

Thanks to all who created this project!

Phil.

**Comment by sarahwooders** [comment]
Closing since duplicated with #954
