### ISSUE TITLE
memgpt server fails once context memory is full (when it calls archival_memory_insert) 

### ISSUE THREAD

**Issue by vinayak-revelation** [cpacker/MemGPT#953]
**Describe the bug**
When I send it messages back and forth it seems to be OK. But as soon as I send it messages like "remember my son's name is travis" or anything to trigger it's internal save function, it fails. and after that the agent cannot be accessed on any future messages.
I am using GPT4, I don't know if this happens to all functions but I was noting this behavior whenever it's mem got full and it tried to save to memory. So I made it do this on purpose by saying -- "My son is called X and remember it"
That dialog works if I chat with memgpt using memgpt run on command line and tell it to remember. Just that the memgpt server one when called from REST API does not work
Also, then I went back to the backend and started it from command line with the same agent that was stuck and I keep getting this error

assert all([v is not None for v in [self.text, self.role]]), vars(self)
AssertionError: {'id': UUID('f1efcb9a-3c1f-4c58-8485-fbd61c0f103d'), 'user_id': UUID('00000000-0000-0000-0000-e2b55ff325b7'), 'agent_id': UUID('ff734e10-43a0-4354-983a-68bba2fb620c'), 'text': None, 'model': 'gpt-4', 'created_at': datetime.datetime(2024, 2, 2, 16, 43, 2, 851922), 'role': 'assistant', 'name': None, 'embedding': None, 'embedding_dim': None, 'embedding_model': None, 'tool_calls': [<memgpt.data_types.ToolCall object at 0x12602b450>], 'tool_call_id': None}

**Please describe your setup**

- [ ] MemGPT version
  - 0.3.0 (Today's build fro source and pip installed via pip install -e .)
- [ ] How did you install memgpt?
  - git clone and then pip install -e .
- [ ] Describe your setup
  - MacOS
  - Running macOS both via memgpt run and memgpt server. memgpt server seems like is broken which then breaks the agent in memgpt run as well.

---

**Comment by vinayak-revelation** [comment]
This also happens when it fails other function calling, maybe archival memory insert failing is a subset of the larger problem of function calling failing?

**Comment by dlaliberte** [comment]
I was able to fix context memory limit exceeded errors, but my fix may only apply to the local llm cases.

I've also seen the error about 'assert all([v is not None for v in [self.text, self.role]])' and just commented out the assert line.

**Comment by sarahwooders** [comment]
Could you please post the line number of the failing assert? We fixed a similar issue recently, but it's in a couple places.

**Comment by TomasLipton** [comment]
@sarahwooders I got the same error. I'm running ubuntu and did installation by pip install -e (ver 0.3). Error happens in both memgpt run and memgpt server. Here is the exception trace. 

`An exception occurred when running agent.step(): 
Traceback (most recent call last):
  File "/root/MemGPT/memgpt/main.py", line 347, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/MemGPT/memgpt/main.py", line 323, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
                                                                                          ^^^^^^^^^^^^^^^^^^
  File "/root/MemGPT/memgpt/agent.py", line 673, in step
    raise e
  File "/root/MemGPT/memgpt/agent.py", line 582, in step
    input_message_sequence = self.messages
                             ^^^^^^^^^^^^^
  File "/root/MemGPT/memgpt/agent.py", line 270, in messages
    return [msg.to_openai_dict() for msg in self._messages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/MemGPT/memgpt/agent.py", line 270, in <listcomp>
    return [msg.to_openai_dict() for msg in self._messages]
            ^^^^^^^^^^^^^^^^^^^^
  File "/root/MemGPT/memgpt/data_types.py", line 249, in to_openai_dict
    assert all([v is not None for v in [self.text, self.role]]), vars(self)
AssertionError: {'id': UUID('0bfe0de7-c0e2-4cde-922c-e29eef3837cd'), 'user_id': UUID('00000000-0000-0000-0000-de8925efc5a7'), 'agent_id': UUID('c8c09cc9-9a9d-4777-a0aa-260eab1a80eb'), 'text': None, 'model': 'gpt-4', 'created_at': datetime.datetime(2024, 2, 8, 19, 27, 42, 32364, tzinfo=datetime.timezone.utc), 'role': 'assistant', 'name': None, 'embedding': None, 'embedding_dim': None, 'embedding_model': None, 'tool_calls': [<memgpt.data_types.ToolCall object at 0x7fc91c1297d0>], 'tool_call_id': None}`

**Comment by sarahwooders** [comment]
@TomasLipton  - thanks for posting this, I'm having trouble reproducing the error but I think #976 should fix it this time (hopefully)
