### ISSUE TITLE
Quickstart fails every way

### ISSUE THREAD

**Issue by cleesmith** [cpacker/MemGPT#955]
**Describe the bug**
It does not work

**Please describe your setup**

- [ ] MemGPT version
  - memgpt version = 0.3.0
- [ ] How did you install memgpt?
  - pip install pymemgpt
- [ ] Describe your setup
  - MacOS = Sonoma 14.3, MacBook Pro M3 Max 128GB
  - Terminal with conda 

**Screenshots**
... in the Terminal:
memgpt run

? Would you like to select an existing agent? Yes
? Select agent: UnderstandingLighthouse

🔁 Using existing agent UnderstandingLighthouse

Hit enter to begin (will request first MemGPT message)

An exception occurred when running agent.step(): 
Traceback (most recent call last):
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/main.py", line 356, in run_agent_loop
    new_messages, user_message, skip_next_user_input = process_agent_step(user_message, no_verify)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/main.py", line 332, in process_agent_step
    new_messages, heartbeat_request, function_failed, token_warning, tokens_accumulated = memgpt_agent.step(
                                                                                          ^^^^^^^^^^^^^^^^^^
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/agent.py", line 676, in step
    raise e
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/agent.py", line 596, in step
    response = self._get_ai_reply(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/agent.py", line 362, in _get_ai_reply
    raise e
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/agent.py", line 342, in _get_ai_reply
    response = create(
               ^^^^^^^
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/llm_api_tools.py", line 373, in wrapper
    raise e
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/llm_api_tools.py", line 346, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/llm_api_tools.py", line 465, in create
    return get_chat_completion(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/local_llm/chat_completion_proxy.py", line 159, in get_chat_completion
    result, usage = get_vllm_completion(endpoint, auth_type, auth_key, model, prompt, context_window, user)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cleesmith/anaconda3/envs/memgpt/lib/python3.11/site-packages/memgpt/local_llm/vllm/api.py", line 46, in get_vllm_completion
    raise Exception(
Exception: API call got non-200 response code (code=521, msg=<!DOCTYPE html>

 <html class="no-js" lang="en-US"> 
<head>

<title>api.memgpt.ai | 521: Web server is down</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />

</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              <span class="inline-block">Web server is down</span>
              <span class="code-label">Error code 521</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_521&utm_campaign=api.memgpt.ai" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2024-02-04 16:29:12 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">
                  
<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Browser
    
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_521&utm_campaign=api.memgpt.ai" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Newark</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_521&utm_campaign=api.memgpt.ai" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    
    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    
  </div>
  <span class="md:block w-full truncate">api.memgpt.ai</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    
    Host
    
  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server is not returning a connection. As a result, the web page is not displaying.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                          <h3 class="text-15 font-semibold mb-2">If you are a visitor of this website:</h3>
      <p class="mb-6">Please try again in a few minutes.</p>

      <h3 class="text-15 font-semibold mb-2">If you are the owner of this website:</h3>
      <p><span>Contact your hosting provider letting them know your web server is not responding.</span> <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/200171916-Error-521">Additional troubleshooting information</a>.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">85044a89daaf7d20</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">2603:7080:5d4a:d500:f836:2a4b:1176:b94c</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_521&utm_campaign=api.memgpt.ai" id="brand_link" target="_blank">Cloudflare</a></span>
    
  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div>

    </div>
</div>
</body>
</html>
) for address: https://api.memgpt.ai/v1/completions. Make sure that the vLLM server is running and reachable at https://api.memgpt.ai/v1/completions.
? Retry agent.step()? No
> Enter your message:                                                           

Cancelled by user

Finished.

---

...... 
It seems to always try to go to: https://api.memgpt.ai/v1/completions  (mothership?) ... regardless of the "configure" being 
set to: openai or local.  Why?
It's never a good impresion when the simple quickstart does not work.

**Comment by cpacker** [comment]
Hey @cleesmith thanks for opening the issue - our free endpoint was down earlier today but is back online (https://status.memgpt.ai/status/all). Can you confirm if it's working now?

In the future we can try to revise the error messaging to be a little more communicative - eg in this case, it might have helped if we returned / printed an error that looked like:

>  Error: can't reach the MemGPT hosted endpoint. The MemGPT hosted endpoint may be offline - you can check its current status at https://status.memgpt.ai

**Comment by sarahwooders** [comment]
@cleesmith you can see the docs for instructions on how to run MemGPT with local models https://memgpt.readme.io/docs/local_llm

As @cpacker mentioned, `memgpt quickstart` is connected to our hosted endpoint (which went down for about a day) since local LLMs require more configuration. 

Going to close this issue for now, but let us know if you have other issues/questions!
