### ISSUE TITLE
a very small bug that potentially make the package not runnable

### ISSUE THREAD

**Issue by Ignorance999** [cpacker/MemGPT#956]
**Describe the bug**
Please correct me if i am wrong as i am a newbie. As i install memgpt today, i get the error after typing memgpt run in cmd.

  ... "venv\lib\site-packages\memgpt\server\server.py", line 115, in LockingServer
    def user_message(self, user_id: str, agent_id: str, message: str) -> None:
TypeError: 'staticmethod' object is not callable

i suspect it is the problem of the following code, after i comment the staticmethod it no longer has the error

\#server/server.py line 87
class LockingServer(Server):
    \#@staticmethod
    def agent_lock_decorator(func: Callable) -> Callable:

**Please describe your setup**

- [ ] MemGPT version
  - What is the output of `memgpt version`? 
  Version: 0.2.11

- [ ] How did you install memgpt?
  - `pip install -U pymemgpt`
  - 
- [ ] Describe your setup
  - What's your OS (Windows)?
  - How are you running `memgpt`? (conda)

**Comment by heshaojia** [comment]
same question, but I can run it in Linux

**Comment by svenhaitjema** [comment]
This is probably due to the python version on your system. I had the same issue on macOS that had python3.9.8 installed. Upgrading to 3.11 fixed the issue.

**Comment by sarahwooders** [comment]
Yes python 3.9 is unfortunately not supported. I'll close this issue for now but please re-open if you see this with python >=3.10
